### ISSUE TITLE
Changing Album After Selecting Images

### ISSUE THREAD

**Issue by Chefda** [zhangao0086/DKImagePickerController#10]
Hello Again,

I think there is a bug, in this scenario. Can you check this out?

**Comment by Chefda** [comment]
Confused. It's about same photos in different albums. Not an issue i guess. They have same url's.

Thanks.

**Comment by zhangao0086** [comment]
Hello @Chefda 

When they have the same URLs and they are in different albums and they are in different selection status, I will think it's a bug. However, I has not found this situation. Any hints? Thanks.

**Comment by Chefda** [comment]
Create new album and add photos to new album from another album. 

In DKImageController select photos than change album. When you change album these photos will be in same selection status. Because they are same photos right?

**Comment by zhangao0086** [comment]
Yes, I think it's not a bug. And you?

**Comment by Chefda** [comment]
No it's cool. Issue closed.
