### ISSUE TITLE
hi.It will crash when I click button 'Done' without any image selected

### ISSUE THREAD

**Issue by ETHANAIR** [zhangao0086/DKImagePickerController#105]
```
internal func done() {
		self.presentingViewController?.dismissViewControllerAnimated(true, completion: nil)
        self.didSelectAssets?(assets: self.selectedAssets)
    }
```
I think you have to pass judgement on it when I not selected

**Comment by zhangao0086** [comment]
Thanks!
But I cannot reproduce it. The `selectedAssets` will to be an empty array `[]` If you click button 'Done' without any image selected.

**Comment by zhangao0086** [comment]
ping...

**Comment by zhangao0086** [comment]
Feel free to re-open if your issue is not solved.
