### ISSUE TITLE
Can I use this from Objective-C?

### ISSUE THREAD

**Issue by Pokotuz** [zhangao0086/DKImagePickerController#11]
Im just finding new ImagePicker controller and I found yours is very cool one. Is there any advice to use it from obj-c ?

Thx a lot.
// sry for my bad Eng and Knowledge.

**Comment by zhangao0086** [comment]
Of couse~! I will update README :)

**Comment by Pokotuz** [comment]
Thx a lot man. Anyway from many Custom ImagePicker Controller I found a problem that I can only see 49 photos from "All Photos". Do I miss something?

**Comment by zhangao0086** [comment]
That seemed strange. I've never encountered that...

**Comment by zhangao0086** [comment]
Look this: https://github.com/zhangao0086/DKImagePickerController#how-to-use-in-objective-c

**Comment by Pokotuz** [comment]
Thank you very much.

**Comment by hiteshwork** [comment]
when i press the select button after selecting images , the method
-(void)imagePickerController:(DKImagePickerController * _Nonnull)imagePickerController didSelectAssets:(NSArray<DKAsset *> * _Nonnull)didSelectAssets is not called.
However the block [pickerController setDidSelectAssets:^(NSArray * __nonnull assets) {
     NSLog(@"didSelectAssets");
 }]; is called. How to get the images selected using your library in objective c? I want to display them on an imageview.
