### ISSUE TITLE
Delete Selected Photos?

### ISSUE THREAD

**Issue by kheniparth** [zhangao0086/DKImagePickerController#110]
Hi, 

First of all, Thank you very much for this library. I want to know how can I ask the user if he wants to delete selected photos from camera roll or not. I already knew how we can do it with default ImagePickerController but not with this library.

 I know there is one issue related this question but I didn't get it.

Thank you in advance.

**Comment by kheniparth** [comment]
Hi again, 

Sorry to bother you but I found the solution so I will close this issue. I attached the code so if other want to do the same they can use it.

var tempPHAssets : [PHAsset] = []
//...
pickerController.didSelectAssets = { (assets: [DKAsset]) in

  for asset in assets{
     self.tempPHAssets.append(asset.originalAsset!)
  }
  PHPhotoLibrary.sharedPhotoLibrary().performChanges( {
      PHAssetChangeRequest.deleteAssets(self.tempPHAssets)
      },
      completionHandler: { success, error in
      print("Finished deleting asset. %@", (success ? "Success" : error))
 })
}

**Comment by zhangao0086** [comment]
👍
