### ISSUE TITLE
Use of unresolved identifier 'DKImagePickerController'

### ISSUE THREAD

**Issue by laser2302** [zhangao0086/DKImagePickerController#111]
I manually copied DKCamera and DKImagePickerController into my application project, but when I put this line of code:

let pickerController = DKImagePickerController()

It gives the error "Use of unresolved identifier 'DKImagePickerController'". Can you please tell me how I resolve this issue?

**Comment by zhangao0086** [comment]
What language your project uses? swift? oc?

**Comment by zhangao0086** [comment]
ping...

**Comment by kenrickvaz** [comment]
I am having the same issue...using swift

**Comment by zhangao0086** [comment]
@kenrickvaz 
Are you using CocoaPods? 
I've uploaded a demo project:[TestDKImagePickerControllerSwift.zip](https://github.com/zhangao0086/DKImagePickerController/files/299845/TestDKImagePickerControllerSwift.zip)

**Comment by danieljin** [comment]
Bump. Swift 3 Test project please?

Use of unresolved identifier 'DKImagePickerController'

**Comment by zhangao0086** [comment]
@danieljin 
There is a Swift 3 demo project: [TestDKImagePickerControllerSwift.zip](https://github.com/zhangao0086/DKImagePickerController/files/656371/TestDKImagePickerControllerSwift.zip)

**Comment by danieljin** [comment]
I think mentioning that import DKImagePickerController is required in the README would be helpful.

Also, that it's now self.present in swift 3 instead of self.presentViewController

**Comment by zhangao0086** [comment]
@danieljin Thank you for reminding me of that! I'll update in the next version :)
