### ISSUE TITLE
image duplicate

### ISSUE THREAD

**Issue by brokeniceinteractive** [zhangao0086/DKImagePickerController#115]
if i select a cutted image i obtain a photo twice from this method: 

`fetchOriginalImageWithCompleteBlock({ (image) -> Void in`

**Comment by zhangao0086** [comment]
it sounds a bit strange :( I cannot reproduce it :(

**Comment by zhangao0086** [comment]
ping...

**Comment by brokeniceinteractive** [comment]
I have do this take a Photo forma camera, edit it with iOS image and cut and resize it! Then when i select this from the app i obtain twice!

**Comment by zhangao0086** [comment]
I think the problem is fixed now :)

**Comment by brokeniceinteractive** [comment]
i updated to last version 3.2.1 but the problem is the same!

**Comment by brokeniceinteractive** [comment]
Sorry!!!!!! the problem has been solved! thanks!  another question, before the update i used this:

`imagesel.fetchAVAssetWithCompleteBlock({ (avAsset) -> Void in
avAsset.URL
})`

but now does not work, how can i get URL?

**Comment by brokeniceinteractive** [comment]
i solved in this way, is the right way?

let urlAsset = avAsset.AVAsset as! AVURLAsset
let url = urlAsset.URL

**Comment by zhangao0086** [comment]
This way works on normal video, for slow motion video, avAsset is an `AVComposition` not `AVURLAsset`.
You can try the `PHImageFileSandboxExtensionTokenKey` of the `info`:
![3de95ac4-dacb-4cb1-b558-755f7755ba96](https://cloud.githubusercontent.com/assets/7742344/15532846/57304c24-2294-11e6-890a-7ce644b2e340.png)

**Comment by brokeniceinteractive** [comment]
will be nice something like this:

`fune isNormalVideo(asset:AVAsset){
if let _ = asset as? [AVURLAsset] {
    return true
}
return false
}`

and

`fune isSlowMotionVideo(asset:AVAsset){
if let _ = asset as? [AVComposition] {
    return true
}
return false
}`

What do you think?

**Comment by zhangao0086** [comment]
It's no problem :)

**Comment by brokeniceinteractive** [comment]
This are correct:

`func isNormalVideo(asset:AVAsset) -> Bool{
        if let _ = asset as? AVURLAsset {
            return true
        }
        return false
    }
    func isSlowMotionVideo(asset:AVAsset) -> Bool{
        if let _ = asset as? AVComposition {
            return true
        }
        return false
    }`

**Comment by zhangao0086** [comment]
Maybe I should go see an opthamologist 😅😅😅

**Comment by brokeniceinteractive** [comment]
👍 no problem!

**Comment by zhangao0086** [comment]
Close this thread.
