### ISSUE TITLE
Memory problem

### ISSUE THREAD

**Issue by leobouilloux** [zhangao0086/DKImagePickerController#116]
Hi, I'm currently having similar problem initially posted by ArjunSa786.
When I select multiple images (around 20), it crashes on my iPhone 6.

Here is the code involved, I know I'm doing  something wrong can you help me please?
```Swift
        pickerController.didSelectAssets = { (assets: [DKAsset]) in
            for a in assets {
                let date = a.originalAsset!.creationDate!
                let dateFormatter: NSDateFormatter = NSDateFormatter()
                dateFormatter.dateFormat = "YYYY-MM-dd_hh-mm-ss"
                let pictureDate: String = dateFormatter.stringFromDate(date)
                
                a.fetchOriginalImageWithCompleteBlock({ (image, info) in
                    let filename = documentsDirectory.stringByAppendingPathComponent("\(pictureDate).jpg")
                    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0)) {
                        UIImageJPEGRepresentation(image!, 0.65)!.writeToFile(filename, atomically: true)
                    }
                })
            }
        }
```
For each iteration in the loop the memory increase significally (arround 30-50mB by image)

Here is the message received on the output: 

> Message from debugger: Terminated due to memory issue 

Hope you can help,

Kind regards,

**Comment by leobouilloux** [comment]
More information:
- Problem still occurs with version 3.2 freshly installed
- The code bellow gives me a memory warning and starts to crash when I select around 25 pictures:

```Swift
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0)) {     
   pickerController.didSelectAssets = { (assets: [DKAsset]) in
        for a in assets {
            a.fetchOriginalImageWithCompleteBlock({ (image, info) in
            })
        }
    }
}
```

**Comment by RainbowMango** [comment]
I met same problem too. 
I used fetchFullScreenImageWithCompleteBlock, much better now.

**Comment by leobouilloux** [comment]
@RainbowMango: I can't use this solution, because I need to upload the picture with its original quality.
I fixed the problem partially, it's now working with fetchOriginalImageWithCompleteBlock regardless how much pictures are selected, but it kinda freeze the application (probably doing something wrong with threads).

Here is my code :

```swift
    func DKImagePicker(sourceType: DKImagePickerControllerSourceType) {
        let paths = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)
        let documentsDirectory: NSString = paths[0]
        let pickerController = DKImagePickerController()
        pickerController.sourceType = sourceType
        
        pickerController.didSelectAssets = { (assets: [DKAsset]) in
            for a in assets {
                let dateFormatter: NSDateFormatter = NSDateFormatter()
                dateFormatter.dateFormat = "YYYY-MM-dd_hh-mm-ss"
                let pictureDate: String = dateFormatter.stringFromDate(a.originalAsset!.creationDate!)
                
                dispatch_sync(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0)) {
                        a.fetchOriginalImage(false, completeBlock: { (image, info) in
                            let filename = documentsDirectory.stringByAppendingPathComponent("\(pictureDate).jpg")
                            UIImageJPEGRepresentation(image!, 1)!.writeToFile(filename, atomically: true)
                        })
                }
            }
        }
        self.presentViewController(pickerController, animated: true) {}
    }
```


Some help could be nice :)

Kind regards!

**Comment by zhangao0086** [comment]
@leobouilloux I think Your approach is right 👍 Some images are pretty big, so `writeToFile` is a good idea :)
Just want to add a little optimization to it:
Creating an NSDateFormatter is very slow. Instead, you can create the date formatter once and reuse it.

**Comment by leobouilloux** [comment]
@zhangao0086 That's a good point thanks! After correcting that, I still have the UI blocked for 5-10 sec (depending on the number of images picked), but it's a bit faster. Thank you again for your time 👍

**Comment by zhangao0086** [comment]
Try this:

```swift
let dateFormatter: NSDateFormatter = NSDateFormatter()
dateFormatter.dateFormat = "YYYY-MM-dd_hh-mm-ss"
dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0)) {
    let group = dispatch_group_create()
    
    for a in assets {
        dispatch_group_enter(group);

        let pictureDate: String = dateFormatter.stringFromDate(a.originalAsset!.creationDate!)
        a.fetchOriginalImageWithCompleteBlock({ (image, info) in
            let filename = documentsDirectory.stringByAppendingPathComponent("\(pictureDate).jpg")
            UIImageJPEGRepresentation(image!, 1)!.writeToFile(filename, atomically: true)

            dispatch_group_leave(group)
        })
    }
    
    dispatch_group_notify(group, dispatch_get_main_queue(), { 
        // finished ...
    })
}
```

**Comment by leobouilloux** [comment]
@zhangao0086 Still lagging on my side. I did not observe any improvement with your code.
To perform the test, I picked 30 pictures from the library.

If there is any information useful that I forgot to tell you,  let me know, but I'm okay with this lag, it's not a huge problem. I'll investigate on this problem on my side, thanks for your help :)

**Comment by zhangao0086** [comment]
Do you use `dispatch_async ` instead of using `dispatch_sync`?

**Comment by leobouilloux** [comment]
Sure, here is my code with your modifications:

```swift
pickerController.didSelectAssets = { (assets: [DKAsset]) in
            let dateFormatter: NSDateFormatter = NSDateFormatter()
            dateFormatter.dateFormat = "YYYY-MM-dd_hh-mm-ss"
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0)) {
                let group = dispatch_group_create()
                for a in assets {
                    dispatch_group_enter(group)
                    let pictureDate: String = dateFormatter.stringFromDate(a.originalAsset!.creationDate!)
                    
                    a.fetchOriginalImage(false, completeBlock: { (image, info) in
                            let filename = documentsDirectory.stringByAppendingPathComponent("\(pictureDate).jpg")
                            UIImageJPEGRepresentation(image!, 1)!.writeToFile(filename, atomically: true)
                            dispatch_group_leave(group)
                        })
                    }
                dispatch_group_notify(group, dispatch_get_main_queue(), {
                    print("Done")
                })
            }
}
```

"Done" is printed when the UI is no longer blocked.

**Comment by zhangao0086** [comment]
Got. The completeBlock of the `fetchOriginalImageWithCompleteBlock` is executed on the main thread. 
```swift
pickerController.didSelectAssets = { (assets: [DKAsset]) in
    let dateFormatter: NSDateFormatter = NSDateFormatter()
    dateFormatter.dateFormat = "YYYY-MM-dd_hh-mm-ss"

    let group = dispatch_group_create()

    for a in assets {
        dispatch_group_enter(group);

        let pictureDate: String = dateFormatter.stringFromDate(a.originalAsset!.creationDate!)
        a.fetchOriginalImageWithCompleteBlock({ (image, info) in
            dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0)) {

                let filename = documentsDirectory.stringByAppendingPathComponent("\(pictureDate).jpg")
                UIImageJPEGRepresentation(image!, 1)!.writeToFile(filename, atomically: true)

                dispatch_group_leave(group)
            }
        })
    }

    dispatch_group_notify(group, dispatch_get_main_queue(), { 
        // finished ...
    })
}
```

**Comment by leobouilloux** [comment]
It's no longer blocking the UI, but I now got memory issues.
`2016-05-19 16:09:17.962 Pydio[1793:570725] Received memory warning.`
`2016-05-19 16:09:19.237 Pydio[1793:570725] Received memory warning.`
`Message from debugger: Terminated due to memory issue`

I returned to my initial problem.

**Comment by zhangao0086** [comment]
😅😅😅
I'll give you a perfect solution later.

**Comment by leobouilloux** [comment]
Hahaha, sorry :) I now that I must have a very specific demand. For now I'll keep my code with dispatch_sync, it maybe block the UI for a few sec, but it doesn't crash. 
And again, thank you very much for your time 👍 👍 👍

**Comment by zhangao0086** [comment]
I've added two utility methods:
```swift
public func writeImageToFile(path: String, completeBlock: (success: Bool) -> Void)

public func writeAVToFile(path: String, presetName: String, completeBlock: (success: Bool) -> Void)
```

Now you can try this:
```swift
let dateFormatter: NSDateFormatter = NSDateFormatter()
dateFormatter.dateFormat = "YYYY-MM-dd_hh-mm-ss"

pickerController.didSelectAssets = { (assets: [DKAsset]) in
	let group = dispatch_group_create()
	
	for a in assets {
		dispatch_group_enter(group);
		
		let pictureDate: String = dateFormatter.stringFromDate(a.originalAsset!.creationDate!)
		
		if a.isVideo {
			let filename = documentsDirectory.stringByAppendingPathComponent("\(pictureDate).mov")
			a.writeAVToFile(filename, presetName: AVAssetExportPresetHighestQuality, completeBlock: { (success) in
				dispatch_group_leave(group)
			})
		} else {
			let filename = documentsDirectory.stringByAppendingPathComponent("\(pictureDate).jpg")
			a.writeImageToFile(filename, completeBlock: { (success) in
				dispatch_group_leave(group)
			})
		}
	}
	
	dispatch_group_notify(group, dispatch_get_main_queue(), {
		// finished ...
		print("finished")
	})
}
```

**Comment by leobouilloux** [comment]
Hi there, thank you for your update!
I've seen you added these new functions to the develop branch, so I had to modify my Podfile.
It's working perfectly thank you very much.

I only have one suggestion that could be useful in my case and maybe for everyone else.
Adding a "quality rate" parameter will be perfect (is it already the case for video?)
I mean something like this function : 
```swift
UIImageJPEGRepresentation(image: UIImage, compressionQuality: Float)
```

Gonna check when you'll push the code to the stable branch!

Thank you very much, you rock!

**Comment by zhangao0086** [comment]
Closing this thread...

**Comment by mariogalvao** [comment]
I had the same problem. After write my images to file (writeImageToFile), how can I read then? I tried this code below, that I already use in other cases successfully, but it did not work.

    func loadOriginalImage(i: Int) -> UIImage? {
        
        let originalFile = documentsUrl.appendingPathComponent("Original_image_id_\(i).jpg")
        print(originalFile.absoluteString)
        
        do {
            let imageData = try Data(contentsOf: originalFile)
            return UIImage(data: imageData)
        } catch {
            print("Erro ao ler imagem original do arquivo: \(error)")
        }
        return nil
        
    }
