### ISSUE TITLE
Crash after picture ... sometimes

### ISSUE THREAD

**Issue by aeterDraco** [zhangao0086/DKImagePickerController#118]
The DKImagePicker crashes after taking picture, the problem is that it only occurs sometimes so it becomes really hard to debug, any ideas?

![dkimagepicker](https://cloud.githubusercontent.com/assets/984130/14980208/679618ba-1127-11e6-95d6-eecd5bdad6ab.png)

**Comment by aeterDraco** [comment]
I mange to catch the crash on the debugger, this is the stack that i get on the debugger
<img width="800" alt="dkimageerror" src="https://cloud.githubusercontent.com/assets/984130/15075947/745eb930-13a7-11e6-87bc-6ab5978e3b29.png">
<img width="800" alt="dkimageerror2" src="https://cloud.githubusercontent.com/assets/984130/15075948/7464ed96-13a7-11e6-87df-6717c3e88512.png">

**Comment by zhangao0086** [comment]
Hi @aeterDraco 
In the newly version, I've replace the `viewWillLayoutSubviews` to this:
```swift
override func viewWillLayoutSubviews() {
	super.viewWillLayoutSubviews()
	
	if let currentViewSize = self.currentViewSize where CGSizeEqualToSize(currentViewSize, self.view.bounds.size) {
		return
	} else {
		currentViewSize = self.view.bounds.size
	}

	self.collectionView?.collectionViewLayout.invalidateLayout()
}
```

**Comment by aeterDraco** [comment]
Thanks!!!
