### ISSUE TITLE
Russian language

### ISSUE THREAD

**Issue by oxozle** [zhangao0086/DKImagePickerController#120]
Hello, here russian translations: 

"select" = "Выбрать(%ld)";
"permissionCamera" = "Пожалуйста, разрешите доступ к камере";
"permissionPhoto" = "Пожалуйста, разрешите доступ к фото";
"permit" = "Предоставить доступ";
"gotoSettings" = "Перейти в 「Настройки";
"ok" = "Ок";
"selectPhotosOrVideos" = "Выбрать фото или видео";
"selectPhotosOrVideosError" = "Нельзя выбрать фото и видео одновременно";
"done" = "Готово";
"maxLimitReached" = "Достигнут лимит фото";
"maxLimitReachedMessage" = "Вы можете выбрать %ld фото";

**Comment by zhangao0086** [comment]
Thanks!!!
