### ISSUE TITLE
How to get the picked image 

### ISSUE THREAD

**Issue by PABannier** [zhangao0086/DKImagePickerController#122]
Hello, 

I am a beginner in learning Swift and I don't figure out how I can get the image selected. I understand that my image is in the assets array but I don't know how to get the UIImage var. 

Here is my simple code :  `let pickerController = DKImagePickerController()
        
        pickerController.didSelectAssets = { (assets: [DKAsset]) in
            
            
        }
        
        pickerController.maxSelectableCount = 1`

Thanks

**Comment by PABannier** [comment]
It seems actually that the originalAsset contains nothing since when I place a breakout, I found that originalAsset is nil. How can I fix it ?

**Comment by thesugarrush** [comment]
![image](https://cloud.githubusercontent.com/assets/11215473/15417413/33f9bbc8-1e1b-11e6-9aa2-5783da611964.png)

Refer to to POD file: Pods/DKImagePickerController/ImageManager/DKAsset.swift code, line 122 - 142
You can get the image by using DKAsset.fetchOriginalImage(sync: bool, completedBlock: <your callback code>)
Inside that completedBlock, the UIImage will be in the variable 'image' and there is also var 'info'.

**Comment by zhangao0086** [comment]
@thesugarrush Awesome! 👍

**Comment by xuanzi23** [comment]
@thesugarrush Hi, I still no getting any idea from ur explanation. Can u more clearly to brief again??

Now I want to see what is inside the array of DKasset

so means like this?         
    if assets.count != 1{
                for i in 0..<assets.count{
                    assets.fetchOriginalImage(sync: bool, completedBlock: )
                }
            }

**Comment by zhangao0086** [comment]
@xuanzi23 
Try this:
```swift
for asset in assets {
	asset.fetchOriginalImageWithCompleteBlock({ (image, info) in
		print(image)
	})
}
```

**Comment by xuanzi23** [comment]
@zhangao0086 Hi I have try ur code and i get the result

Optional(<UIImage: 0x7fa957a285c0>, {3000, 2002})
Optional(<UIImage: 0x7fa9546288b0>, {4288, 2848})

Which means this is two different picture right?

But when I encoding it

var env64string:String! = ""

 for asset in self.assets! {
                asset.fetchOriginalImageWithCompleteBlock({ (image, info) in
                    print(image)
                    let imageData = UIImageJPEGRepresentation(image!, 0)
                    self.env64string = imageData!.base64EncodedStringWithOptions(.Encoding64CharacterLineLength)
                })

It give me same picture for that

**Comment by zhangao0086** [comment]
@xuanzi23  Do you pick two different pictures?

**Comment by xuanzi23** [comment]
@zhangao0086 i have pick two different pictures the image print out different output but the 'imageData' come out two same output.

**Comment by zhangao0086** [comment]
@xuanzi23 Do you save the imageData or env64string in a container type(array or dictionary)? Like so:
```swift
for asset in self.assets! {
	asset.fetchOriginalImageWithCompleteBlock({ (image, info) in
	print(image)
	let imageData = UIImageJPEGRepresentation(image!, 0)
	self.env64string = imageData!.base64EncodedStringWithOptions(.Encoding64CharacterLineLength)

	self.env64strings[env64string] = image // the env64strings is a dictionary.
})
```

**Comment by xuanzi23** [comment]
@zhangao0086 For my curiosity,what is the point saving into the array or dictionary?

**Comment by zhangao0086** [comment]
If the env64string is a String type, it can only save the last one.

**Comment by zhangao0086** [comment]
Feel free to re-open if your issue is not solved.

**Comment by hoangphan92** [comment]
good issues ^^^^
