### ISSUE TITLE
App is crashing after selecting the images due to [weak self] or [unowned self] in swift

### ISSUE THREAD

**Issue by gmansata6290** [zhangao0086/DKImagePickerController#123]
Hello,
         Thank you so much for your awesome and easy to use library for iOS community. But I just want to know that should i prevent the strong reference cycle by making self as weak or unowned reference or not? I read the Apple Docs, according to Apple we need to prevent the strong reference cycle created by block or closures using weak or unowned.

**Comment by zhangao0086** [comment]
Hi @gmansata6290 
Yes, we need to prevent the strong reference cycle created by block or closures using weak or unowned.
The answer explains difference between `weak` with `unowned`:
http://stackoverflow.com/a/26025176/907422

Can you describe that crash?

**Comment by bithavoc** [comment]
I also had crashes while not properly retaining the picker controller instance, specially on `didSelectAssets` when the navigation controller finished the animation and releases the `DKImagePickerController` and we still need access to the array of `DKAsset` instances.

**How I fixed it:**
```swift
    var mediaPicker:DKImagePickerController? // no `weak` here, so it retains, but... we have to release it manually
    func addPhoto() {
        let mediaPicker = DKImagePickerController()
        mediaPicker.maxSelectableCount = 6
        mediaPicker.assetType = .AllPhotos
        mediaPicker.autoDownloadWhenAssetIsInCloud = true
        mediaPicker.didSelectAssets = { [weak self] (assets: [DKAsset]) in
            print("didSelectAssets")
            print(assets)
            self?.mediaPickingFinished() // manually release controller when finished selecting photos
        }
        mediaPicker.didCancel = {
            [weak self] in
            self?.mediaPickingFinished() // manually release controller on cancel
        }
        self.mediaPicker = mediaPicker
        self.presentViewController(mediaPicker, animated: true, completion: nil)
    }
    
    func mediaPickingFinished() {
        self.mediaPicker = nil
    }
```

@zhangao0086 I don't think there is an issue with the library, you can close this issue now.

**Comment by zhangao0086** [comment]
@bithavoc Thanks!
