### ISSUE TITLE
Can't pick photo after take a picture from camera when using same DKImagePickerController

### ISSUE THREAD

**Issue by RainbowMango** [zhangao0086/DKImagePickerController#125]
hi,

I want to share same instance of DKImagePickerController for both pick photo from album and camera. But i found, after take picture by camera, i can't pick photos from album.
I tried in demo project and reproduced it.

Reproduce step with Demo:
1. update code with attachment named 'reproduce.txt'
2. Run Demo
3. Take a picker first 
4. Pick photos only
That you can see, album not shown but the camera.

[reproduce.txt](https://github.com/zhangao0086/DKImagePickerController/files/264961/reproduce.txt)

Environment: 
pod 'DKImagePickerController', '~> 3.1.3'
Xcode 7.3.1

**Comment by RainbowMango** [comment]
Seems i found the root cause and provide a pull request. Please review. Hope you can response me. 

https://github.com/zhangao0086/DKImagePickerController/pull/127

**Comment by zhangao0086** [comment]
Closing this thread...
