### ISSUE TITLE
我觉得可以增加一个delegate去定制done()等方法，另外拍照后列表照片数没有刷新

### ISSUE THREAD

**Issue by misuqian** [zhangao0086/DKImagePickerController#128]
我想在select按钮点击后直接跳转其他界面进行操作，而不是dissmissVC,我看了下done方法是固定成dissmiss了，所以觉得可以增加一个delegate去定制done。总体这是一个非常棒的图片选择器了

**Comment by misuqian** [comment]
要不去掉done中的dismissViewControllerAnimated,didSelectAssets增加一个视图本身回调参数，让用户选择点击select是否dismiss?不知道可不可行

**Comment by zhangao0086** [comment]
可行的，我打算和预览页面一起加

**Comment by zhangao0086** [comment]
现在 done 方法可以被重写
