### ISSUE TITLE
Spanish - Translation

### ISSUE THREAD

**Issue by yhondri** [zhangao0086/DKImagePickerController#131]
Hello, thanks for this great library, could you add Spanish translation?

thanks and regards. 

"select" = "Seleccciona(%ld)";

"permissionCamera" = "Por favor, permite el Acceso a la cámara";

"permissionPhoto" = "Por favor, permite el Acceso a tus fotos";

"permit" = "Permitir acceso";

"gotoSettings" = "Dirígete a 「Ajustes」para permitir el acceso";

"ok" = "OK";

"selectPhotosOrVideos" = "Selecciona Fotos o Vídeos";

"selectPhotosOrVideosError" = "No es posible seleccionar fotos y videos a la vez.";

"done" = "Hecho";

"maxLimitReached" = "Superado el número máximo de fotos";

"maxLimitReachedMessage" = "Puedes seleccionar %ld fotos";

**Comment by zhangao0086** [comment]
Thanks!!!
