### ISSUE TITLE
Slow to presentViewController

### ISSUE THREAD

**Issue by JoshBoluga** [zhangao0086/DKImagePickerController#132]
Calling `presentViewController(dkImagePickerController, animated: true, completion: nil)` takes about 5 or 6 seconds to appear. CPU usage goes up to about 100% during this period.

**Comment by zhangao0086** [comment]
@JackieQi 
How many albums and photos in your Photos?

**Comment by JoshBoluga** [comment]
I have 6407 photos (iCloud Photo Library is on) and 23 albums. The vast majority of the images are only in the 'All Photos' album. Thanks for the fast response!

**Comment by zhangao0086** [comment]
Thanks for your feedback! I'll address the issue as soon as possible :)

**Comment by JoshBoluga** [comment]
Thanks. Do you know if this issue is less present if the user has less photos?

**Comment by zhangao0086** [comment]
I have 1800+ photos. The picker takes about several milliseconds to appear.

**Comment by JoshBoluga** [comment]
Is there any update on this? With over 20,000 photos, it takes about a minute.

**Comment by zhangao0086** [comment]
I'm trying to find the cause of the problem...

**Comment by zhangao0086** [comment]
Hi @JoshBoluga Could you try the Feature/FixSlowToPresent branch? If you using CocoaPods, that will be 
```
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Feature/FixSlowToPresent'
```

**Comment by JoshBoluga** [comment]
Hi @zhangao0086 I just tried it and the view pops up immediately but it's blank. 5 or 6 seconds later, the thumbnails appear. If this is just changing when the delay is, is it still going to take a minute for a 20,000 photo library?

**Comment by zhangao0086** [comment]
Yes, now is just delay. I'll keep trying to fix it...

**Comment by JoshBoluga** [comment]
Thanks.

**Comment by zhangao0086** [comment]
Hi @JoshBoluga Please try again the Feature/FixSlowToPresent branch 😄

**Comment by JoshBoluga** [comment]
The only change I've noticed is that the camera icon appears immediately. It still takes a long time (same as before) before all the images pop in at once.

**Comment by zhangao0086** [comment]
Fixed.
