### ISSUE TITLE
Images have low quality 

### ISSUE THREAD

**Issue by Jackson0111** [zhangao0086/DKImagePickerController#133]
Hi there! I have to say I love this framework. And I noticed something that could be improved, or I did something wrong, and in that case please let me know. Below is my code: 
![screen shot 2016-05-27 at 5 06 44 am](https://cloud.githubusercontent.com/assets/13260808/15603449/d68d162a-23c8-11e6-830e-18ae1c39c5f8.png)

When the ImagePicker appears, I notice that the images have lower quality than the photo library in the phone. Is there a way to match the quality to original photos?

**Comment by zhangao0086** [comment]
Hi @Jackson0111 I also get an original photo and it match the quality to original photo:

![img_2138](https://cloud.githubusercontent.com/assets/7742344/15605650/dcb036b0-2439-11e6-9da3-58e95ac08614.PNG)

**Comment by Jackson0111** [comment]
I have a collection view of 5 cells with a 100,100 size, when I select the images and load them into the cells as background image, they become blurred. Any idea what might've happened?

**Comment by zhangao0086** [comment]
You have to fetch image with `cell.size.toPixel()`.

The following code is the implementation of `toPixel`:
```swift
public extension CGSize {
	
	public func toPixel() -> CGSize {
		let scale = UIScreen.mainScreen().scale
		return CGSize(width: self.width * scale, height: self.height * scale)
	}
}
```

**Comment by zhangao0086** [comment]
Feel free to re-open if your issue is not solved.
