### ISSUE TITLE
Build issue with DKImagePickerController

### ISSUE THREAD

**Issue by andy9819** [zhangao0086/DKImagePickerController#135]
I'm getting a build issue, when trying to build a project containing DKImagePickerController .

![image](https://cloud.githubusercontent.com/assets/12941097/15947674/1d1eca3c-2e9d-11e6-9d52-22618c41c72a.png)

**Comment by zhangao0086** [comment]
The picker supports Swift 2.2 (Xcode 7.3) and later.
