### ISSUE TITLE
Issue with Cocoapod 1.0 and DKImagePickerController.bundle

### ISSUE THREAD

**Issue by bithavoc** [zhangao0086/DKImagePickerController#136]
I'm having issues with this pod when building for distribution/release, stack trace comes to:

```	
DKImageResource.swift ​ Line 15
static NSBundle.imagePickerControllerBundle() -> NSBundle
```
This is the line where `DKImagePickerController.bundle` is loaded, however, with optimizations enabled the bundler is not included or doesn't match any bundle included in the app.

I noticed we're using `.resource` https://github.com/zhangao0086/DKImagePickerController/blob/master/DKImagePickerController.podspec#L13 where we're supposed to be using [resource_bundles](http://guides.cocoapods.org/syntax/podspec.html#resource_bundles) instead, does that have something to do with this?

Anyway the pod works in locally but not for distributing apps, any tips?

**Comment by bithavoc** [comment]
Looks like this issue has been fixed in [`1.0.1`](https://github.com/CocoaPods/CocoaPods/releases/tag/1.0.1)

**Comment by zhangao0086** [comment]
@bithavoc Let me know if you have any questions 😄

**Comment by tentenlee100** [comment]
我也有這個問題
已經是1.0.1了 降到之前可以正常使用的本版也不能用了
