### ISSUE TITLE
Turkish localization support

### ISSUE THREAD

**Issue by bsener** [zhangao0086/DKImagePickerController#137]
Turkish localization support is not available. It can be added.

**Comment by zhangao0086** [comment]
Hi @bsener  You're able to provide a pull request, I'll be happy to merge it. 😄

**Comment by bsener** [comment]
Hi @zhangao0086 when I try to send a pull request I get authentication failure. 
I am new to contribution on github. Am I doing something wrong?

**Comment by zhangao0086** [comment]
Could you post the content of the localization strings file here?

**Comment by zhangao0086** [comment]
Thanks!!!
