### ISSUE TITLE
Crash when get the `fullScreenImage` in Xcode 6.4

### ISSUE THREAD

**Issue by kshan** [zhangao0086/DKImagePickerController#14]
> invalid attempt to access <ALAssetPrivate: 0x7f8946220cd0> past the lifetime of its owning ALAssetsLibrary
> fatal error: unexpectedly found nil while unwrapping an Optional value

How to solove it?

**Comment by zhangao0086** [comment]
Hi @kshan 

The type of `fullScreenImage` is Optional, maybe you have to check it nil or not like this:

```swift
if let fullScreenImage = asset.fullScreenImage {
    // do something...
}
```

Thanks for your used :)
Closing the thread... Let me know if you have any other questions :)

**Comment by kshan** [comment]
@zhangao0086 Thanks for your prompt reply. I found the solution to this in my case. 
 
Crash happen to that I post data to server via `fullScreenImage`, but use `thumbnailImage` in collectionview after picks phtos, even if unwrapping an optional value. If i use `fullScreenImage` in collectionview too, it's normal.

**Comment by zhangao0086** [comment]
Thanks for your detail!

Could you make a test? Change these line:
```swift
public private(set) lazy var fullScreenImage: UIImage? = {
    return UIImage(CGImage: self.originalAsset?.defaultRepresentation().fullScreenImage().takeUnretainedValue())
}()
```
to that:
 
```swift
public private(set) lazy var fullScreenImage: UIImage? = {
    return UIImage(CGImage: self.originalAsset?.defaultRepresentation().fullScreenImage(). takeRetainedValue())
}()
```
I think this will resolve your issue. Let me know if that works. TIA :)

**Comment by nishantdongare** [comment]
Hello @zhangao0086  . I tried to do this . But this is also not working. I am using iOS 9.0

**Comment by zhangao0086** [comment]
Hi @nishantdongare @kshan 

The issue has been fixed. Here is my solution:

1. Define the `library` as a singleton property:`static private let library = ALAssetsLibrary()`
1. Replace `self.library.enumerateGroupsWithTypes...` with `self.dynamicType.library.enumerateGroupsWithTypes...`

This will always use the same library for all accesses to the assets. 
Let me know if you have any other questions :)
