### ISSUE TITLE
Crash when asset group doesn't know its count

### ISSUE THREAD

**Issue by wainglaister** [zhangao0086/DKImagePickerController#142]
Looks like a recent commit changed the DKGroupDataManager and added `dispatch_async(dispatch_get_global_queue(0, 0)`, which looks to mean that the asset group doesn't know its `totalCount` when it's tested just after that.

I guess this was related to performance optimisation.

It may be better to say that the first and/or the default groups are processed immediately and that other groups are scheduled. For any scheduled groups, rather than processing them immediately, or trying to as the code currently does, instead tie in with the change observer so that when the group details are known the listing and UI can be updated.

**Comment by zhangao0086** [comment]
@wainglaister Thanks for point out my mistake! I‘ll temporarily remove `dispatch_async`, then try the other solution 😄

**Comment by zhangao0086** [comment]
Please try the `3.3.1` version.
