### ISSUE TITLE
how can add prompt(subtitle) to navigationbar???  

### ISSUE THREAD

**Issue by shindonghyeok** [zhangao0086/DKImagePickerController#145]
i'd like to add a prompt to navigationbar. actually i added prompt to navigationbar using "self.navigationItem.prompt = "prompt text" in viewDidLoad func.. but i  don't know where i can add it... 
please i really need your help....

**Comment by zhangao0086** [comment]
You should use a custom `DKImagePickerControllerDefaultUIDelegate` like so:
```swift
@objc
public class CustomDelegate: DKImagePickerControllerDefaultUIDelegate {
	
	override public func prepareLayout(imagePickerController: DKImagePickerController, vc: UIViewController) {
		super.prepareLayout(imagePickerController, vc: vc)
		
		vc.navigationItem.prompt = "prompt text"
	}
	
}
```
then 
```swift
pickerController.UIDelegate = CustomDelegate()
```

**Comment by shindonghyeok** [comment]
thanks for your appreciate!! but.. i don' know where i should write your code...  i have to make a new swift file?? or i should your code in DKImagePickerController.swift?? sorry... i am a begginer, so i don't know about swift yet..;;

**Comment by zhangao0086** [comment]
Are you using Objective-C?

**Comment by shindonghyeok** [comment]
no i am using swift. i add your github file to my project using cocoa pod.

**Comment by zhangao0086** [comment]
You can make a new swift file, then set the pickerController's UIDelegate before `presentViewController`.

**Comment by shindonghyeok** [comment]
I made a new swift file and wrote the code, but it had errors....

![2016-06-21 2 37 57](https://cloud.githubusercontent.com/assets/20056570/16219010/e1120bd8-37bd-11e6-8be6-32a39717671b.png)

what's the problem?? are there something that i should do??

**Comment by shindonghyeok** [comment]
oh i got solved my problem!! i had wrote prompt code in viewWillAppear function of DkImagePickerController.swift!! 
thank you for your help!

**Comment by zhangao0086** [comment]
Closing...
