### ISSUE TITLE
how to know type of the picked file??? 

### ISSUE THREAD

**Issue by shindonghyeok** [zhangao0086/DKImagePickerController#147]
how to know type of t picked files that which one is image file or video file?? the reason that why i have to know type is that i'd like to call 'writeImageToFile' or writeAVToFile func as picked files.. so how can i  seperate from picked files???

**Comment by zhangao0086** [comment]
The DKAsset has a property named `isVideo`.

**Comment by shindonghyeok** [comment]
thank you!! closing.....

**Comment by nharbo** [comment]
This doesn't seem to work anymore - what's the new approach?

**Comment by zhangao0086** [comment]
@nharbo  Try this:
```swift
switch asset.type {
case .photo:
    print("photo")
case .video:
    print("video")
}
```

**Comment by nharbo** [comment]
I fixed it with asset.type == .video :-) thanks!
