### ISSUE TITLE
Swift 2.0 compatibility

### ISSUE THREAD

**Issue by Urkman** [zhangao0086/DKImagePickerController#15]
Your Swift2.0 branch is not working for me, when using it as a pod :(

**Comment by zhangao0086** [comment]
Hi @Urkman 

It's my fault for has not been pushed all commits to GitHub. Now fixed.
Thank you for being here :)

**Comment by zhangao0086** [comment]
And you should have the following code in your Podfile:

```ruby
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Swift2.0'
use_frameworks!
```

**Comment by Urkman** [comment]
Thanks :)

**Comment by Urkman** [comment]
Now I had time to take a look... And I still get errors. 
All in DKCamera.swift...

**Comment by zhangao0086** [comment]
@Urkman 
Try again... 

Unfortunately I'm unable to find out a solution to suppress deprecated warning in swift...

**Comment by Urkman** [comment]
Seems to work now :)

**Comment by zhangao0086** [comment]
@Urkman 
Let me know if you have any questions :)
