### ISSUE TITLE
Core Data: error

### ISSUE THREAD

**Issue by rvilches** [zhangao0086/DKImagePickerController#150]
Hi guys first of all thanks for this amazing  SDK. I writing because from the sudden I encountered this error when I tried to show the DKImagePickerController to select images :

"Core Data: error: -executeRequest: encountered exception = CoreData: SQLite: error: Can't bind intarray. SQLite error code: 21 with userInfo = {
    NSSQLiteErrorDomain = 21;
}"

and some of my folders appear in blank. Do you guys have a hint or something I have been trying to fix it  with no success.

**Comment by rvilches** [comment]
I notice that if i change the "Optimization Level" to None[-O0] on debug it doesnt happens but when I use the release version, it fails.

**Comment by zhangao0086** [comment]
Are you using CoreData?

**Comment by rvilches** [comment]
I do. But on the moment that I am opening the DKImageViewController I am not using it for anything.

**Comment by zhangao0086** [comment]
Hi @rvilches I cannot reproduce it. Could you give me a demo project?

**Comment by rvilches** [comment]
@zhangao0086  I read this http://www.openradar.me/21247340 and as it suggest I think the problem is with albums with large data amount. 
I changed the assetGroupTypes to [.SmartAlbumFavorites] and everything ran smooth, as soon as I add another album with big amount of data like = [.SmartAlbumUserLibrary,.SmartAlbumFavorites,.SmartAlbumVideos,.AlbumRegular] , the biggest albums appears empty.
 It shows the quantity of objects in the albums and I can even select them but I don't see them .I attached some images here:
![13523804_10153955988969652_1860621635_o](https://cloud.githubusercontent.com/assets/3842797/16395178/a89863ec-3c86-11e6-8bbb-a6f7cae19898.jpg)
![13517742_10153955989099652_896916007_o](https://cloud.githubusercontent.com/assets/3842797/16395179/a8a83ab0-3c86-11e6-9d96-3a2c7920db8c.jpg)

**Comment by zhangao0086** [comment]
It's so strange.. I have 6000+ photos, but I cannot reproduce it ... :(

**Comment by rvilches** [comment]
I found it!. It was my fault. I was "cleaning" the temporary directory on the "appWillResignActive" and this caused this behavior on the app.  I feel so sorry for bother you :(. Once again thanks for such an excellent project like this.

**Comment by rvilches** [comment]
I found it!. It was my fault. I was "cleaning" the temporary directory on the "appWillResignActive" and this caused this behavior on the app. I feel so sorry for bother you :(. Once again thanks for such an excellent project like this.

**Comment by zhangao0086** [comment]
@rvilches 😄
