### ISSUE TITLE
Remove asset from another controller

### ISSUE THREAD

**Issue by ricardodnb** [zhangao0086/DKImagePickerController#153]
I think there is the possibility of this feature is not yet implemented. I was trying to remove an asset from another controller and automatically update the picker collection view. 
Added a public function on DKImagePickerController called removeAsset that solves this problem.

`    public func removeAsset(index: Int){
        let asset = self.selectedAssets[index]
        self.unselectedImage(asset)
        if let rootVC = self.viewControllers.first as? DKAssetGroupDetailVC {
            rootVC.collectionView?.reloadData()
        }
    }
`

**Comment by zhangao0086** [comment]
👍
