### ISSUE TITLE
Suggestion:  Add a zoom image on longpress. (like photos app)

### ISSUE THREAD

**Issue by FreudGit** [zhangao0086/DKImagePickerController#155]
Add a zoom image on longpress. (like photos app)

So user will be able to see image in fullscreen

**Comment by zhangao0086** [comment]
Thanks! I'll add it in the next version.

**Comment by mirzadelic** [comment]
I have suggestion, to add download progress bar when images are downloading from icloud, and to not close popup until it's done.

**Comment by ferico55** [comment]
this feature has been added, please update your pod file
please refer to this issue #134 for download progress from iCloud

**Comment by RedBluePeas** [comment]
> 已添加此功能，请更新您的Pod文件，
> 请参阅此问题[＃134，](https://github.com/zhangao0086/DKImagePickerController/issues/134)了解从iCloud下载的进度

你好，我使用的是最新版本，可是获取iCloud照片时没有显示下载进度，需要配置什么吗
