### ISSUE TITLE
DKImagePickerController for IOS 10 

### ISSUE THREAD

**Issue by Danielthenew** [zhangao0086/DKImagePickerController#156]
On Xcode 8 and IOS 10 the DKImagePickerController have an error.

**Comment by zhangao0086** [comment]
The DKImagePickerController does not support Swift3 beta.

**Comment by Danielthenew** [comment]
ah oke so when it´s come the real Swift3 version you implement it that it works with Swift3 ? 
So it must be work with Swift 2.3 .

**Comment by zhangao0086** [comment]
Yes.

**Comment by Danielthenew** [comment]
Oke Thanks

**Comment by Danny182** [comment]
I get the error "no such module DKImagePickerController"
Will it get updated soon? or It will get updated when iOS 10 comes out (not beta)?

**Comment by zhangao0086** [comment]
Use the `Feature/Swift3` branch if you are using Swift3.
