### ISSUE TITLE
How to get transparent background for DKImagePickerController?

### ISSUE THREAD

**Issue by nkmadala** [zhangao0086/DKImagePickerController#157]
Hi, I have a requirement where I will present the picker controller over the top of a view controller which shows the camera stream. I want to  make the DKImagePickerController view transparent so that the camera stream is visible in the background. I have tried the following with no luck.

 ```
pickerController.modalPresentationStyle = .OverCurrentContext
        self.presentViewController(pickerController, animated: true) {
            self.pickerController.view.backgroundColor = UIColor.clearColor()
            self.pickerController.view.opaque = false
        }
```

Can you please let me know on how to make the picker with transparent background?

**Comment by zhangao0086** [comment]
In the latest version, you can try this:
```swift
pickerController.modalPresentationStyle = .OverCurrentContext
```

then in your UIDelegate:
```swift
public func imagePickerControllerCollectionViewBackgroundColor() -> UIColor {
    return UIColor.clearColor()
}
```

**Comment by zhangao0086** [comment]
Feel free to re-open if your issue is not solved.
