### ISSUE TITLE
Unable to save the selected assets array

### ISSUE THREAD

**Issue by alvinreuben** [zhangao0086/DKImagePickerController#16]
I have implemented this project via cocoa pods. I wanted to save the selected images (path) to an array and retrieve and upload in another view controller.

Failed to work out. Appreciate your help.

**Comment by zhangao0086** [comment]
Hi @alvinreuben 

The asset url is a temp url, so you have to save the selected images to Document directory and upload later.

**Comment by zhangao0086** [comment]
Closing the thread...
