### ISSUE TITLE
issue on video selection

### ISSUE THREAD

**Issue by realanalysis** [zhangao0086/DKImagePickerController#160]
hi, on video selection, you should display max videos limit reached instead of max photos limit reached

**Comment by zhangao0086** [comment]
I'll change
```swift
"maxLimitReachedMessage" = "You can select %ld photos";
```
to
```swift
"maxLimitReachedMessage" = "You can select %ld items";
```

What do you think?

**Comment by realanalysis** [comment]
it will be great, if you allow user to add their own message on the alert view. What do you think?

**Comment by realanalysis** [comment]
here is another problem, if user select one item, will you change items to item? 如果可以让dev自己填写自己想要的alert view message会比较好

**Comment by zhangao0086** [comment]
Sounds good to me. 我会让用户去处理这种行为.

**Comment by zhangao0086** [comment]
Now users can customize the process of `didReachMaxLimit` via `DKImagePickerControllerDefaultUIDelegate`:

The following code is the default implementation:
```swift
public func imagePickerControllerDidReachMaxLimit(imagePickerController: DKImagePickerController) {
	UIAlertView(title: DKImageLocalizedStringWithKey("maxLimitReached"),
	            message: String(format: DKImageLocalizedStringWithKey("maxLimitReachedMessage"), imagePickerController.maxSelectableCount),
	            delegate: nil,
	            cancelButtonTitle: DKImageLocalizedStringWithKey("ok"))
		.show()
}
```
