### ISSUE TITLE
How convert ASAsset to NSData?

### ISSUE THREAD

**Issue by zlatibor** [zhangao0086/DKImagePickerController#161]
I'm using DKImagePickerController and I have one problem.

I have variable
`var videoFile: AVAsset!
`
and it contains (loaded with) MP4 video, already.

I have need to convert that videoFile to NSData using Swift. How to do this conversion?

**Comment by zhangao0086** [comment]
You can use
```swift
public func writeAVToFile(path: String, presetName: String, completeBlock: (success: Bool) -> Void)
```
