### ISSUE TITLE
DKImage how do i upload it to a url?? 

### ISSUE THREAD

**Issue by biotechpro7** [zhangao0086/DKImagePickerController#162]
i couldnt find a way to upload the picture file to a url. please help

**Comment by zhangao0086** [comment]
You have to write the picture to Documents directory by using:
```swift
public func writeImageToFile(path: String, completeBlock: (success: Bool) -> Void)
```
or
```swift
public func writeAVToFile(path: String, presetName: String, completeBlock: (success: Bool) -> Void)
```

then upload it to your server.

**Comment by biotechpro7** [comment]
sorry but i am a bit confuse what i am suppose to put in the completeBlock

here is what i have done

let path = “http://localhost/swift/upload.php”
 
// when i change the completeBlock to true i got an error. did i do something wrong or do i need to put something else inside {}

public func writeImageToFile(path: path!, completeBlock: true){
	
}

**Comment by zhangao0086** [comment]
Hi @biotechpro7 

The path must to be the local path. e.g. `Documents` or `tmp`.
You should write the selected picture to the `Documents` or `tmp`, then uploading it to your server via `AFNetworking` or other:
```swift
let writePath = (NSTemporaryDirectory() as NSString).stringByAppendingPathComponent("1.png")

assets.first?.writeImageToFile(writePath, completeBlock: { (success) in
    if success {
        // uploading to your server
    } else {
        // ...
    }
})
```

See also:[Creating an Upload Task](https://github.com/AFNetworking/AFNetworking#creating-an-upload-task)
