### ISSUE TITLE
fatal error: unexpectedly found nil while unwrapping an Optional value

### ISSUE THREAD

**Issue by mac8878** [zhangao0086/DKImagePickerController#163]
i'm not able to figure cause of this error but its pointing to this       `if let firstSelectedAsset = DKImagePickerController.sharedInstance().selectedAssets.first` and this 		`return DKImagePickerController.imagePickerController!;` anyone knows  why its happening ??

**Comment by zhangao0086** [comment]
Please update to the latest version `3.3.2`.
