### ISSUE TITLE
Getting (read) file name and extension in Swift?

### ISSUE THREAD

**Issue by zlatibor** [zhangao0086/DKImagePickerController#165]
Hi,

How do I get file name and file extension of selected image or video using DKIimagePickerConstroller?

For example, if user selected "video1.mp4" file from his library in the iPhone, how get "video1" and "mp4", or just full name of the file "video1.mp4" from that selected file, using Swift?

**Comment by zlatibor** [comment]
I solved it:

`let nameWithExt = ((info!["PHImageFileSandboxExtensionTokenKey"]!) as! NSString).lastPathComponent`

**Comment by zhangao0086** [comment]
I'm glad to hear your issue has been solved!
