### ISSUE TITLE
Exif data

### ISSUE THREAD

**Issue by zlatibor** [zhangao0086/DKImagePickerController#166]
How get Exif data from image or video?

**Comment by zhangao0086** [comment]
If you need to get the metadata of a DKAsset, just access the `originalAsset` like so:
```swift
if let originalAsset = asset.originalAsset {
	originalAsset.mediaType
	originalAsset.mediaSubtypes
	originalAsset.creationDate
	originalAsset.modificationDate
	// ...
}
```

See also: [Reading Asset Metadata](https://developer.apple.com/library/ios/documentation/Photos/Reference/PHAsset_Class/#//apple_ref/doc/uid/TP40014383-CH1-SW3)
