### ISSUE TITLE
writeAVToFile doesn't work

### ISSUE THREAD

**Issue by tacq** [zhangao0086/DKImagePickerController#168]
I call writeAVToFile, but it always print false. I wonder know why. Thanks
let uploadVideoName = "video-test.mov"
let documents = NSSearchPathForDirectoriesInDomains(.DocumentDirectory, .UserDomainMask, true)[0] as! String
let writePath = documents.stringByAppendingString("/video-test.mov")
asset.writeAVToFile(writePath, presetName: "uploadVideoName", completeBlock: { (success) in                          print(success)
 })

**Comment by tacq** [comment]
presetName should be [AVAssetExportPresetLowQuality,AVAssetExportPresetMediumQuality,
AVAssetExportPresetHighestQuality,AVAssetExportPreset640x480,AVAssetExportPreset960x540,AVAssetExportPreset1280x720,AVAssetExportPreset1920x1080]

**Comment by zhangao0086** [comment]
🍺
