### ISSUE TITLE
Exporting imagefile to a Url. 

### ISSUE THREAD

**Issue by biotechpro7** [zhangao0086/DKImagePickerController#170]
hi guys, sorry i am a noob but please i really need to make this work. i tried to export the selected image/video from the DKimagepickercontroller. and this is what i have tried. (i change the path: String to Nsurl because i want to export it to a url) i put the code below outside func showimagepickerwithasseststype

    let apath = "../desktop"
    let url = NSURL(string: "http://localhost/swiftios/upload.php")
    
   // i got this code from the instruction on this github
    func writeImageToFile(path: NSURL, completeBlock: (success: Bool) -> Void){
        
    }

then i put that code inside the func showimagepickerwithassesttype

		pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
			
			self.assets = assets
			self.previewView?.reloadData()

            // i recall the function above in here like this 
            self.writeImageToFile(self.url!, completeBlock:  { (success) in
                if success {
                    self.UploadRequest()
                    print("file is uploaded")
                } else {
                    print("error")
                }
            })

but one i select images and click on SELECT nothing is happening. it didnt even print an error.

did i not write this correctly?? or am i putting the code in the wrong place??

**Comment by zhangao0086** [comment]
You have to export the selected image/video to the Documents directory, then uploading it to your server.
