### ISSUE TITLE
Sort Selected Images by selected Order Number?

### ISSUE THREAD

**Issue by Sun3** [zhangao0086/DKImagePickerController#175]
Is there a way to get the Selected Images returned by user Selected Order Number. 

For example. User pick's images 1,2,3 and I would like the order returned in the same order so I can save them in an array in the same order as picked.

Thanks and great control, love it.

**Comment by zhangao0086** [comment]
Hi @Sun3 The `assets` array will be returned in the same order as the user picked.

**Comment by zhangao0086** [comment]
Feel free to re-open if your issue is not solved.

**Comment by Sun3** [comment]
I was just about to update the post and saw your comment. It's working perfectly it was something else causing the order to be changed on my side.

Thank you.
