### ISSUE TITLE
How do I get path of Image?

### ISSUE THREAD

**Issue by Riaxter** [zhangao0086/DKImagePickerController#176]
Using callback didSelectAssets in "DKImagePickerController", I get UIImage successfully. But I don't know how to get the selected image path. In DKAsset class there is no information about path or URI. Could you let me know how to get path of image?

**Comment by rdadkins** [comment]
I had this same issue. From what I researched and found out (the hard way - wasted time) is that you should use the localIdentifier (string identifier to identify the asset) found in the originalAsset (PHAsset) of a DKAsset. Here is an example:
```
override func didSelectAssets(images: [DKAsset]) {
  if let identifier = images[0].originalAsset?.localIdentifier { // DKAsset -> PHAsset identifier (string)
    let phAsset = PHAsset.fetchAssetsWithLocalIdentifiers([identifier], options: .None).firstObject as? PHAsset // localIdentifier -> PHAsset
  }
}
```

I wrote this on the fly so some of the swift may produce errors. The thing to take away is to use `PHAsset.localIdentifier` and fetch PHAssets via `PHAsset.fetchAssetsWithLocalIdentifiers`

**Comment by zhangao0086** [comment]
Why do you want to get the path of image?

**Comment by Riaxter** [comment]
When I want to make a simple board application, it needs to select image from storage and upload it as a file. I used UIImagePNGRepresentation with UIImage that selected, but it doesn't work. I don't know the reason exactly. So I want to try to get file from path and upload it.

**Comment by zhangao0086** [comment]
You can save the selected image to `Documents`, then uploading it to your server.
```swift
public extension DKAsset {
	/**
		Writes the image in the receiver to the file specified by a given path.
	*/
	public func writeImageToFile(path: String, completeBlock: (success: Bool) -> Void) 
	
	/**
		Writes the AV in the receiver to the file specified by a given path.
	
		- parameter presetName:    An NSString specifying the name of the preset template for the export. See AVAssetExportPresetXXX.
	*/
	public func writeAVToFile(path: String, presetName: String, completeBlock: (success: Bool) -> Void)
}
```

**Comment by Riaxter** [comment]
Thank you for giving me a solution and it is possible solution. But I think it is unnecessary task. Is there any way to get path of original file?

**Comment by zhangao0086** [comment]
I think the path of original file is unuseful. You cannot read any files or directories outside of your application directory.

**Comment by Riaxter** [comment]
Oh... I didn't know that. Thanks! I really appreciate it.

**Comment by aneeskodappana** [comment]
```
public extension DKAsset {
    /**
        Writes the image in the receiver to the file specified by a given path.
    */
    public func writeImageToFile(path: String, completeBlock: (success: Bool) -> Void) 

    /**
        Writes the AV in the receiver to the file specified by a given path.

        - parameter presetName:    An NSString specifying the name of the preset template for the export. See AVAssetExportPresetXXX.
    */
    public func writeAVToFile(path: String, presetName: String, completeBlock: (success: Bool) -> Void)
}
```
Is this writeImageToFile() method still exist on the latest version ?

**Comment by yu-t** [comment]
@zhangao0086 Can you please answer if there is any alternative to writeImageToFile() method on the latest version ?
