### ISSUE TITLE
singleSelect doesn't work as it should

### ISSUE THREAD

**Issue by mirzadelic** [zhangao0086/DKImagePickerController#177]
Hi,
this is my setup:
```
pickerController.assetType = .AllPhotos
pickerController.singleSelect = true
pickerController.didSelectAssets = { (assets: [DKAsset]) in
    print(assets)
}
```

now when picker shows up, i select image, and it automatically hides picker, then when i open same picker, is shows me that selected image, and when i click on another image, is doesn't deselect first one, it just behave like multiple selection, and prints me 2 assets:
```
<DKImagePickerController.DKAsset: 0x7ffde373aa40>, <DKImagePickerController.DKAsset: 0x7ffde378cb90>]
```
Same is happening when i do this again, picker shows up, and i see 2 images selected, and i select on another image, it prints me 3 assets.

is this bug or?

**Comment by zhangao0086** [comment]
Sorry for the late reply...
Fixed in the latest version `3.3.4`.
