### ISSUE TITLE
Get images ordered by date

### ISSUE THREAD

**Issue by LucidityDesign** [zhangao0086/DKImagePickerController#18]
Is it possible to get the images ordered by date instead of ordered by selection order?

**Comment by zhangao0086** [comment]
Hi @LucidityDesign 
Do you want to get the create date of the image?

**Comment by LucidityDesign** [comment]
I would like to have the image selection count (white number on blue frame) ordered by date and the SelectedAssets ordered by date, too, so I don't have to order the array.

**Comment by zhangao0086** [comment]
The current order is ordered by selection order, not date. If you want to get the create date of the selected images, I think I'll add it.

**Comment by syky27** [comment]
Hi @zhangao0086 thanks for creating this awesome pod, when do you plan to add this?

**Comment by zhangao0086** [comment]
Hi @LucidityDesign @syky27 

I have added a convenient way to get the create date of selected asset in [2.3.7](https://github.com/zhangao0086/DKImagePickerController/commit/db80175e894bb9a626295af9194ebb736016252b) :)

You can use the `createDate` property like this:

```swift
let asset = assets.first
print(asset?.createDate)
```

**Comment by syky27** [comment]
Thanks!
