### ISSUE TITLE
Photo thumbnails white on iPhone app run on iPad

### ISSUE THREAD

**Issue by leondobnik** [zhangao0086/DKImagePickerController#181]
Hi!

When an iPhone app in run on iPad (in my case iPad AIR) in so called compatibility mode (iPhone4 size) thumbnails for images are present (can be selected - selection is visible), but entire screen is white. It is possible to reproduce this issue on real device and on simulator. If example code is needed, please let me know.

**Comment by MuqThe2nd** [comment]
https://openradar.appspot.com/25813088
https://forums.developer.apple.com/thread/43400
