### ISSUE TITLE
How do I change the background of picker to black color?

### ISSUE THREAD

**Issue by nkmadala** [zhangao0086/DKImagePickerController#183]
How do I change the background of picker to black color? And how can I reduce the size of the camera icon on videos to match as shown in photos app?

**Comment by zhangao0086** [comment]
> How do I change the background of picker to black color? 

The `DKImagePickerController` has a property named `backgroundCollectionViewColor`.

> And how can I reduce the size of the camera icon on videos to match as shown in photos app?

Subclass of `DKImagePickerControllerUIDelegate`, then overrides the method:
```
func imagePickerControllerCameraImage() -> UIImage
```

**Comment by nkmadala** [comment]
Thanks for the response. However, I'm showing only videos and the icon I want change is "videoCameraIcon" for which I don't find any func to override. Can you please consider this for next release?

**Comment by yu-t** [comment]
@zhangao0086 Now there's no property `backgroundCollectionViewColor `. How is it possible to change now?
