### ISSUE TITLE
闭包返回选中图片用起来极其不便

### ISSUE THREAD

**Issue by huangboju** [zhangao0086/DKImagePickerController#185]
希望改为代理返回，有利于代码逻辑处理

**Comment by zhangao0086** [comment]
为什么你觉得 Block 不利于代码逻辑处理？

**Comment by huangboju** [comment]
我有一个多选图片的需求，显示时用小图，上传时用原图。但是我又只想循环一次，所以要在返回asset哪里去遍历asset。感觉会混上很多DKImagePickerController的代码。感觉成一坨了。

**Comment by zhangao0086** [comment]
我觉得这种场景下，Delegate 并不具备优势，甚至你还会更麻烦，因为你得自己维护一个 Asset 标识符的字典。
你的场景，`Photos` 是建议在两个入口 fetch 两次的，你可以自己用一个工具方法把 DKImagePickerController 的调用封装起来.
