### ISSUE TITLE
does DKImagePickerController support swift 3 xcode 8 ?

### ISSUE THREAD

**Issue by rohimdev** [zhangao0086/DKImagePickerController#196]
does DKImagePickerController support swift 3 xcode 8? 
DKImagePickerController was working properly when I work on project in swift 2 xcode 7, but after I update the xcode to 8, it has so many error.

**Comment by softpeterkk** [comment]
me too, have the same problem after upgrade project to swift 3.

**Comment by rdadkins** [comment]
As of now, no. You can fix this for now by updating your Podfile to `pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Feature/Swift3'`

**Comment by softpeterkk** [comment]
yes thank, but I didn't like to use pod, I like install manually. when you will release new version that support swift 3.

**Comment by zhangao0086** [comment]
I released 3.4.0. You can use the `3.4.0` tag or `master` branch.

**Comment by junaidjp** [comment]
As of now, no. You can fix this for now by updating your Podfile to pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Feature/Swift3'

IT does not work 


[!] Error installing DKImagePickerController
[!] /usr/bin/git clone https://github.com/zhangao0086/DKImagePickerController.git /var/folders/cs/902zv7953bb25fcmkbsfwxhc0000gn/T/d20170224-1549-1xqttgq --template= --single-branch --depth 1 --branch Feature/Swift3

Cloning into '/var/folders/cs/902zv7953bb25fcmkbsfwxhc0000gn/T/d20170224-1549-1xqttgq'...
warning: Could not find remote branch Feature/Swift3 to clone.
fatal: Remote branch Feature/Swift3 not found in upstream origin

**Comment by zhangao0086** [comment]
@junaidjp 
Use the `master` branch.
```swift
pod 'DKImagePickerController'
```

**Comment by junaidjp** [comment]
thank you. 
Does the above POD support Swift 3 ?

**Comment by zhangao0086** [comment]
Yes, the `master` and `develop` supports swift3.
