### ISSUE TITLE
EXif data needed!

### ISSUE THREAD

**Issue by hadwanihardik** [zhangao0086/DKImagePickerController#197]
How i can have exif data with  the image?
Or
How can i get image without removing exifdata?

My need is to send image to  server with  exifdata

**Comment by zhangao0086** [comment]
If you need to get the metadata of a DKAsset, just access the `originalAsset` like so:
```swift
if let originalAsset = asset.originalAsset {
	originalAsset.mediaType
	originalAsset.mediaSubtypes
	originalAsset.creationDate
	originalAsset.modificationDate
	// ...
}
```

See also: [Reading Asset Metadata](https://developer.apple.com/library/ios/documentation/Photos/Reference/PHAsset_Class/#//apple_ref/doc/uid/TP40014383-CH1-SW3)
