### ISSUE TITLE
numberColor and checkedBackgroundImgColor are gone from Swift 3 & Xcode 8

### ISSUE THREAD

**Issue by Sun3** [zhangao0086/DKImagePickerController#202]
numberColor and checkedBackgroundImgColor properties are now gone with Swift 3 and Xcode 8. Any way to set them?

Thanks

**Comment by zhangao0086** [comment]
Subclass of `DKImagePickerControllerDefaultUIDelegate`, then override these methods:
```swift
class CustomUIDelegate2: DKImagePickerControllerDefaultUIDelegate {
    
    override func imagePickerControllerCheckedNumberColor() -> UIColor {
        return UIColor.red
    }
}

...
pickerController.UIDelegate = CustomUIDelegate()
```

**Comment by Sun3** [comment]
Thanks. Do you think we will bring those properties to be dynamic in the future?

**Comment by zhangao0086** [comment]
Are you saying that a different cell with different colors?

**Comment by Sun3** [comment]
In my case the user will have multiple books that they will add photo's to. Each book the user can choose it's own color. I was trying to dynamically at runtime use the color the the user has chosen for each book. If book is blue then the selected cell will be blue If user choose green the cell will be green.
