### ISSUE TITLE
Save selection to NSUserDefaults

### ISSUE THREAD

**Issue by timfi** [zhangao0086/DKImagePickerController#207]
I'm trying to save the didSelectAssets to NSUserDefaults, but this doesn't seem possible. Do you have a way to save the selection so I can use it after the app has restarted?

**Comment by zhangao0086** [comment]
Hi @timfi 
You can store the `localIdentifier` of `originalAsset: PHAsset` to `NSUserDefaults`, then create `DKAsset` with `public init(originalAsset: PHAsset)`.

You should get a `PHAsset` using the following API.
```swift
// PHAsset.h 

open class func fetchAssets(withLocalIdentifiers identifiers: [String], options: PHFetchOptions?) -> PHFetchResult<PHAsset>
```

**Comment by timfi** [comment]
Thank you, this works :)
