### ISSUE TITLE
Not compatible with Swift 3.0

### ISSUE THREAD

**Issue by nileshpol18** [zhangao0086/DKImagePickerController#208]

**Comment by zhangao0086** [comment]
Try this in your `pod`:
```shell
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'master'
```

**Comment by nileshpol18** [comment]
This did work. Thanks. 👍 

You should mention this on installation process. I installed as just **pod 'DKImagePickerController'** and it gave my app a cancer! :|
