### ISSUE TITLE
Swift 2.3 - Incompatible versions of Swift

### ISSUE THREAD

**Issue by erickva** [zhangao0086/DKImagePickerController#209]
I install version 3.3.4 to use with Swift 2.3 and Xcode8.
But I am getting the following error after converting to 2.3 and compiling:
```
error: The following binaries use incompatible versions of Swift:
Frameworks/DKImagePickerController.framework/DKImagePickerController
```

**Comment by zhangao0086** [comment]
The `3.3.4` uses Swift 2.2 not 2.3 and not compatible with Xcode 8. Instead, you can try this in your `Podfile`:
```bash
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'master'
```

The `master` branch is compatible with Xcode 8.

**Comment by erickva** [comment]
Thank you, is there a way to use it with a project using Swift 2.3?

**Comment by zhangao0086** [comment]
It does not support Swift 2.3 :(
You're able to provide a pull request(from 3.3.4), I'll be happy to merge it :)
