### ISSUE TITLE
module file was created by an older version of the compiler; rebuild 'DKImagePickerController' and try again

### ISSUE THREAD

**Issue by XLW-Jeroen** [zhangao0086/DKImagePickerController#210]
Hi there. First of all I'd like to thank you for all your hard work into making this awesome image picker controller!

Now on to the issue. I have an Objective-C project in which I've been using this controller for quite a while now. Everything worked fine, until I updated to Xcode8. After solving many errors and problems I've gotten stuck on this issue. I used cocoapods before, but when I try using it now I keep getting version 3.3.4, while it is said I should use 3.4.0. If I try to get version 3.4.0 specifically, cocoapods says it's not there. So I have added the files from the 3.4.0 branch to my project instead. However, now I keep getting this error: `module file was created by an older version of the compiler; rebuild 'DKImagePickerController' and try again`. It seems there is nothing I can do about this. Do you have any idea how to solve this issue?

Many thanks in advance, and again, thank you for your hard work! It is very much appreciated.

**Comment by XLW-Jeroen** [comment]
Update: I found a way to get version 3.4.0 through cocoapods in the closed issues.
`pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Feature/MigratingToSwift3'`

Unfortunately, this brings me back to this issue:
`“Use Legacy Swift Language Version” (SWIFT_VERSION) is required to be configured correctly for targets which use Swift. Use the [Edit > Convert > To Current Swift Syntax…] menu to choose a Swift version or use the Build Settings editor to configure the build setting directly.`

Seeing as how Xcode convert to current swift syntax does nothing but create more and more errors, this still didn't solve my problem.

**Comment by YanisSalos** [comment]
same problem i have when i choose to use good library i hope the owner fix this problem or give us a solve

**Comment by faizandedia** [comment]
Here is the quick fix

set property "Use Legcay swift Language version" to "No" under pods framework settings for DKImagePickerController

**Comment by zhangao0086** [comment]
Hi all, there is a possible solution:

#### Step 1
Try this in your `Podfile`:
```swift
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'master'
```

#### Step 2
As @faizandedia said.
> set property "Use Legcay swift Language version" to "No" under pods framework settings for DKImagePickerController

![79607ac3-e254-4651-8ea5-c66cc90d7810](https://cloud.githubusercontent.com/assets/7742344/18735643/04d993a0-80b2-11e6-8b8d-570c85bb4a96.png)

**Comment by XLW-Jeroen** [comment]
Thanks a lot @faizandedia & @zhangao0086! This solved my problem. I am now able to build my project again. I have been looking hours for a solution, I don't think I would've ever come up with this solution. So thank you for solving a problem which was driving me nuts. Much appreciated!
