### ISSUE TITLE
cocoapods 最新版本 不是3.4.0的呀..还是3.3.4

### ISSUE THREAD

**Issue by SugarTzzz** [zhangao0086/DKImagePickerController#212]

**Comment by zhangao0086** [comment]
你可以看看这里：https://github.com/zhangao0086/DKImagePickerController/issues/201
`Podfile` 里可以临时这样写：
```bash
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'master'
```

**Comment by SugarTzzz** [comment]
好的我去试试 谢谢

**Comment by SugarTzzz** [comment]
成功啦  谢谢┗|｀O′|┛ 嗷~~.  请问下啥时候能 更新呀..    
可否用 导入到carthage   上面呀

**Comment by zhangao0086** [comment]
等 `Cocoapods` 的 `pod lib lint` 和 `pod trunk push` 命令不报错的时候就可以更新了。
Carthage 之前跑过一次，后面没跑过了，我看看需不需要更新。

**Comment by SugarTzzz** [comment]
好的 O(∩_∩)O谢谢了  挺好用的  ..找了一个上午类似的框架了
