### ISSUE TITLE
Please add french language

### ISSUE THREAD

**Issue by R0bb12** [zhangao0086/DKImagePickerController#213]
"select" = "Sélectionnez(%ld)";

"permissionCamera" = "Merci d'autorisez l'accès à l'appareil photo";

"permissionPhoto" = "Merci d'autorisez l'accès aux photos";

"permit" = "Autorisez l'accès";

"gotoSettings" = "Allez dans  「Réglages」 pour donner l'accès";

"ok" = "OK";

"selectPhotosOrVideos" = "Sélectionnez des Photos ou des Vidéos";

"selectPhotosOrVideosError" = "Il n'est pas possible de sélectionner des photos et des vidéos en même temps.";

"done" = "Terminé";

"maxLimitReached" = "Limite de photos atteinte";

"maxLimitReachedMessage" = "Vous pouvez sélectionner %ld éléments";

**Comment by zhangao0086** [comment]
Thanks!!!
