### ISSUE TITLE
Not using Podfile on xcode 8 and switf 3

### ISSUE THREAD

**Issue by lexuanquynh** [zhangao0086/DKImagePickerController#216]
My Podfile:
platform :ios, '8.0'
use_frameworks!

target 'RepeatAgain' do
pod 'DKImagePickerController'
end
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
  end

But when I try open RepeatAgain.xcworkspace, I get error:
![1](https://cloud.githubusercontent.com/assets/17588791/18868948/3f69d964-84d4-11e6-8b3d-4b891bc2d9eb.png)

I try convert my project to switf3. I get error:
![2](https://cloud.githubusercontent.com/assets/17588791/18869016/92272616-84d4-11e6-83ea-a4ff34bf317c.png)
I try to re-install cocosPod to new version, or old version.. I hot fixed on code, but I can't fixed it.
can you help me?

**Comment by zhangao0086** [comment]
Try this:
```bash
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'master'

```

**Comment by lexuanquynh** [comment]
Thanks @zhangao0086. I fixed it.
Tell me why the reason I get this bug?

**Comment by zhangao0086** [comment]
Also https://github.com/zhangao0086/DKImagePickerController/issues/201
