### ISSUE TITLE
Images taken from camera are oriented incorrectly

### ISSUE THREAD

**Issue by hadwanihardik** [zhangao0086/DKImagePickerController#217]
When  we capture image from camera it send back mis oriented image.

i tried both full image and original image option

**Comment by AnthonyMDev** [comment]
Is anyone else having this issue? I have been unable to reproduce this. 

@hadwanihardik Can you share with us some code of how you are implementing this library please?

**Comment by hadwanihardik** [comment]
Below code resolved my issue.  

  func fixOrientationOfImage(image: UIImage) -> UIImage? {
        if image.imageOrientation == .Up {
            return image
        }
        
        // We need to calculate the proper transformation to make the image upright.
        // We do it in 2 steps: Rotate if Left/Right/Down, and then flip if Mirrored.
        var transform = CGAffineTransformIdentity
        
        switch image.imageOrientation {
        case .Down, .DownMirrored:
            transform = CGAffineTransformTranslate(transform, image.size.width, image.size.height)
            transform = CGAffineTransformRotate(transform, CGFloat(M_PI))
        case .Left, .LeftMirrored:
            transform = CGAffineTransformTranslate(transform, image.size.width, 0)
            transform = CGAffineTransformRotate(transform, CGFloat(M_PI_2))
        case .Right, .RightMirrored:
            transform = CGAffineTransformTranslate(transform, 0, image.size.height)
            transform = CGAffineTransformRotate(transform, -CGFloat(M_PI_2))
        default:
            break
        }
        
        switch image.imageOrientation {
        case .UpMirrored, .DownMirrored:
            transform = CGAffineTransformTranslate(transform, image.size.width, 0)
            transform = CGAffineTransformScale(transform, -1, 1)
        case .LeftMirrored, .RightMirrored:
            transform = CGAffineTransformTranslate(transform, image.size.height, 0)
            transform = CGAffineTransformScale(transform, -1, 1)
        default:
            break
        }
        
        // Now we draw the underlying CGImage into a new context, applying the transform
        // calculated above.
        guard let context = CGBitmapContextCreate(nil, Int(image.size.width), Int(image.size.height), CGImageGetBitsPerComponent(image.CGImage), 0, CGImageGetColorSpace(image.CGImage), CGImageGetBitmapInfo(image.CGImage).rawValue) else {
            return nil
        }
        
        CGContextConcatCTM(context, transform)
        
        switch image.imageOrientation {
        case .Left, .LeftMirrored, .Right, .RightMirrored:
            CGContextDrawImage(context, CGRect(x: 0, y: 0, width: image.size.height, height: image.size.width), image.CGImage)
        default:
            CGContextDrawImage(context, CGRect(origin: .zero, size: image.size), image.CGImage)
        }
        
        // And now we just create a new UIImage from the drawing context
        guard let CGImage = CGBitmapContextCreateImage(context) else {
            return nil
        }
        
        return UIImage(CGImage: CGImage)
    }

**Comment by ferico55** [comment]
this issues has been fixed, please update your pod to the latest version
