### ISSUE TITLE
French localization

### ISSUE THREAD

**Issue by emilienc** [zhangao0086/DKImagePickerController#219]
Hello

Thx for this great pod, may you add the french localization below ?

"select" = "Choix(%ld)";

"permissionCamera" = "Autoriser l'accès à la camera";

"permissionPhoto" = "Autoriser l'accès aux photos";

"permit" = "Autoriser l'accès";

"gotoSettings" = "Aller à 「Paramêtres」 Pour donner l'accès";

"ok" = "OK";

"selectPhotosOrVideos" = "Choisir des photos ou des vidéos";

"selectPhotosOrVideosError" = "Il n'est pas possible de choisir à la fois des photos et des vidéos.";

"done" = "Terminé";

"maxLimitReached" = "Vous avez choisi le nombre maximum de photos";

"maxLimitReachedMessage" = "Vous pouvez choisir %ld items";

**Comment by zhangao0086** [comment]
Hi, I've already merged another French localization:https://github.com/zhangao0086/DKImagePickerController/issues/213
