### ISSUE TITLE
Please add Swift 2.3 support

### ISSUE THREAD

**Issue by retsohuang** [zhangao0086/DKImagePickerController#221]

**Comment by AnthonyMDev** [comment]
@zhangao0086 Do we want to release an actual version with Swift 2.3 support? I know we already have 3.0 support out there, but is it worth support 2.3 also?

If we don't want to push a version for 2.3 support, you can always use an explicit dependency on @mspasov 's fork. The current PR he's got for Swift 2.3 support should work for you.

**Comment by zhangao0086** [comment]
@AnthonyMDev Maybe we should create a branch with Swift 2.3 base on `3.3.4` tag. This branch will out of sync new features and bug fixes with the develop branch. 

What do you think?

**Comment by AnthonyMDev** [comment]
I agree. I can make this happen tomorrow morning if you'd like.

**Comment by zhangao0086** [comment]
@AnthonyMDev Thanks 😄

**Comment by AnthonyMDev** [comment]
Version `3.3.5` has been released with swift 2.3 support.

**Comment by zhangao0086** [comment]
@AnthonyMDev 👍👍👍
