### ISSUE TITLE
App crash when select another photo

### ISSUE THREAD

**Issue by anhkieet** [zhangao0086/DKImagePickerController#225]
Device: Ipad Air 2
IOS: 9.3
Orientation: Landscape

```
let picker = DKImagePickerController()
            picker.assetType = .allPhotos
            picker.maxSelectableCount = 1
            picker.didSelectAssets = { (assets: [DKAsset]) in
                if let asset = assets.first {
                        asset.fetchOriginalImage(true, completeBlock: { (image, object) in
                        })
                    
                }
            }
```

App crash when I select the second photo.

Error message: 

> Terminating app due to uncaught exception 'UIApplicationInvalidInterfaceOrientation', reason: 'Supported orientations has no common orientation with the application, and [UIAlertController shouldAutorotate] is returning YES'

**Comment by anhkieet** [comment]
Sorry, I have fixed it. Please close it. Thank :)

**Comment by zhangao0086** [comment]
Let me know if you have any questions 😄
