### ISSUE TITLE
get data from AVAsset

### ISSUE THREAD

**Issue by Chefda** [zhangao0086/DKImagePickerController#226]
Hello again @zhangao0086,

I'm big fan of DKImagePickerController. I use it to pick images/videos. Then i upload them to ftp server. I need NSURL to do that but you saying: "The asset url is a temp url, so you have to save the selected images to Document directory and upload later." I'm okay with that. I can get data from images thanks to fetchOriginalImage method. But it can not work for videos. I use swift 2 and AVAsset has no member 'URL' so i get error from below code. Can you show me another way please?

asset.fetchAVAssetWithCompleteBlock ({ (aVAsset, info) -> Void in
                   data = NSData(contentsOfURL: avAsset!.URL)   //Value of type 'AVAsset' has no member 'URL'
})

**Comment by zhangao0086** [comment]
@Chefda Thank you for your support :) You can use the following API:
```swift
// DKAsset.swift

/**
 Writes the image in the receiver to the file specified by a given path.
 */
public func writeImageToFile(_ path: String, completeBlock: @escaping (_ success: Bool) -> Void)

/**
 Writes the AV in the receiver to the file specified by a given path.
 
 - parameter presetName:    An NSString specifying the name of the preset template for the export. See AVAssetExportPresetXXX.
 */
public func writeAVToFile(_ path: String, presetName: String, completeBlock: @escaping (_ success: Bool) -> Void)
```

Like this:
```swift
let destinationPath = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0].appending("/test.mov")
assets.first?.writeAVToFile(destinationPath, presetName: AVAssetExportPresetHighestQuality, completeBlock: { (success) in
    print(success)
})
```
