### ISSUE TITLE
How to record video using DKImagePickerController ? If it isn't supported could you please add that ?

### ISSUE THREAD

**Issue by neoD1** [zhangao0086/DKImagePickerController#229]

**Comment by hadwanihardik** [comment]
did you found any solution for this? @neoD1

**Comment by dms90** [comment]
Any update about this?

**Comment by zhangao0086** [comment]
I uploaded a test project. Hope this have helped you.

[TestDKImagePickerControllerObjc.zip](https://github.com/zhangao0086/DKImagePickerController/files/1010535/TestDKImagePickerControllerObjc.zip)

**Comment by dms90** [comment]
Thanks @zhangao0086 for the soon response! 👍
