### ISSUE TITLE
Xcode 8 Migration Showing me lot of error 

### ISSUE THREAD

**Issue by vinod1988** [zhangao0086/DKImagePickerController#239]
I have working project on xcode 7 with swift version 2.3 its working fine. After i have updated the Xcode 8 and all development, its showing me lot of error. Can you please suggest me what changes have to be done on swift version3.

**Comment by zhangao0086** [comment]
Could you show me those errors and your Podfile?

**Comment by zhangao0086** [comment]
Closing this thread.
