### ISSUE TITLE
limit selection

### ISSUE THREAD

**Issue by SambathChea** [zhangao0086/DKImagePickerController#240]
I have one problem I want to select 10 both image and video but I want user can select only 1 video and 9 image. what should I do ?
thank in advance.

**Comment by zhangao0086** [comment]
May need to add the following method in `DKImagePickerControllerUIDelegate`
```swift
func imagePickerController(_ imagePickerController: DKImagePickerController, willSelectAssets: [DKAsset]) -> Bool
```

then calls it in `func collectionView(_ collectionView: UICollectionView, shouldSelectItemAt indexPath: IndexPath) -> Bool`

**Comment by SambathChea** [comment]
one more I when I get image for library that extension are DKAsset, How can I convert it to image URL ?

**Comment by zhangao0086** [comment]
You have to save the selected images to your Document directory:
```swift
// DKAsset.swift

/**
 Writes the image in the receiver to the file specified by a given path.
 */
public func writeImageToFile(_ path: String, completeBlock: @escaping (_ success: Bool) -> Void)

/**
 Writes the AV in the receiver to the file specified by a given path.
 
 - parameter presetName:    An NSString specifying the name of the preset template for the export. See AVAssetExportPresetXXX.
 */
public func writeAVToFile(_ path: String, presetName: String, completeBlock: @escaping (_ success: Bool) -> Void)
```

**Comment by zhangao0086** [comment]
Closing this thread.
