### ISSUE TITLE
captured image does not save location data?

### ISSUE THREAD

**Issue by hadwanihardik** [zhangao0086/DKImagePickerController#242]
When we capture image from using this library it does not save location details. same time when we capture image from the camera app it saves image with location details.
i checked location services are enabled for the app.

**Comment by zhangao0086** [comment]
Hi @hadwanihardik 
I tried for a few hours, but did not find a way to write metadata with PHPhotoLibrary :(

**Comment by zhangao0086** [comment]
Fixed.
