### ISSUE TITLE
选中相机后,拍照后 发现 返回不了 ,按 重拍 也没有反应

### ISSUE THREAD

**Issue by manajay** [zhangao0086/DKImagePickerController#244]
最上传头像功能 ,选中相机后,拍照后 发现 返回不了 ,按 重拍 也没有反应
配置如下
        pickerController.UIDelegate = CustomUIDelegate()
        pickerController.modalPresentationStyle = .overCurrentContext
        
        pickerController.assetType = .allPhotos
        pickerController.allowsLandscape = false
        pickerController.allowMultipleTypes = true
        pickerController.sourceType = both
        pickerController.singleSelect = false
        pickerController.maxSelectableCount = 1
        (self.viewController()?.navigationController!)!.present(pickerController, animated: true) {}

**Comment by zhangao0086** [comment]
已修复
