### ISSUE TITLE
Removal of options.deliveryMode causes crash

### ISSUE THREAD

**Issue by Vancion** [zhangao0086/DKImagePickerController#245]
My code:  
```
for asset in dkAssets {
    self.group.enter()
    asset.fetchImageWithSize(CGSize(width: 720, height: 1280), completeBlock: { (image: UIImage?, info: [AnyHashable : Any]?) in
        if let image = image {
            images.append(image)
        }
        self.group.leave()
    })
}

self.group.notify(queue: .main) {
......
```
I get an "thread 1 exc_bad_instruction (code=exc_i386_invop subcode=0x0)" error on self.group.leave().

After some investigation, it seems like the removal of options.deliveryMode = .highQualityFormat in 3.4.1 caused the problem. If I add it back, the error is gone.
```
private lazy var defaultImageRequestOptions: PHImageRequestOptions = {
    let options = PHImageRequestOptions()
    options.deliveryMode = .highQualityFormat
    return options
}()
```

I am not sure what really causes the problem. Can you take a look? Thanks.

**Comment by ferico55** [comment]
Thank you for your report, this case already fixed in the latest version, please update your pod and try again.
Please kindly report any issues you encounter during usage of this library
