### ISSUE TITLE
Hide album "My photo stream"

### ISSUE THREAD

**Issue by LucidityDesign** [zhangao0086/DKImagePickerController#25]
Because you are using the AssetsLibrary instead of Photo Framework it is not easily possible to fetch PHAssets if the user selects images from "My photo stream" (see http://stackoverflow.com/questions/26480526/alassetslibrary-assetforurl-always-returning-nil-for-photos-in-my-photo-stream).
Is it possible to hide the album "my photo stream" or better: have you considered to switch to Photo Framework?

**Comment by LucidityDesign** [comment]
Sorry, this is fixed with ca9b591.
But please let me know if you are thinking about switching to Photo Framework.

**Comment by zhangao0086** [comment]
Hi @LucidityDesign 
Yes, I like the Photo Framework, but it supports iOS8 only. Do you think compatible ios7 is necessary?

**Comment by LucidityDesign** [comment]
I think with the iOS 9 release iOS 7 support is not necessary. But that's just my personal opinion and you have to keep in mind that there are still iPhone 4 out there who can't update to iOS 8 or 9.

I think this report might come in handy: https://mixpanel.com/trends/#report/ios_9

**Comment by zhangao0086** [comment]
Thank you @LucidityDesign !
It's very useful to me :) I think I will use the Photo Framework instead of AssetsLibrary :)

**Comment by doguhanokumus** [comment]
+1 for the Photo Framework, would be a great addition

**Comment by zhangao0086** [comment]
I will release the 3.0.0 with Photos framework. [develop](https://github.com/zhangao0086/DKImagePickerController/tree/develop).

**Comment by LucidityDesign** [comment]
Wow! Thank you so much!!
