### ISSUE TITLE
images from library have wrong order

### ISSUE THREAD

**Issue by sergJozee** [zhangao0086/DKImagePickerController#251]
When i pick images from the library i do not get the images to show in the correct order. The first image i pick from library does not always show as first image in the list with chosen images.
<img width="374" alt="schermafbeelding 2016-11-22 om 14 50 16" src="https://cloud.githubusercontent.com/assets/15928490/20526185/4532ef3c-b0c3-11e6-83b4-67d3dd9aeac5.png">
<img width="358" alt="schermafbeelding 2016-11-22 om 14 52 34" src="https://cloud.githubusercontent.com/assets/15928490/20526203/590530e2-b0c3-11e6-8eed-a5ec8e56fe44.png">

**Comment by DesmondDAI** [comment]
@sergJozee I met the same problem. I pick the according index using `enumerated()`

**Comment by zhangao0086** [comment]
@sergJozee Could you post your code about show chosen images?

**Comment by DesmondDAI** [comment]
@zhangao0086 

I tried to multi select photos:
```swift
let pickerController = DKImagePickerController()
pickerController.assetType = .AllPhotos
pickerController.showsCancelButton = true
pickerController.maxSelectableCount = 5

pickerController.didSelectAssets = { (assets: [DKAsset]) in
    for (index, asset) in self.selectedImageAssets.enumerate() {
        asset.fetchImageWithSize(CGSizeMake(512, 512), options: getImageRequestOptions(), contentMode: PHImageContentMode.AspectFill, completeBlock: {
            (image, info) in
            print("index: \(index)")
        })
    }
}
```

And the function **getImageRequestOptions()**:
```swift
private func getImageRequestOptions() -> PHImageRequestOptions {
    let options = PHImageRequestOptions()
    options.deliveryMode = PHImageRequestOptionsDeliveryMode.HighQualityFormat
    options.networkAccessAllowed = true
    return options
}
```

The printed `index` is out of order. e.g. `3 1 2 0`

**Comment by zhangao0086** [comment]
Hi @DesmondDAI 
The `fetchImageWithSize` is an asynchronous method. It will get images from your device or iCloud, so the callback order is not guaranteed.

**Comment by annphan** [comment]
I have the same issue. Is there any ways to resolve this issue?

**Comment by annphan** [comment]
@zhangao0086 Any ideas on this please?

**Comment by annphan** [comment]
Update: using this method and then it should work well. 
public func fetchFullScreenImage(sync: Bool, completeBlock: (image: UIImage?, info: [NSObject : AnyObject]?) -> Void)
