### ISSUE TITLE
Error when implementing DKImagePickerControllerDefaultUIDelegate protocol

### ISSUE THREAD

**Issue by thacilima** [zhangao0086/DKImagePickerController#252]
I am trying to create a CustomUIDelegate class which implements a DKImagePickerControllerDefaultUIDelegate like the following code:

```swift
class ImagePickerCustomUIDelegate: DKImagePickerControllerDefaultUIDelegate {
    
    override func imagePickerControllerCheckedImageTintColor() -> UIColor? {
        return UIColor.black
    }
}
```

Before adding that code, the project was compiling normally and the basic example of DKImagePickerController was working. After that, I started getting the following error when trying to build:

"direct field offset for DKImagePickerController.DKImagePickerControllerDefaultUIDelegate.(doneButton.storage in _05C026158387582BAD923CF0457DA1FC) : __ObjC.UIButton?", referenced from:
      DKImagePickerController.DKImagePickerControllerDefaultUIDelegate.doneButton.setter : __ObjC.UIButton in ViewController.o
      DKImagePickerController.DKImagePickerControllerDefaultUIDelegate.(doneButton.materializeForSet : __ObjC.UIButton).(closure #1) in ViewController.o

I am using Carthage and I think maybe it may be related to that, anyone knows anything about this error?

**Comment by zhangao0086** [comment]
Hi @thacilima 
I've updated the code to remove the lazy properties.
Could you please check now using `develop` branch?

```
github "zhangao0086/DKImagePickerController" "develop"
```

**Comment by thacilima** [comment]
@zhangao0086 Now it's working!
