### ISSUE TITLE
UICollectionView do not reloaddata.

### ISSUE THREAD

**Issue by potscars** [zhangao0086/DKImagePickerController#253]
Hello, thanks for sharing the library. I'm having a problem using it, its work fine. But once i select the images. The collectionView not reloading, I try to select once again. Then the collectionView reloading, and adding the previous selected images not the new selected one. Here the codes, thanks. 

imagePicker.didSelectAssets = { (assets: [DKAsset]) in
            for asset in assets {

                asset.fetchOriginalImageWithCompleteBlock({ (image, info) in
 
                    guard let imageData = UIImageJPEGRepresentation(image!, 0) else {
                        print("There is no image bro..!")
                        return
                    }
                    let thumbnails = UIImage(data: imageData)
                    self.imageArray.append(thumbnails!)   
                })
            }
            DispatchQueue.main.async {
                self.collectionView.reloadData()
            }
        }

**Comment by ismailtosun** [comment]
+1
