### ISSUE TITLE
Cant do anything after 'cancel' or 'take a picture' from PickerView using CustomCamera (using demo code)

### ISSUE THREAD

**Issue by kotdark** [zhangao0086/DKImagePickerController#255]
I modifier your demo code a litter bit as:
 - Uncomment line 36 37 of ViewController.swift
 - Using DKImagePickerController version support swift 2.3 (my code still swift 2.3)

Then I build and using demo app, I choose 'Take a picture' function.

After that, I tap on 'Cancel' button, or take a picture.

PickerView dismiss, but I cant do anything after pickerview dismissed.
I try do debug as 'Debug View Hierarchy' and I can see reason. It has 3 view display over ViewController as: UITransitionView > UILayoutContainerView > UINavigationTransitionView

My question is: How can I fixed this bug? 

Thank you.

**Comment by zhangao0086** [comment]
Fixed in develop.
Could you please check now using `develop` branch?

**Comment by masbenx** [comment]
after selected picture and grab the image, custom camera wont dismiss the view or segue to another view

this is my code
`let imagePicker = DKImagePickerController()
        
        imagePicker.UIDelegate = CustomCameraUIDelegate()
        imagePicker.modalPresentationStyle = .overCurrentContext
        
        imagePicker.sourceType = .camera
        imagePicker.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
            
            let asset = assets[0]
            let destinationPath = NSSearchPathForDirectoriesInDomains(.documentDirectory, .userDomainMask, true)[0].appending("/lapor.png")

            asset.writeImageToFile(destinationPath, completeBlock: { (result) in
                if !result {
                    APESuperHUD.showOrUpdateHUD(icon: .sadFace, message: "failed get image", duration: 2, presentingView: self.view)
                }else {
                    let image = UIImage(contentsOfFile: destinationPath)
                    
                    if let imageData = UIImageJPEGRepresentation(image!, 0) {
                        self.latitude = self.locManager.location?.coordinate.latitude
                        self.longitude = self.locManager.location?.coordinate.longitude
                        
                        self.laporData = imageData
                        self.laporImage = image
                        
                        DispatchQueue.main.async(execute: { () in
                            self.performSegue(withIdentifier: "laporProfileLabel", sender: nil)
                        })
                    }else {
                        APESuperHUD.showOrUpdateHUD(icon: .sadFace, message: "failed get image", duration: 2, presentingView: self.view)
                    }
                }
            })
        }
        
        self.present(imagePicker, animated: true) {}`
