### ISSUE TITLE
Allow overriding of done()

### ISSUE THREAD

**Issue by elementsrtyte** [zhangao0086/DKImagePickerController#256]
I'd like to suggest a change to the done() function in DKImagePickerController. Can we make this method open to subclassing by simply changing:
```public func done()```
to
```open func done()```

It's a pretty common use case where the user would want to push a review view controller after selecting a few images rather than dismissing it.

Let me know if you have any questions.

Thanks,
Neil

**Comment by zhangao0086** [comment]
I agree with your :)

**Comment by abdulla-allaith** [comment]
Any update regarding this? Both the ```done``` and ```dismiss``` functions should be customizable/overridable.
Is that possible with Swift 2.3 as well?

**Comment by zhangao0086** [comment]
Swift2.3 branch was deleted. Closing this thread.
