### ISSUE TITLE
iOS10的内存泄漏问题，好像属性是闭包都会引起，可以关注一下

### ISSUE THREAD

**Issue by qyning** [zhangao0086/DKImagePickerController#258]
我新建一个工程测试了一下
ViewController只要调用 nettool.toUpdateBlock 就会 swift_slowAlloc的内存泄漏

// VC:
class ViewController: UIViewController{
      ....

    var nettool:NetTool!
    private func updateNetData() {
        nettool = NetTool()
        nettool.toUpdateBlock = {()->Void in
            print("收到回调")
        }
    }
}
// otherTool
class NetTool: NSObject {
    .....
    var toUpdateBlock:(()->Void)?
    func toUpdate()  {
        toUpdateBlock?()
    }
}

**Comment by zhangao0086** [comment]
内存泄漏和 DKImagePickerController 有关么？

**Comment by qyning** [comment]
@zhangao0086 ,使用swift3，在我的项目中发现instruments在 iOS10下会有内存泄漏，找了很久没发现原因，以上那个闭包使用在iOS10就会产生leaks，所以我找了一波github的工程测试一下。发现很多都会发生这种情况

你可以用instruments打开一下你的demo，在iOS9没有问题，iOS10会出现非常多的leaks，我感觉是iOS10 的问题。如果您有时间可以帮忙分析一下

**Comment by zhangao0086** [comment]
好的，感谢提醒

**Comment by malonguwa** [comment]
你好，使用Swift 3, Xcode8 纯净项目，以下几句代码执行后instruments出现400+的内存泄漏，也就是从imagePickerController modal出来的一瞬间就出现了，我点击Done, 推掉controller, 再打开，又会出现400+的新泄漏。我是点击按钮就弹出imagePickerController, 不知道是否是我使用不当造成的呢？

```
@IBAction func clickPic(_ sender: Any) {
  let picController = DKImagePickerController()
        picController.didSelectAssets = { [weak self] (assets : [DKAsset]) in
        }
        present(picController, animated: true)
}
```

**Comment by hyouuu** [comment]
也发现了泄漏问题，希望这些log有帮助：
<img width="908" alt="screen shot 2018-03-25 at 2 24 29 am" src="https://user-images.githubusercontent.com/5061867/37873617-23226886-2fd5-11e8-9118-e14df48969ce.png">
<img width="1113" alt="screen shot 2018-03-25 at 2 24 36 am" src="https://user-images.githubusercontent.com/5061867/37873618-234fe982-2fd5-11e8-8582-8f8146470a09.png">
<img width="959" alt="screen shot 2018-03-25 at 2 24 44 am" src="https://user-images.githubusercontent.com/5061867/37873619-236a15b4-2fd5-11e8-8d63-f87345e2dbed.png">
