### ISSUE TITLE
Original Picture

### ISSUE THREAD

**Issue by josaal17** [zhangao0086/DKImagePickerController#26]
Hello, my question is about the pic, in the example select but is a thumbnail (low quality and small), How to select the image, video original from the library or camera?

Thanks

**Comment by zhangao0086** [comment]
Hi @josaal17 
You can use `asset.fullResolutionImage` or `asset.fullScreenImage` for image. For video, do you want to get the video as `NSData`?

**Comment by josaal17** [comment]
Thanks, it's works!!

**Comment by josaal17** [comment]
I'm sorry, I had not seen the other question!, Yes i need get the video as NSData!

**Comment by zhangao0086** [comment]
Hi @josaal17 

The originalAsset becomes public property in `2.3.0`, now you can get the raw data of the selected assets like this:

```swift
pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
    print("didSelectAssets")
    print(assets.map({ $0.url}))
	
	if let rep = assets.first?.originalAsset?.defaultRepresentation() {
		let sizeOfRawDataInBytes = Int(rep.size())
		let rawData = NSMutableData(length: sizeOfRawDataInBytes)!
		let bufferPtr = rawData.mutableBytes
		let bufferPtr8 = UnsafeMutablePointer<UInt8>(bufferPtr)

		rep.getBytes(bufferPtr8, fromOffset: 0, length: sizeOfRawDataInBytes, error: nil)
		print(rawData)
	}
    
    self.assets = assets
    self.previewView?.reloadData()
}
```
