### ISSUE TITLE
Nothing works after custom camera is dismissed using cancel button. 

### ISSUE THREAD

**Issue by vivektakrani** [zhangao0086/DKImagePickerController#263]
Hey, thanks for such a great library. 

I am able to create a custom camera, the issue is when clicked on cancel button the camera is dismissed but I am unable to click any element that are there on the view.

I am even presenting it overCurrentContext, don't know what's wrong. Can you please help?

**Comment by zhangao0086** [comment]
Please check out the `develop` branch. If you are using CocoaPods, just try this:
```
pod 'DKImagePickerController', :branch => 'develop'
```
I updated the implementation of `CustomCamera` in the `develop` branch. Please refer to `CustomCamera.swift`.

**Comment by vivektakrani** [comment]
Okay, will check that and give you an update...

**Comment by zhangao0086** [comment]
Fixed.
