### ISSUE TITLE
use of undeclared type 'DKImagePickerController'

### ISSUE THREAD

**Issue by carlhung** [zhangao0086/DKImagePickerController#268]
i was using 'pod install'.
after installing, i's encountered use of undeclared type 'DKImagePickerController' and 'DKAsset' on my viewController.

**Comment by WilliamLCobb** [comment]
Found the answer here: http://stackoverflow.com/questions/35270303/use-of-undeclared-type-dkasset-use-of-unresolved-identifier-dkimagepickercon

**Comment by zhangao0086** [comment]
Closing this thread...
