### ISSUE TITLE
cant do pod install , branch swift2.3

### ISSUE THREAD

**Issue by tranvutuan** [zhangao0086/DKImagePickerController#269]
Currently in my podfile, I am 
`pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'swift2.3'`

However, I am getting an error when doing pod install
```
[!] Unable to load a podspec from `DKImagePickerController.podspec`, skipping:

Pod::DSLError
```
Any suggestions about this error ?

**Comment by tranvutuan** [comment]
i dont see you tag 3.3.6 branch

**Comment by zhangao0086** [comment]
Swift2.3 branch was deleted. Closing this thread.
