### ISSUE TITLE
didRotateFromInterfaceOrientation was deprecated in iOS 8.0

### ISSUE THREAD

**Issue by A1iAshoor** [zhangao0086/DKImagePickerController#27]
should be version check..

**Comment by Anders123fr** [comment]
Would be awesome if this could be fixed!

**Comment by zhangao0086** [comment]
Hi @A1iAshoor @Anders123fr 
I agree with you :) I had temporarily suppressed the warning on the [2.3.6](https://github.com/zhangao0086/DKImagePickerController/commit/ec078af4ce947cc8819a74fb51113f30242bf990)

**Comment by A1iAshoor** [comment]
@zhangao0086 man. you are awesome. thumps up.

**Comment by zhangao0086** [comment]
@A1iAshoor 

Let me know if you have any questions. :)
