### ISSUE TITLE
No images displayed on second launch

### ISSUE THREAD

**Issue by preraksola** [zhangao0086/DKImagePickerController#270]
Hello,

I am facing a very weird issue. In my app, if I launch the image picker for the first time, everything goes smooth. Upon selecting the images or cancelling the image picker I return back to my view controller.
However, if I again launch the image picker, the  picker gets displayed with the toolbar buttons Done and Cancel but I can not see any images.

My test environment is:
Xcode: 8.2.1
Device: iPhone 6 Simulator
OS: iOS 10.2

Is this a bug or am I missing something from my side?

Thanks,
Prerak

**Comment by deutschmannstefan** [comment]
I had the same Problem.

I have fixed it by setting my Member Variable to nil after setDidSelectAssets and setDidCancel

```
[self.picker setDidSelectAssets:^(NSArray * __nonnull assets) {
         self.picker = nil;
}];
[self.picker setDidCancel:^{
        self.picker = nil;
 }];
```

**Comment by zhangao0086** [comment]
Fixed.
