### ISSUE TITLE
从相册选择照片,看不到qq内保存的图片

### ISSUE THREAD

**Issue by jinyu1122** [zhangao0086/DKImagePickerController#272]
在ios系统相册中，qq内新保存的图片会显示在"我的胶卷"相册和"QQ"相册中。
但是使用DKImagePickerController从相册选择图片，相册选择“我的胶卷”，找不到qq内新保存的图片。

**Comment by zhangao0086** [comment]
这个应该是默认的排序有点问题。现在是按创建时间排序，QQ 应该是按修改时间排序，相册内照片的数量应该是一样的。
我打算下次提交时更新下排序方式。

**Comment by jinyu1122** [comment]
回复好快，赞！

**Comment by zhangao0086** [comment]
Closing this thread.
