### ISSUE TITLE
i want to get files which have date after specific date.. 

### ISSUE THREAD

**Issue by shindonghyeok** [zhangao0086/DKImagePickerController#273]
i hope image picker shows some special images and videos which have date after specific date. 
i mean if specific date is 2017.02.01, then i want to get a files after 2017.02.01.. can u understand..?? 
is it possible? if yes... how can i do this? 
thank u for your project

**Comment by zhangao0086** [comment]
```swift
pickerController.assetFilter = { asset in
    return asset.creationDate...
}
```
