### ISSUE TITLE
change color

### ISSUE THREAD

**Issue by rennyrun** [zhangao0086/DKImagePickerController#274]
I want to change border color for selected cell but in version 3.5.0 I can't found imagePickerControllerCheckedImageTintColor even if I already subclass DKImagePickerControllerDefaultUIDelegate.
Any other way to set them?

Thanks

**Comment by iad24** [comment]
Any updates on this one?

**Comment by zhangao0086** [comment]
Please see [ui-customization](https://github.com/zhangao0086/DKImagePickerController/tree/develop#ui-customization).
