### ISSUE TITLE
AssetType can't be changed once we have presented the picker controller.

### ISSUE THREAD

**Issue by jovanpreet** [zhangao0086/DKImagePickerController#276]
Let i have set the the assetType to .allPhotos and then presented the controller then i press cancel. Now i set the assetType to .allVideos but it won't change now. Is there any workaround for that?

**Comment by acjh** [comment]
You can present a different instance.

```swift
let photoPicker = DKImagePickerController()
photoPicker.assetType = .allPhotos

let videoPicker = DKImagePickerController()
videoPicker.assetType = .allVideos
```

**Comment by jovanpreet** [comment]
Is it possible with just one pickerController

**Comment by acjh** [comment]
Why do you need it to be the same instance?

**Comment by jovanpreet** [comment]
Your above solution also didn't work. Setting assetType to later controller affects first controller

**Comment by acjh** [comment]
Ah, I was creating each instance just before presenting (which works), rather than keeping references.

**Comment by jovanpreet** [comment]
Yes that was the only solution that worked by creating instance every time before presenting. Also i have to save the selectedAsset and set the selectedAsset to pickerController before presenting.

But why this happens?
Why can't we create two instances?

**Comment by ignivaankitchauhan** [comment]
This problem occurs due to its _shared instance._ I have found a solution to this problem. Whenever you call **DKImagePickerController()** , dispose its previous instance before that.

Paste this method in **DKImageManager** class :

```
    func disposeInstance()
    {
        DKImageManager.Static.instance = nil
    }
```

And Call it before creating any object of **DKImagePickerController()**. Like this:

```
DKImageManager.sharedInstance.disposeInstance()
let photoPicker = DKImagePickerController()
photoPicker.assetType = .allPhotos
```

OR

```
DKImageManager.sharedInstance.disposeInstance()
let videoPicker = DKImagePickerController()
videoPicker.assetType = .allVideos

```

Hope It helps!
Cheers !
Happy Coding :)

**Comment by snehageorge** [comment]
Hi @ignivaankitchauhan , I'm facing the same issue. How can I fix this ?
Tried
DKImageManager.Static.instance = nil
But gets an error

Type 'DKImageManager' has no member 'Static'
I am using DKImagePickerController - version 3.6 (Pods)
