### ISSUE TITLE
It crashed

### ISSUE THREAD

**Issue by mwapptest** [zhangao0086/DKImagePickerController#28]
Hi,

Thanks for sharing wonderful library. I have just installed on my phone and it was crash when you choose photos only option from examples.
 
in DKAsset:
        self.thumbnailImage = UIImage(CGImage:originalAsset.thumbnail().takeRetainedValue())

with error message "fatal error: unexpectedly found nil while unwrapping an Optional value"

Not sure what is reason but when I tried to open camera it was asking me permission but when it was allowed it was crashed again. No debug statment generated that time.

Let me know if you need more information for this issues.

Thanks
Manoj

**Comment by zhangao0086** [comment]
Hi @mwapptest 
What's your phone version? (e.g. iPhone 6 Plus iOS 9)

**Comment by mwapptest** [comment]
my phone is 5s with 9.0.2

**Comment by zhangao0086** [comment]
Hi @mwapptest 

The issue has been fixed :)
https://github.com/zhangao0086/DKImagePickerController/issues/14?partial=issues%2Fsidebar%2Fshow%2Flabels
