### ISSUE TITLE
DKCamera 拍照后对图片宽高处理的有问题

### ISSUE THREAD

**Issue by iostang** [zhangao0086/DKImagePickerController#281]
使用iPhone6s Plus拍照 正常会得到一张4032x3024或3024x4032 
可实际结果是4032x2269 或 2269x4032

Swift-2.3
Xcode-8.1
macOS-10.12
DK版本-3.3.5

检查代码后发现
DKCamera.swift

public func takePicture()

let outputRect = self.previewLayer.metadataOutputRectOfInterestForRect(self.previewLayer.bounds)

outputRect.size = {0.75,1} 或 {1，0.75}

let cropRect = CGRectMake(outputRect.origin.x * width, outputRect.origin.y * height, outputRect.size.width * width, outputRect.size.height * height)

宽度或者高度或被计算成 2269 导致图片比例变了

**Comment by zhangao0086** [comment]
做这个裁剪的目的是保持图片与看到的一致；与本地照相机拍摄出来的比例是否相同并不重要。
