### ISSUE TITLE
问题

### ISSUE THREAD

**Issue by huangboju** [zhangao0086/DKImagePickerController#282]
asset.fetchImageWithSize(CGSize(width: (SCREEN_WIDTH - 2) / 3, height: (SCREEN_WIDTH - 2) / 3).toPixel(), options: nil, contentMode: .aspectFill, completeBlock: { [weak self] image, info in
                    这里会走两遍
                })

**Comment by zhangao0086** [comment]
这是因为 options 传 nil 的话，内部会自动使用一个 deliveryMode 为 opportunistic 的 options 对象；opportunistic 会回调多次，回调的图片会越来越清晰，这样显示一张大图时不会空白很久。
