### ISSUE TITLE
Cancel Dismiss Always sent to root

### ISSUE THREAD

**Issue by masbenx** [zhangao0086/DKImagePickerController#287]
when I try to hit cancel button on camera view, all the view are dismiss and sent to root view controller

**Comment by woowhoo** [comment]
i got the same issue

**Comment by mkarakeh** [comment]
In DKImagePickerController.swift
Comment     self.dismiss(animated: false)  in createCamera Function
```
    private func createCamera() -> UIViewController {
        let didCancel = { () in
            if self.sourceType == .camera {
                self.dismiss(animated: true, completion: nil)
               // self.dismiss(animated: false)
            } else {
                self.dismiss(animated: true, completion: nil)
            }
        }
```

Thank you

**Comment by zhangao0086** [comment]
Closing this thread. Feel free to re-open if your issue is not solved.

**Comment by ChendayUP** [comment]
private func showCamera(isInline: Bool) {
        let didCancel = { [unowned self] () in
            if self.sourceType == .camera {
                self.dismissCamera(isInline: true)
//                self.dismiss()
            } else {
                self.dismissCamera()
            }
        }
i got the same issue
i fix like this

**Comment by psnt143** [comment]
private func showCamera(isInline: Bool) {
        let didCancel = { [unowned self] () in
            if self.sourceType == .camera {
//                self.dismissCamera(isInline: true)
//                self.dismiss()
            } else {
                self.dismissCamera()
            }
        }
i got both lines commented but still problems.

**Comment by udaantech** [comment]
I too was unable to close camera on button click.
Nothing help me with it.
