### ISSUE TITLE
Present new VC upon selecting single asset.

### ISSUE THREAD

**Issue by Andriyas123** [zhangao0086/DKImagePickerController#290]
Hello! I have Single Select set to true. How do I present a new VC after I select this asset? As of now nothing happens, it just comes back to root VC. Thanks!

**Comment by elainelinlin** [comment]
You can override done() and take out the dismiss presenting VC block:

  `override func done() {
        self.didSelectAssets?(self.selectedAssets)
    }`

And then in your didSelectAsset method:

`imagePickerViewController.didSelectAssets = { (assets: [DKAsset]) in
	if !assets.isEmpty {
		assets[0].fetchOriginalImage(false) { [weak self] (image, info) in
		guard let image = image, let _self = self else { return }
                if imagePickerViewController.presentedViewController is DKImagePickerControllerCamera {
                        imagePickerViewController.dismiss(animated: true, completion: {
                            UIView.transition(with: UIApplication.shared.keyWindow!, duration: 0.4, options: .transitionCrossDissolve, animations: {
                                _self.presentAnotherVCHere(image: image)
                            })
                        })
                    } else {
                        UIView.transition(with: UIApplication.shared.keyWindow!, duration: 0.4, options: .transitionCrossDissolve, animations: {
                            imagePickerViewController.dismiss(animated: false)
                            _self.presentAnotherVCHere(image: image)
                        })
                    }
		}
	}
}
`

In your present VC method:
`func presentAnotherVCHere(image: UIImage) {
          // Initialize anotherVC and set delegate
          present(anotherVC, animated: false, completion: nil)
}`

Notice that animation boolean must be set to false if you are using the UIView.transition block.

**Comment by elainelinlin** [comment]
You can override done() and take out the dismiss presenting VC block:

  ```
override func done() {
         self.didSelectAssets?(self.selectedAssets)
 }
```

And then in your didSelectAsset method:

```
imagePickerViewController.didSelectAssets = { (assets: [DKAsset]) in
	if !assets.isEmpty {
		assets[0].fetchOriginalImage(false) { [weak self] (image, info) in
		guard let image = image, let _self = self else { return }
                if imagePickerViewController.presentedViewController is DKImagePickerControllerCamera {
                        imagePickerViewController.dismiss(animated: true, completion: {
                            UIView.transition(with: UIApplication.shared.keyWindow!, duration: 0.4, options: .transitionCrossDissolve, animations: {
                                _self.presentAnotherVCHere(image: image)
                            })
                        })
                    } else {
                        UIView.transition(with: UIApplication.shared.keyWindow!, duration: 0.4, options: .transitionCrossDissolve, animations: {
                            imagePickerViewController.dismiss(animated: false)
                            _self.presentAnotherVCHere(image: image)
                        })
                    }
		}
	}
}
```

In your present VC method:
```
func presentAnotherVCHere(image: UIImage) {
          // Initialize anotherVC and set delegate
          present(anotherVC, animated: false, completion: nil)
}
```

Notice that animation boolean must be set to false if you are using the UIView.transition block.

**Comment by zhangao0086** [comment]
Hi @elainelinlin , thanks for your answer! It's right!

**Comment by elainelinlin** [comment]
Hi @zhangao0086 , thanks! Actually I was having the same problem and this was my solution. However, the downside of this is that the transition between the camera to a customVC was not as smooth because of the dismiss method inside didFinishCapturingImage():

```
open class DKImagePickerController: UINavigationController {
      ...
      private func createCamera() -> UIViewController {
            ...
            let didFinishCapturingImage = { (image: UIImage) in
            
            var newImageIdentifier: String!

            PHPhotoLibrary.shared().performChanges({
                let assetRequest = PHAssetChangeRequest.creationRequestForAsset(from: image)
                newImageIdentifier = assetRequest.placeholderForCreatedAsset!.localIdentifier
            }) { (success, error) in
                DispatchQueue.main.async(execute: {
                    if success {
                        if let newAsset = PHAsset.fetchAssets(withLocalIdentifiers: [newImageIdentifier], options: nil).firstObject {
                            if self.presentedViewController != nil {
                                self.dismiss(animated: true, completion: nil)      // This line here
                            }
                            self.selectImage(DKAsset(originalAsset: newAsset))
                        }
                    } else {
                        if self.sourceType != .camera {
                            self.dismiss(animated: true, completion: nil)
                        }
                        self.selectImage(DKAsset(image: image))
                    }
                })
                
            }
        }
      ...
      }
```

In order to get a smooth transition, I was trying to remove that line of code from this method and deal with transition the same way I did with selecting an image from a photo album. However, I wasn't sure which method I should overwrite and which class to subclass this for. Really all I need is to just remove that line of code. What are your suggestions?

Right now the way I have it set up (the solution I posted), the user sees the camera being dismissed modally before another view fades in, when the ideal solution should have the view fade in without waiting for the camera to be dismissed.

Much appreciate your input!

**Comment by zhangao0086** [comment]
There is no good way to solve it :( I will deal with this situation in the next version.

**Comment by storix** [comment]
I was able to present a new VC seamlessly (without glitches, flashes and other mess) by taking a screenshot of the image picker and adding to the root VC. I would greatly appreciate if you could share a better approach.
