### ISSUE TITLE
album selection button color

### ISSUE THREAD

**Issue by DesmondDAI** [zhangao0086/DKImagePickerController#291]
I am using version 3.3.5, and cannot find an API to change selection button color. Is there a way that I don't know to change it?

**Comment by zhangao0086** [comment]
Try this:
```swift
pickerController.navigationBar.tintColor = UIColor.red
```

**Comment by DesmondDAI** [comment]
@zhangao0086 Thanks...Just came up with the same solution after posting the question. Stupid me >_<
