### ISSUE TITLE
Does not confirm protocol

### ISSUE THREAD

**Issue by ArjunSa786** [zhangao0086/DKImagePickerController#3]
![Uploading Screen Shot 2015-07-16 at 7.49.56 pm.png…]()

**Comment by zhangao0086** [comment]
Sorry? I can't see the screen shot?

**Comment by ArjunSa786** [comment]
No Problem  the problem is solve.  and wonderful demo this one. thanks

**Comment by zhangao0086** [comment]
You are welcome :)

**Comment by ArjunSa786** [comment]
hi in your code how to limit only 20 images selected??

**Comment by zhangao0086** [comment]
Hi, I have added a property as `maxSelectableCount`, then you can 
```
let pickerController = DKImagePickerController()
pickerController.maxSelectableCount = 20
```

**Comment by ArjunSa786** [comment]
Thank you so much ..:)

**Comment by zhangao0086** [comment]
You are welcome :)

**Comment by ArjunSa786** [comment]
how to  get image location?
    if let location: CLLocation = asset.valueForProperty(ALAssetPropertyLocation) as CLLocation!

**Comment by zhangao0086** [comment]
Try this:
```
import CoreLocation
```

**Comment by ArjunSa786** [comment]
thank you
