### ISSUE TITLE
修改之后实现了查看大图功能，但是一次性读取相册里所有的原图 ，导致内存溢出

### ISSUE THREAD

**Issue by menicor** [zhangao0086/DKImagePickerController#300]
如题 
let group = getImageManager().groupDataManager.fetchGroupWithGroupId(selectedGroupId!)
for i in 0..<group.totalCount{
                let asset = getImageManager().groupDataManager.fetchAsset(group, index: i)
                asset.fetchOriginalImageWithCompleteBlock({ (image, info) in
                    
                    
                })
            }
查看大图最好是滑到某一个cell的时候再去读取大图

**Comment by zhangao0086** [comment]
这个功能在`4.0.0-Beta`中加上了。后续还会再做一些优化。
