### ISSUE TITLE
CustomCameraUIDelegate is objective-C

### ISSUE THREAD

**Issue by nishanth9493** [zhangao0086/DKImagePickerController#305]
How to use the custom camera in objective-c class. 

Or how to record video in objective-c

**Comment by zhangao0086** [comment]
Hi @nishanth9493 

I uploaded a test project. Hope this have helped you.

[TestDKImagePickerControllerObjc.zip](https://github.com/zhangao0086/DKImagePickerController/files/1010535/TestDKImagePickerControllerObjc.zip)
