### ISSUE TITLE
Crash in the new update version

### ISSUE THREAD

**Issue by hyouuu** [zhangao0086/DKImagePickerController#309]
Got Crashlytics report about many crashes in DKAssetGroupListVC.swift on line 228:
```
// MARK: - DKGroupDataManagerObserver methods
	
	func groupDidUpdate(_ groupId: String) {
		let indexPath = IndexPath(row: self.groups!.index(of: groupId)!, section: 0)
		self.tableView.reloadRows(at: [indexPath], with: .none)
	}
```

The call is from file DKBaseManager.swift on line 32:
```
open func notifyObserversWithSelector(_ selector: Selector, object: AnyObject?, objectTwo: AnyObject?) {
		if self.observers.count > 0 {
			DispatchQueue.main.async(execute: { () -> Void in
				for observer in self.observers.allObjects {
					if observer.responds(to: selector) {
						_ = observer.perform(selector, with: object, with: objectTwo)
					}
				}
			})
		}
	}
```

Example crash message:
`Fatal Exception: NSInternalInconsistencyException`
`attempt to delete row 3 from section 0 which only contains 1 rows before the update`

**Comment by zhangao0086** [comment]
Hi @hyouuu 
I can't reproduce the issue, could you provide some more information?

**Comment by hyouuu** [comment]
I can reproduce by having the gallery picker open, then go to iOS Gallery and remove an album and go back to the gallery picker. 
However, based on the number of users experiencing crashes, I think there are other ways to trigger the issue as well. Note that this never happened before the latest release of 3.5.2

**Comment by zhangao0086** [comment]
@hyouuu Could you try the `develop` branch? It's 3.5.3.

**Comment by hyouuu** [comment]
Tried 3.5.3 and the same crash occurs - please try the steps yourself

**Comment by zhangao0086** [comment]
I still can't reproduce... I recorded a short video of how I tried it :( 
I used test devices: 6s plus(10.2.1), 6 plus(10.3.2).

[recording1.mp4.zip](https://github.com/zhangao0086/DKImagePickerController/files/1021756/recording1.mp4.zip)

**Comment by hyouuu** [comment]
Thanks for trying it out - please don't go to the test folder, rather, just stay in the default All Photos initial screen, then go to Gallery and delete an _existing_ album, then go back to the All Photos screen and it would crash after half second

**Comment by zhangao0086** [comment]
I reproduced! Thank your! Fixed in the `develop` branch :)

**Comment by hyouuu** [comment]
Thanks! Please note that in my original post crashes happen in groupDidUpdate as well, but for that one I'm not sure how to reproduce - probably photo changes in an album?

**Comment by hyouuu** [comment]
Should be fixed - I'll check in prod ;)

**Comment by zhangao0086** [comment]
I can reproduce by update an album name. Thank you for your PR :)
