### ISSUE TITLE
Change tick blue to another color

### ISSUE THREAD

**Issue by lam560** [zhangao0086/DKImagePickerController#313]
How to change tick blue to another color ?

It seems the code fetch an png image named "tick_blue" but I can't find it.

**Comment by zhangao0086** [comment]
The "tick_blue" image is in the bundle:
![image](https://cloud.githubusercontent.com/assets/7742344/26390924/3b81e712-4093-11e7-836f-0ec09f9489d2.png)

**Comment by iad24** [comment]
@zhangao0086 So no other way to change the color of the tick but to replace here?

**Comment by zhangao0086** [comment]
See the example: [CustomUIDelegate](https://github.com/zhangao0086/DKImagePickerController/tree/develop/DKImagePickerControllerDemo/CustomUIDelegate)
