### ISSUE TITLE
Add or removal of photo album does not updated dynamically.

### ISSUE THREAD

**Issue by DragonCherry** [zhangao0086/DKImagePickerController#317]
When I add or remove album, it does not appear on album list. Every changes should be applied to the album list.

**Comment by zhangao0086** [comment]
Hi @DragonCherry 
Could you try the `develop` branch?

```swift
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'develop'
```

**Comment by DragonCherry** [comment]
@zhangao0086 
I've checked it appears in the list, but the size of album view does not change to fit them well. When I close and reopen album list, it works well then.

**Comment by zhangao0086** [comment]
Fixed! Please check the `develop` branch again!

**Comment by DragonCherry** [comment]
Now it works perfectly. Really appreciate your jobs done. Thank you!
