### ISSUE TITLE
Removing Selected Assets (images) from camera roll after picking

### ISSUE THREAD

**Issue by Owaisss10** [zhangao0086/DKImagePickerController#318]
Hi. First of all thanks for this awesome picker. 
My query :  I want to delete images from camera roll after saving them in my app. I want those selected images to delete permanently from my camera roll. I am not sure how and where to take a start. Please help me. Thanks :)
Here's my code of opening DKPickerController and saving photos.

        func showImagePicker() {
        pickerController.defaultSelectedAssets = self.assets
        
        pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
            print("didSelectAssets")
            print(assets.count)
      
            for asset in assets {
                asset.fetchOriginalImageWithCompleteBlock({ (image, info) in
                    print(image!)
                    self.storePhoto(image2: image!)  // Saving Images in my app through this function
                    self.collectionView.reloadData()
                })
            }
            
            self.assets = assets
            self.collectionView?.reloadData()  
        }
        self.present(pickerController, animated: true) {}
    }

**Comment by zhangao0086** [comment]
Hi @Owaisss10 
Try this:
```swift
...
for asset in assets {
    asset.fetchOriginalImageWithCompleteBlock({ (image, info) in
        print(image!)
        self.storePhoto(image2: image!)  // Saving Images in my app through this function
        self.removeAssetFromCameraRoll(asset) // delete images from camera roll
        self.collectionView.reloadData()
    })
}
...


func removeAssetFromCameraRoll(_ asset: DKAsset) {
    PHPhotoLibrary.shared().performChanges({
        PHAssetChangeRequest.deleteAssets(PHAsset.fetchAssets(withLocalIdentifiers: [asset.localIdentifier], options: nil))
    }) { (success, error) in
    }
}

```

**Comment by Owaisss10** [comment]
Worked like a charm ! :') 
Thank you very much.
