### ISSUE TITLE
Deselecting photos does not update the numbering.

### ISSUE THREAD

**Issue by marmoy** [zhangao0086/DKImagePickerController#32]
If you have selected a number of photos and decide to **de**select one (or more), the relative numbering of the rest of the photos does not get updated. 

For example if you have selected 3 photos, and then deselect number 2, then the remaining two photos will still be numbered 1 and 3. Expected behaviour would be that number 3 would change to 2. 

This also has the effect that when you then continue to select another photo, then there will be three photos with the numbers 1, 3 and 3.

**Comment by zhangao0086** [comment]
@marmoy 
Thanks for your feedback! The bug has been fixed on 2.3.1! :)
