### ISSUE TITLE
Remove the camera item in the picker?

### ISSUE THREAD

**Issue by hamzakhanfcb10** [zhangao0086/DKImagePickerController#320]
Hey,,

How can i remove the first item i.e Camera icon from the picker? 

Thanks in advance.

@zhangao0086

**Comment by hamzakhanfcb10** [comment]
and one more thing how to change the title and done button title.

**Comment by zhangao0086** [comment]
If you want to hide the camera icon, please try this:

```swift
pickerController.sourceType = .photo
```
About how to change the title and done button title, see also: https://github.com/zhangao0086/DKImagePickerController#camera-customization
