### ISSUE TITLE
DKImageManager's groupDataManager getter issue after invalidate()

### ISSUE THREAD

**Issue by juli1quere** [zhangao0086/DKImagePickerController#321]
Hello, 

There is a little bug in `DKImageManager` with the `groupDataManager` getter. Indeed, this is a `lazy` var. But, in the `invalidate()` method, this var is set to `nil`. 

The problem is that `lazy` in a one-time initializer. So, if we try to access `groupDataManager` after an `invalidate()` call, the initializer will not be called. And we have a Bad Access. 

To test this issue, you just have to display the controller twice in a row: 

```swift
    func showImagesPicker() {
        let picker = DKImagePickerController()
        picker.singleSelect = true
        picker.sourceType = .photo
        self.present(picker, animated: true, completion: nil)
    }
```

I'm preparing a PR to fix this :)

**Comment by zhangao0086** [comment]
Thanks!
