### ISSUE TITLE
VERY URGENT !!! - How can I change "Send" button color and localization

### ISSUE THREAD

**Issue by smartsidd** [zhangao0086/DKImagePickerController#323]
How can I change "Send" button color and localization for "send" and "camera" text. Please need very urgent. Please help.

I attached screen shots please check..  
![simulator screen shot jun 19 2017 10 12 20 am](https://user-images.githubusercontent.com/1187989/27269917-48ec15e0-54d8-11e7-9b71-f8069f89a7af.png)

**Comment by zhangao0086** [comment]
If you use your custom UIDelegate, you can modify them in your file. Please refer to `CustomUIDelegate` and `CustomGroupDetailCameraCell`.

**Comment by smartsidd** [comment]
Thanks Its SOLVED .. cheers
