### ISSUE TITLE
Upcoming problem with Swift 4

### ISSUE THREAD

**Issue by bitwizardry-net** [zhangao0086/DKImagePickerController#324]
Hello,

I just found out that the following code in DKImageManager won't work anymore with Swift 4:

```
public lazy var groupDataManager: DKGroupDataManager! = {
        return DKGroupDataManager()
}()
	
public func invalidate() {
	self.groupDataManager.invalidate()
        self.groupDataManager = nil
}
````
See also here:
https://stackoverflow.com/questions/25072597/re-initialize-a-lazy-initialized-variable-in-swift

It seems that lazy vars won't be re-initialized when set to empty. A solution would be to re-move the lazy keyword and implement the same behaviour as computed propert with a get{} handler and an internal variable.

**Comment by zhangao0086** [comment]
Rather helpful! Thank you! 😃

**Comment by zhangao0086** [comment]
Fixed.
