### ISSUE TITLE
NEED to update in GERMAN and SPANISH -- Urgent please refer screen shots!!!!

### ISSUE THREAD

**Issue by smartsidd** [zhangao0086/DKImagePickerController#325]
![app1](https://user-images.githubusercontent.com/1187989/27477322-64110124-5829-11e7-8904-98b07a387ef2.png)
![img_1164](https://user-images.githubusercontent.com/1187989/27477362-8f7d59d4-5829-11e7-90d9-0e854f938c46.PNG)

**Comment by zhangao0086** [comment]
Do you mean "This app requires access to the photo library" and "Camera usage description"?

**Comment by smartsidd** [comment]
yes

**Comment by zhangao0086** [comment]
You can modify them in your `Info.plist` file.

**Comment by smartsidd** [comment]
Thanks @zhangao0086 for fast reply.

**Comment by smartsidd** [comment]
thanks bro

**Comment by smartsidd** [comment]
Hi bro,

Please help its not working for xcode 9  and swift 4 . URGER

[image: Inline image 1]

Thanks,
Brother
