### ISSUE TITLE
Couldn't read shared photos by iCloud

### ISSUE THREAD

**Issue by PinkPhayate** [zhangao0086/DKImagePickerController#328]
i couldn't see photos shared in icloud, in colletions of DKAssetGroupDetailVC.
i arranged  pickerController below.

```
let pickerController = DKImagePickerController()
pickerController.autoDownloadWhenAssetIsInCloud = true
```

however, view in DKAssetGroupDetailVC doesn't show photos shared in iCloud.
I don't find out this reason. Is it feature? Did i forget to permit any object?

This problem bothers me a lot.
Would you please tell me this reason.

Thank you.

**Comment by zhangao0086** [comment]
Try this:
```swift
pickerController.assetGroupTypes = [
    .smartAlbumFavorites,
    .albumCloudShared
]
```

**Comment by PinkPhayate** [comment]
Got it! great!
I can see photos.

Thank you for all your assistance.
