### ISSUE TITLE
Unrecognized Locale in build when upload to iTunes Connect

### ISSUE THREAD

**Issue by LiborZ** [zhangao0086/DKImagePickerController#332]
Hi,

I get message below when I upload build to TestFlight to iTunes Connect. It's warning so build is available but could you fix it? Thanks

> Unrecognized Locale -
> The directory located at ( 'Payload/PNGQA.app/Frameworks/DKImagePickerController.framework/DKImagePickerController.bundle/DK-nb-NO.lproj' ) has an unrecognized locale name. Refer to the Language and Locale Designations guide ( https://developer.apple.com/library/ios/#documentation/MacOSX/Conceptual/BPInternational/Articles/LanguageDesignations.html%23//apple_ref/doc/uid/20002144-SW3 ) for more information on naming your language-specific directories.

**Comment by zhangao0086** [comment]
Hi
The issue was fixed in https://github.com/zhangao0086/DKImagePickerController/pull/330.
I'll update pod on this weekend. :)

**Comment by LiborZ** [comment]
Hi,
thank you for quick answer.
