### ISSUE TITLE
how to resolve this issue i got this message app store after updating my app? 

### ISSUE THREAD

**Issue by UmaMadhavi** [zhangao0086/DKImagePickerController#335]
The directory located at
 ('Payload/myapp.app/Frameworks/DKImagePickerController.framework/DKImagePickerController.bundle/DK-nb-NO.lproj' ) has an unrecognized locale name. Refer to the Language and Locale Designations guide for more information on naming your language-specific directories.

**Comment by zhangao0086** [comment]
The issue was fixed in #330. :)

**Comment by UmaMadhavi** [comment]
@zhangao0086 Thank you
