### ISSUE TITLE
Crash when showsEmptyAlbums is false and no pictures are available

### ISSUE THREAD

**Issue by GregOriol** [zhangao0086/DKImagePickerController#338]
When the image picker is set to `showsEmptyAlbums = false` and the are no non-empty albums to show, the components and app crashs on a optional unwrap which is nil.

The error exactly is `fatal error: unexpectedly found nil while unwrapping an Optional value` and it happens on `DKAssetGroupDetailVC.swift` `func updateTitleView()` line 136, where there is a force un-wrap on `self.selectedGroupId!` which is nil in this case.

One quick-solution I found could be to add an `if !groupIds.isEmpty {` around calls to `strongSelf.updatePartial(...)` in `fetchGroups` of `DKGroupDataManager.swift` => then the image picker shows up empty. Not perfect but good enough as a quick-fix. What do you think?

**Comment by zhangao0086** [comment]
It's my fault! You're right! Could you send me a PR?
