### ISSUE TITLE
Record video through camera

### ISSUE THREAD

**Issue by rehannali** [zhangao0086/DKImagePickerController#342]
How can I record only video from the camera? 
I can't see any documentation of this and I don't understand where I can change to work.
Could you please tell me where I can find it.

**Comment by rehannali** [comment]
Or there is any way I can replace DKcamera with an Original camera to record video and then switch to image Picker controller?

**Comment by zhangao0086** [comment]
For example, see [CustomCameraUIDelegate](https://github.com/zhangao0086/DKImagePickerController#camera-customization).

![87099752-8405-4274-84e7-3de721780cbc](https://user-images.githubusercontent.com/7742344/28016054-4cde8326-65a5-11e7-80eb-63c55ca4543f.png)

**Comment by rehannali** [comment]
How i can add this classes to my project? I can't see in pod files.

**Comment by zhangao0086** [comment]
You can copy it to your project.

**Comment by rehannali** [comment]
And for usage?

**Comment by rehannali** [comment]
Actually, i want to press camera button which is already present in collection view and that record video and returns to again collection view for selection and upload purposes.

**Comment by zhangao0086** [comment]
Try this:
```swift
let pickerController = DKImagePickerController()
pickerController.UIDelegate = CustomCameraUIDelegate()
pickerController.modalPresentationStyle = .overCurrentContext

self.present(pickerController, animated: true) {}
```

**Comment by rehannali** [comment]
Thanks. this solution helps me a lot. I have on problem, I copied files in the project and whenever I update or install pod, this will remove those files from the directory. Could you help me with this problem? How can I prevent those deletions while update or new installation of pods?

**Comment by zhangao0086** [comment]
Hi @rehannali 
You should copy these files to **your project** not **Pods project**.

**Comment by rehannali** [comment]
@zhangao0086 I copy files to my project but it gives me an error that's why I copy it to Pods project.
"Custom camera delegate not found" error.

**Comment by rehannali** [comment]
It always gives me an error, use of undeclared type "DKImagepickercontrollerDefaultuidelegate"

**Comment by rehannali** [comment]
Yeah, I find solutions for my problem. Thanks for helping me.
