### ISSUE TITLE
Italian Language

### ISSUE THREAD

**Issue by adabag** [zhangao0086/DKImagePickerController#344]
Hello, 
thank you for the library. May you add the italian language?

Thanks.

"select" = "Seleziona(%ld)";
"permissionCamera" = "Premettere l'accesso alla fotocamera";
"permissionPhoto" = "Permettere l'accesso alla gallery";
"permit" = "Permettere l'accesso";
"gotoSettings" = "Vai a「Impostazioni」per permettere l'accesso";
"ok" = "OK";
"selectPhotosOrVideos" = "Selezionare foto o video";
"selectPhotosOrVideosError" = "Non è possibile selezionare contemporaneamente sia foto che video.";
"done" = "Fatto";
"maxLimitReached" = "Raggiunto il numero massimo di foto";
"maxLimitReachedMessage" = "Puoi selezionare %ld elementi";

**Comment by zhangao0086** [comment]
Done.
