### ISSUE TITLE
Square image

### ISSUE THREAD

**Issue by pqhuy87it** [zhangao0086/DKImagePickerController#346]
how can i get only square images ?

**Comment by zhangao0086** [comment]
You can crop selected image to square after user selecting.

**Comment by pqhuy87it** [comment]
i mean i only want to get the images which was captured in "Square" mode in camera
![img_0033](https://user-images.githubusercontent.com/5575899/28152651-cc1b3e0e-67cb-11e7-858e-305dcf7df6f1.PNG)

**Comment by zhangao0086** [comment]
Hi @pqhuy87it 
There is no way to filter `SQUARE` mode in `Photos framework`. :(

**Comment by pqhuy87it** [comment]
thank you, i have found another way to do that, check image size after user choice.
