### ISSUE TITLE
Asking for Photo Library Access on launch??

### ISSUE THREAD

**Issue by covetalex** [zhangao0086/DKImagePickerController#352]
For some reason the pod is asking for photo library permission on launch even tho I'm not importing or initialising it in appdelegate. What could be causing this?

Thanks

**Comment by zhangao0086** [comment]
Could you provide more information? I think the picker will not ask for permission if `DKImagePickerController` has not initialized.

**Comment by santhoshs5** [comment]
I am also facing this issue @covetalex  how can we resolve this?

**Comment by zhangao0086** [comment]
Closing this thread...
