### ISSUE TITLE
Class PLBuildVersion is implemented in both ... warning occurred

### ISSUE THREAD

**Issue by poqw** [zhangao0086/DKImagePickerController#355]
Every time I run the app, I get a warning like this:

>objc[42625]: Class PLBuildVersion is implemented in both /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/AssetsLibraryServices.framework/AssetsLibraryServices (0x11c2a8cc0) and /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator.sdk/System/Library/PrivateFrameworks/PhotoLibraryServices.framework/PhotoLibraryServices (0x11c0bf6f0). One of the two will be used. Which one is undefined.

It seems that I warning appears when I import this library.
And I also found this [answer](https://stackoverflow.com/a/39582284/7433468) and this [answer](https://stackoverflow.com/a/39759000/7433468).
But still not working.
I want to get rid of this annoying warning.
can anyone help me?

**Comment by zhangao0086** [comment]
Maybe the issue is unrelated to this library.

**Comment by poqw** [comment]
@zhangao0086 You are right.  I am sorry to make an issue without recognizing it properly. 
In this [discussion](https://stackoverflow.com/questions/39520499/class-plbuildversion-is-implemented-in-both-frameworks), It is known bug in Xcode8 that I can ignore it as I cannot fix it. Thank you for your feedback. :)
