### ISSUE TITLE
拍照后保存到相册的照片exif信息丢失了

### ISSUE THREAD

**Issue by wenxp** [zhangao0086/DKImagePickerController#357]
@zhangao0086 您好，我们在使用该库时候发现将图片保存到系统相册时，exif信息丢失了，为了能够在保存图片到系统相册时保留exif信息，我对本库做了如下修改：
1、DKImagePickerControllerCameraProtocol中添加：
   func setDidFinishCapturingImage_Data(block: @escaping (_ data: Data) -> Void) -> Void
2、DKImagePickerController.swift文件中添加import AssetsLibrary
3、DKImagePickerController.swift文件函数private func createCamera() -> UIViewController中添加：
   let didFinishCapturingImage_Data = { [unowned self] (data: Data) in

            if #available(iOS 9.0, *) {
                self.capturingImage_Data_9(data)
            } else {
                self.capturingImage_Data_8(data)
            }

        }
  和
cameraProtocol.setDidFinishCapturingImage_Data(block: didFinishCapturingImage_Data)
4、添加两个函数：
 internal func capturingImage_Data_8(_ data: Data) {
        let library = ALAssetsLibrary()
        library.writeImageData(toSavedPhotosAlbum: data, metadata: nil, completionBlock: { [weak self] (newURL, error) in
            if let _ = error {
                if self?.sourceType != .camera {
                    self?.dismiss(animated: true, completion: nil)
                }
                self?.selectImage(DKAsset(image: UIImage(data: data)!))
            }
            else{
                if let newAsset = PHAsset.fetchAssets(withALAssetURLs: [newURL!], options: nil).firstObject {
                    if self?.presentedViewController != nil {
                        self?.dismiss(animated: true, completion: nil)
                    }
                    self?.selectImage(DKAsset(originalAsset: newAsset))
                }
            }
        })
    }

    internal func capturingImage_Data_9(_ data: Data) {
        var newImageIdentifier: String!

        PHPhotoLibrary.shared().performChanges({

            if #available(iOS 9.0, *) {
                let assetRequest = PHAssetCreationRequest.forAsset()
                assetRequest.addResource(with: .photo, data: data, options: nil)
                newImageIdentifier = assetRequest.placeholderForCreatedAsset!.localIdentifier
            } else {
                // Fallback on earlier versions
            }
        }) { [weak self] (success, error) in
            DispatchQueue.main.async(execute: { [weak self] in
                if success {
                    if let newAsset = PHAsset.fetchAssets(withLocalIdentifiers: [newImageIdentifier], options: nil).firstObject {
                        if self?.presentedViewController != nil {
                            self?.dismiss(animated: true, completion: nil)
                        }
                        self?.selectImage(DKAsset(originalAsset: newAsset))
                    }
                } else {
                    if self?.sourceType != .camera {
                        self?.dismiss(animated: true, completion: nil)
                    }
                    self?.selectImage(DKAsset(image: UIImage(data: data)!))
                }
            })
            
        }
    }
5、DKCamera.swift文件函数open func takePicture()
修改代码：
//                                didFinishCapturingImage(cropTakenImage)

                                if let didFinishCapturingImage_Data = self.didFinishCapturingImage_Data {

                                    didFinishCapturingImage_Data(imageData)
                                }
6、类DKImagePickerControllerCamera中添加：
open func setDidFinishCapturingImage_Data(block: @escaping (Data) -> Void) {
        super.didFinishCapturingImage_Data = block
    }
共以上6处修改，为了保证之前代码的连贯性，我暂时未将修改的代码合并进来，请楼主审查修改代码的正确性。
我是在3.5.7版本上做的修改，并fork了一个分支，地址为：https://github.com/wenxp/DKImagePickerController.git，分支为Branch3.5.7

**Comment by zhangao0086** [comment]
感谢你的方案！我觉得没什么太大问题，你可以直接发 PR 了 :) 
非常感谢！如果后续我作修改的话，我可能会把 setDidFinishCapturingImage_Data 和 setDidFinishCapturingImage 这两个接口合并，就像 SDWebImage 的 SDWebImageDownloaderCompletedBlock 设计一样 :)

**Comment by zhangao0086** [comment]
已合并 :)
