### ISSUE TITLE
Excessive memory use when display images on UIcollectionview 

### ISSUE THREAD

**Issue by SnehalDhanani** [zhangao0086/DKImagePickerController#364]
First of all, thanks for the great ImagePicker!! 
I tried the demo app and it is working fine. No memory issue. Then tried the same code in to my app and it is using too much memory.
 I am not sure How to reduce the memory usage when display all selected images on collectionview. Any help will be much appreciated!!
This is given Demo app of the Library 
<img width="560" alt="screen shot 2017-08-24 at 2 13 00 pm" src="https://user-images.githubusercontent.com/25752018/29681700-8a576b24-88d6-11e7-92ff-04bb3aaf2a98.png">

My app
<img width="503" alt="screen shot 2017-08-24 at 2 12 19 pm" src="https://user-images.githubusercontent.com/25752018/29681690-80c7d08a-88d6-11e7-8d44-5ad64f00db93.png">

Here is the code I use,

        pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
            print("didSelectAssets")
            
            self.assets = assets
            self.previewView?.reloadData()
        }

    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let asset = self.assets![indexPath.row]
        var cell: UICollectionViewCell?
        var imageView: UIImageView?
        
        if asset.isVideo {
            cell = collectionView.dequeueReusableCell(withReuseIdentifier: "CellVideo", for: indexPath)
            imageView = cell?.contentView.viewWithTag(1) as? UIImageView
        } else {
            cell = collectionView.dequeueReusableCell(withReuseIdentifier: "CellImage", for: indexPath)
            imageView = cell?.contentView.viewWithTag(1) as? UIImageView
        }
        
        if let cell = cell, let imageView = imageView {
            let layout = collectionView.collectionViewLayout as! UICollectionViewFlowLayout
            let tag = indexPath.row + 1
            cell.tag = tag
            asset.fetchImageWithSize(layout.itemSize.toPixel(), completeBlock: { image, info in
                if cell.tag == tag {
                    imageView.image = image
                    self.imageArr.append(image!)
                }
            })
        }
        
        return cell!
    }

Don't know what I m missing. Anything anyone can suggest ? 
Thank you!!

**Comment by SnehalDhanani** [comment]
I try running the project on real device and it was working fine. My bad.

**Comment by zhangao0086** [comment]
Feel free to re-open if your issue is not solved.

**Comment by erfanwakka** [comment]
Same Here!
