### ISSUE TITLE
4.0.0

### ISSUE THREAD

**Issue by zhangao0086** [zhangao0086/DKImagePickerController#370]
## What's New

- [x] Improving animation effects.
- [x] Adding image editing feature when taking an image from the camera.(Using [CLImageEditor](https://github.com/yackle/CLImageEditor))
- [x] Make library working for both Swift 3.2 and 4
- [x] Adding assets preview feature.(Using [DKPhotoGallery](https://github.com/zhangao0086/DKPhotoGallery))
- [x] Refactoring API
- [x] HEIF & HEVC #378 

[4.0.0 develop branch](https://github.com/zhangao0086/DKImagePickerController/tree/Feature/4.0.0)

**Comment by rdadkins** [comment]
See #319 for second goal

**Comment by swftvsn** [comment]
Please include Swift 4 support: #376 and #377
