### ISSUE TITLE
Completion block runs twice for larger image sizes

### ISSUE THREAD

**Issue by benpackard** [zhangao0086/DKImagePickerController#371]
When selecting an image using the following image picker, the completion block executes twice:

```
let controller = DKImagePickerController()
controller.assetType = .allPhotos
controller.sourceType = .photo
controller.didSelectAssets = { assets in
	let imageSize = 150
	let size = CGSize(width: imageSize, height: imageSize)
	for (index, asset) in assets.enumerated() {
		print("Fetching asset for image \(index)")
		asset.fetchImageWithSize(size) { _ in
			print("Image \(index) fetched, executing completion block.")
		}
	}
}
present(controller, animated: true, completion: nil)
```

The expected output would be:

```
Fetching asset for image 0
Image 0 fetched, executing completion block.
```

But the actual output is:

```
Fetching asset for image 0
Image 0 fetched, executing completion block.
Image 0 fetched, executing completion block.
```

Curiously, when changing `imageSize` to from 150 to 100, the issue does not occur.

For this test, I used the iOS 7 simulator and selected one of the default images from the camera roll.

**Comment by benpackard** [comment]
Some additional info - it appears that the first time the completion block fires, it returns the image at the thumbnail size. The second time it returns the larger requested image.

Additionally, the second image does not actually match the requested size in my experience. Instead, it returns the original size I believe (I used a size of 1200x1200 but received back 1668.0 x 2500.0). I could add this as a separate issue but perhaps it is related.

**Comment by zhangao0086** [comment]
This issue happens because the internal manager uses a default PHImageRequestOptions, which `deliveryMode` is opportunistic and `resizeMode` is none(client may get several image results when the call is asynchronous or will get one result when the call is synchronous).

You can call `fetchImageWithSize` with specific PHImageRequestOptions:
```swift
let options = PHImageRequestOptions()
options.resizeMode = .exact

asset.fetchImageWithSize(layout.itemSize.toPixel(), options: options, completeBlock: { _ in
})
```

This usage may not be convenient, and may give the caller ambiguity. I'll try to simplify these API more in the next version.

**Comment by zhangao0086** [comment]
Feel free to reopen it if not solved.

**Comment by mydy1987** [comment]
I get the same bug ,when I do it like this:
```
let options = PHImageRequestOptions()
options.resizeMode = .exact

asset.fetchImageWithSize(size, options: options, completeBlock: { _ in
})
```
It does not work, the completionBlock is still called twice.
I did not find the synchronous API.

**Comment by davem2020** [comment]
I am also getting the completion block called twice with the following code-

```
PHImageRequestOptions *initialRequestOptions = [[PHImageRequestOptions alloc] init];
        initialRequestOptions.resizeMode = PHImageRequestOptionsResizeModeExact;
        [asset fetchOriginalImageWithOptions:initialRequestOptions completeBlock:^(UIImage * image, NSDictionary * dictionary) {
...}];
```

**Comment by davem2020** [comment]
I am also getting the completion block called twice with the following code-

```
PHImageRequestOptions *initialRequestOptions = [[PHImageRequestOptions alloc] init];
        initialRequestOptions.resizeMode = PHImageRequestOptionsResizeModeExact;
        [asset fetchOriginalImageWithOptions:initialRequestOptions completeBlock:^(UIImage * image, NSDictionary * dictionary) {
...}];
```

**Comment by i0sa** [comment]
same thing

**Comment by ios4vn** [comment]
> I get the same bug ,when I do it like this:
> 
> ```
> let options = PHImageRequestOptions()
> options.resizeMode = .exact
> 
> asset.fetchImageWithSize(size, options: options, completeBlock: { _ in
> })
> ```
> It does not work, the completionBlock is still called twice.
> I did not find the synchronous API.

I'm adding 
`options.deliveryMode = .highQualityFormat`

**Comment by alexanderritik** [comment]
I found the solution if this issue and it calls only one time with high quality image

        let asset = images[indexPath.row]
        let manager = PHImageManager.default()

        var imageRequestOptions: PHImageRequestOptions{
            let options = PHImageRequestOptions()
            options.version = .current
            options.resizeMode = .exact
            options.deliveryMode = .highQualityFormat
            options.isNetworkAccessAllowed = true
            options.isSynchronous = true
            return options
        }
        
        manager.requestImage(for: asset,
                             targetSize: PHImageManagerMaximumSize,
                             contentMode: .aspectFit,
                             options: imageRequestOptions) { (thumbnail, info) in
                                   print("High Quality Image thumbnail ! " )
                                }
