### ISSUE TITLE
Can i show the assets in sections based on date?

### ISSUE THREAD

**Issue by santhoshs5** [zhangao0086/DKImagePickerController#372]
Can i show the assets in sections based on date?

If i want achieve what could be the best approach with your library.

**Comment by zhangao0086** [comment]
Not supported yet :(

**Comment by santhoshs5** [comment]
Can I get the array of DKAssets so that i can sort and display in my custom view controller.

**Comment by zhangao0086** [comment]
You can try to make a subclass of `DKImagePickerController` then return the custom subclass of `DKAssetGroupDetailVC` in the makeRootVC function.
