### ISSUE TITLE
can i show progress bar on DKImagePickerController

### ISSUE THREAD

**Issue by santhoshs5** [zhangao0086/DKImagePickerController#373]
I have a required where i want mark some of assets based on some processing which takes little while i need to show progress bar and reload the data.

Can i do this without modifying in code files using it as pod.
Please explain if i can do it.

**Comment by zhangao0086** [comment]
When do you want to show the progress bar?

**Comment by santhoshs5** [comment]
before reloading  the collection view which displays assets for first time with camera rool and when changing the album.

**Comment by zhangao0086** [comment]
I think you need to make `var collectionView`/`func selectAssetGroup` to `open` then overrides them.

**Comment by santhoshs5** [comment]
Thanks

**Comment by santhoshs5** [comment]
how can write my custom functionalities to select all assets and still get count ?

**Comment by zhangao0086** [comment]
Closing this thread.
