### ISSUE TITLE
'AVCaptureStillImageOutput' was deprecated in iOS 10.0: Use AVCapturePhotoOutput instead

### ISSUE THREAD

**Issue by Premal-Khetani** [zhangao0086/DKImagePickerController#374]
Hello, This is really very nice library. 

I got these warnings while building in xcode. 

DKCamera.swift:113:44: 'AVCaptureStillImageOutput' was deprecated in iOS 10.0: Use AVCapturePhotoOutput instead

What to do? 

Thank you.

**Comment by zhangao0086** [comment]
Updated in `3.8.0`
