### ISSUE TITLE
Custom active camera 

### ISSUE THREAD

**Issue by leo009394** [zhangao0086/DKImagePickerController#380]
Hi,

I added an UIBarButtonItem with a camera icon on footer using "imagePickerControllerFooterView".
How can I active the camera when click on that bar button, and can I remove the camera cell from the the picker

Thanks in advance.

**Comment by dms90** [comment]
Same here! :( we need custom camera

**Comment by zhangao0086** [comment]
> can I remove the camera cell from the the picker

pickerController.sourceType = .photo

> How can I active the camera when click on that bar button

In `3.8.0`, you can call the `presentCamera` function to present a camera.
