### ISSUE TITLE
Usage of AVFileType only available in iOS 11+

### ISSUE THREAD

**Issue by GregOriol** [zhangao0086/DKImagePickerController#383]
It seems that you are using AVFileType starting from version 3.8, but this class is only available in iOS 11+. It should be protected with `@available` maybe?

**Comment by zhangao0086** [comment]
Hi @GregOriol Look like the AVFileType has existed from iOS 4.
![image](https://user-images.githubusercontent.com/7742344/30914858-9ac8bc94-a35a-11e7-995b-51688c12418b.png)

I have been tested on iOS10 without errors. Do you encounter any problems?

**Comment by GregOriol** [comment]
Ah! Apple doc says 11+ here: https://developer.apple.com/documentation/avfoundation/avfiletype but .mov is indeed 4+ (https://developer.apple.com/documentation/avfoundation/avfiletype/1386770-mov), strange I could not compile because of error on this, maybe wrong alert, I'll double-check!

**Comment by desmond0321** [comment]
@GregOriol I face the same error too, you found a way to fix it?

**Comment by GregOriol** [comment]
Same errors I had

Maybe it's a Swift version incompatibility, since the pod is in Swift 4 since 3.8, project should be in Swift 4 too?

**Comment by zhangao0086** [comment]
Hi @GregOriol @desmond0321  
For Swift 3.*, use version < 3.8.0 😆 
https://github.com/zhangao0086/DKImagePickerController#swift-3

**Comment by DavidKababyan** [comment]
im using latest version with xcode 9 and deployment to ios 11 but still get all the errors in above picture

**Comment by tonyisid** [comment]
I got this same error in xcode 9, with the latest version.

**Comment by zhangao0086** [comment]
@DavidKababyan @tonyisid 

Please make sure you are using Swift 4.

1. The Swift Version setting of DKImagePickerController is set to Swift 4.
2. If you have a .swift-version file under your project, make sure the content of it is "4.0".
3. Try to clean your project.

![image](https://user-images.githubusercontent.com/7742344/31002413-456a9bb2-a4b0-11e7-9a1b-ceb26f8f7801.png)

**Comment by izuchy** [comment]
@zhangao0086 
I use it with objective-c. 
If swift 4 is specified in cocoapods, the problem seems to be solved, but the property of the instance of DKImagePickerController can not be referenced and an error occurs.

**Comment by zhangao0086** [comment]
@izuchy 
You can enable `Swift 3 @objc inference` in Xcode 9 to temporarily solve this problem:
![image](https://user-images.githubusercontent.com/7742344/31043755-32943c1e-a587-11e7-8bfd-93cfc134cd7b.png)

**Comment by GregOriol** [comment]
Also, if going backwards with version 3.6 check this: https://github.com/CocoaPods/CocoaPods/issues/6791
Seems that by default, Cocoapods now may leave "Swift 4.0", and it is needed to switch it manually to 3.2 (or through post_install scripts)

**Comment by zhangao0086** [comment]
Closing this thread.

**Comment by o-zaporozhchenko** [comment]
With swift 3, you can use `AVFileTypeQuickTimeMovie` instead of `AVFileType.mov`.
Helped me, it can actually reference to `AVFileType.mov`
