### ISSUE TITLE
Does not work with Swift 4

### ISSUE THREAD

**Issue by sasquatchgit** [zhangao0086/DKImagePickerController#388]
It says `Image Picker Controller by Swift 4.`, but doesn't really work on Swift 4. Am I missing something, or the claim isn't right?

**Comment by JettF** [comment]
It's not building for me either. I tried the 'Feature/4.0.0' branch as well. 

@zhangao0086 am I right in thinking that you are in the middle of converting the library to swift 4?

**Comment by JettF** [comment]
Fixed in #389

**Comment by zhangao0086** [comment]
Merged.
