### ISSUE TITLE
SWIFT 4 issue - Type 'UIImageView' does not conform to protocol 'DisplaceableView' URGENT !!!

### ISSUE THREAD

**Issue by smartsidd** [zhangao0086/DKImagePickerController#390]
![screen shot 2017-10-13 at 12 29 18 pm](https://user-images.githubusercontent.com/1187989/31533932-3bea0dee-b012-11e7-9622-8153254f8551.png)
Please help me - its urgent - my whole project got stuck with this. 

Type 'UIImageView' does not conform to protocol 'DisplaceableView'

**Comment by zhangao0086** [comment]
Have you updated to 3.8.0?

**Comment by zhangao0086** [comment]
I think update to the latest version should be able to solve this issue.

**Comment by smartsidd** [comment]
I updated the pods still showing same error .. why ? Please help 

![screen shot 2017-10-16 at 10 41 04 am](https://user-images.githubusercontent.com/1187989/31596219-af94ef68-b25e-11e7-9c8e-dc02a2ccc0b8.png)
![screen shot 2017-10-16 at 10 41 28 am](https://user-images.githubusercontent.com/1187989/31596221-b1e41514-b25e-11e7-8de8-9c0bc3adcfdb.png)

URGENT !!!!!

**Comment by smartsidd** [comment]
I updated the pods still showing same error .. why ? Please help

[image: screen shot 2017-10-16 at 10 41 04 am]
<https://user-images.githubusercontent.com/1187989/31596219-af94ef68-b25e-11e7-9c8e-dc02a2ccc0b8.png>


[image: screen shot 2017-10-16 at 10 41 28 am]
<https://user-images.githubusercontent.com/1187989/31596221-b1e41514-b25e-11e7-8de8-9c0bc3adcfdb.png>

**Comment by zhangao0086** [comment]
Please check your `Podfile.lock` to see the actual version is used:
![image](https://user-images.githubusercontent.com/7742344/31597047-e89f850a-b20b-11e7-9ecc-573adafa3d3f.png)

**Comment by smartsidd** [comment]
![screen shot 2017-10-16 at 11 27 53 am](https://user-images.githubusercontent.com/1187989/31597265-20193f72-b265-11e7-9edf-27564950be04.png)


Its showing 3.8.1.

Please help on that.

**Comment by zhangao0086** [comment]
@smartsidd Is your main project development based on Swift4? Looks like your project settings are Swift4, but used syntax is old.

**Comment by smartsidd** [comment]
@zhangao0086 whats syntax or code to use in swift 4. please help me on that

**Comment by zhangao0086** [comment]
Can you post your `CustomGroupDetailImageCell.swift` here?

**Comment by smartsidd** [comment]
//
//  CustomGroupDetailImageCell.swift
//  CaraMaps
//
//  Created by Siddhartha DEB on 2017-04-26.
//  Copyright © 2017 Jérémy Peltier. All rights reserved.
//

import UIKit
import DKImagePickerController

class CustomGroupDetailImageCell: DKAssetGroupDetailBaseCell {
    
    class override func cellReuseIdentifier() -> String {
        return "CustomGroupDetailImageCell"
    }
    
    override init(frame: CGRect) {
        super.init(frame: frame)
        
        self.thumbnailImageView.frame = self.bounds
        self.thumbnailImageView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        self.contentView.addSubview(self.thumbnailImageView)
        
        self.checkView.frame = self.bounds
        self.checkView.autoresizingMask = [.flexibleWidth, .flexibleHeight]
        self.contentView.addSubview(self.checkView)
    }
    
    required init?(coder aDecoder: NSCoder) {
        fatalError("init(coder:) has not been implemented")
    }
    
    override var thumbnailImage: UIImage? {
        didSet {
            self.thumbnailImageView.image = self.thumbnailImage
        }
    }
    
    fileprivate lazy var thumbnailImageView: UIImageView = {
        let thumbnailImageView = UIImageView()
        thumbnailImageView.contentMode = .scaleAspectFill
        thumbnailImageView.clipsToBounds = true
        
        return thumbnailImageView
    }()
    
    fileprivate lazy var checkView: UIImageView = {
        let checkView = UIImageView(image: DKImageResource.blueTickImage())
        checkView.contentMode = .center
        
        return checkView
    }()
    
    override var isSelected: Bool {
        didSet {
            if super.isSelected {
                self.thumbnailImageView.alpha = 0.5
                self.checkView.isHidden = false
            } else {
                self.thumbnailImageView.alpha = 1
                self.checkView.isHidden = true
            }
        }
    }
    
}

**Comment by smartsidd** [comment]
Please help on that .. waiting for you response brother..,

**Comment by zhangao0086** [comment]
@smartsidd Could you share your project?

**Comment by smartsidd** [comment]
yes in your gmail. i sent. please check

**Comment by smartsidd** [comment]
Please check your zhangao0086@gmail.com - I sent dropbox link for whole project

**Comment by zhangao0086** [comment]
Hi @smartsidd This issue happens because your protocol `DisplaceableView` not compatible with Swift4. To fix this, simply rename `hidden` to `isHidden` and `func convertPoint(_ point: CGPoint, toView view: UIView?) -> CGPoint` to `func convert(_ point: CGPoint, to view: UIView?) -> CGPoint`:
```swift
public protocol DisplaceableView {

    var image: UIImage? { get }
    var bounds: CGRect { get }
    var center: CGPoint { get }
    var boundsCenter: CGPoint { get }
    var contentMode: UIViewContentMode { get }
    var isHidden: Bool { get set }

    func convert(_ point: CGPoint, to view: UIView?) -> CGPoint

}
```

The remaining questions are probably pretty simple to solve.

**Comment by zhangao0086** [comment]
You can stop the file sharing.
