### ISSUE TITLE
after taking a photo,the done button can not display all the text

### ISSUE THREAD

**Issue by cartmanguo** [zhangao0086/DKImagePickerController#394]
![wechatimg5](https://user-images.githubusercontent.com/4699162/31599510-54e5a0c6-b218-11e7-9c62-e857f52e3ecb.jpeg)
my device is iPhone6s,iOS 11.0.3
on iPad mini2 with iOS 10.3, the problem does not exist

**Comment by zhangao0086** [comment]
It's a known issue. Fixed in [0b596f98e5b880f52936581ecc33eebc4e1b12f6](https://github.com/zhangao0086/DKImagePickerController/commit/0b596f98e5b880f52936581ecc33eebc4e1b12f6#diff-0d2a3fef5ca584fe1f33baf605c025cb).
Please wait for the next release. 😃
