### ISSUE TITLE
Does not work with Swift 4

### ISSUE THREAD

**Issue by sasquatchgit** [zhangao0086/DKImagePickerController#395]
It says Image Picker Controller by Swift 4.,  but doesn't really work on Swift 4. Am I missing something, or the claim isn't right? [#388](https://github.com/zhangao0086/DKImagePickerController/issues/388)

**Comment by JettF** [comment]
@sasquatchgit I am sorry, I thought I fixed this error in my pull request. I was wrong because it's still happening to me. @zhangao0086 any idea why this might still be broken?

**Comment by zhangao0086** [comment]
Please make sure you are using Swift 4.

1. The Swift Version setting of DKImagePickerController is set to Swift 4.
2. If you have a .swift-version file under your project, make sure the content of it is "4.0".
3. Try to clean your project.

![image](https://user-images.githubusercontent.com/7742344/31002413-456a9bb2-a4b0-11e7-9a1b-ceb26f8f7801.png)

**Comment by sasquatchgit** [comment]
Still no luck
![error](https://user-images.githubusercontent.com/9585608/31701650-80cae5a6-b3ef-11e7-8bc9-63a7defbf559.png)

**Comment by zhangao0086** [comment]
What errors did you get?

**Comment by zhangao0086** [comment]
Closing this thread. Feel free to re-open if your issue is not solved.
