### ISSUE TITLE
Problem when show more than one time the picker

### ISSUE THREAD

**Issue by Casporro** [zhangao0086/DKImagePickerController#40]
I have a problem with the second and next times after first execution of picker, the problem occurs with this picker configuration:
```
let pickerController = DKImagePickerController()
pickerController.allowMultipleTypes = false
pickerController.assetType = .allPhotos
pickerController.singleSelect = true
pickerController.maxSelectableCount = 1
```
The next executions of the code increases the assets in `pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in` with the previous asset or assets...

**Comment by Casporro** [comment]
If in the third time I open the picker the code of `pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in` executes three times first with 3 assets, second with 2 assets and finally with 1 asset. This is the expected behaviour? How can I do if I want only 1 asset at close of the picker?

**Comment by zhangao0086** [comment]
Hi @Casporro 
Thanks for your feedback!!! But I cannot reproduce it... Could you provide more info about that strange behavior? I'll appreciate if you send me your demo project if possible...

**Comment by Casporro** [comment]
I have two UIImageView with two UITapGestureRecognizer with the same selector and the code of my first comment inside the selector function

**Comment by Casporro** [comment]
In the last update seems to work well, but I have to test it better.

**Comment by zhangao0086** [comment]
@Casporro 
Please let me know if that works :)

**Comment by Casporro** [comment]
Seems works like a charm... Can you write the changelog for the library updates?

**Comment by zhangao0086** [comment]
Yes, I'll add it :)
