### ISSUE TITLE
How to pass the images in assests array to an api as post

### ISSUE THREAD

**Issue by Geethanjali14** [zhangao0086/DKImagePickerController#403]
Hi, I would like to pass the images to an api request as post.I know the images are stored in assets as a DKAsset Array but i dont know how to fetch whole image itself to the reguest. I want to pass the image name, type, size and image itself.
Thanks in advance.

**Comment by paramu** [comment]
Just iterate through array of DKAssets and fetch the image by using following method defined in DKAsset Class

public func fetchOriginalImage(_ sync: Bool, completeBlock: @escaping (_ image: UIImage?, _ info: [AnyHashable: Any]?) -> Void) {}

You can able to get the image name from info as shown in below

let url = info?["PHImageFileURLKey"] as? URL {
let imageName = url.lastPathComponent

DKAsset have a var isVideo: Bool
which is used to identify video, if the dkasset is not a video type, then it is image

**Comment by Geethanjali14** [comment]
Can you please explain a little bit more. My code is as below
 ` import UIKit

   class CameraTabViewController: UIViewController,UICollectionViewDataSource, 
                   UICollectionViewDelegate{

    var pickerController: DKImagePickerController!
    
    var assets: [DKAsset]?

            override func viewDidLoad() {
        super.viewDidLoad()
        
        // Do any additional setup after loading the view.
        
    }
    
    override func didReceiveMemoryWarning() {
        super.didReceiveMemoryWarning()
        // Dispose of any resources that can be recreated.
    }
    
    @IBAction func saveCamBtn(_ sender: Any) {
        let parent = self.parent as! DiaryEntryViewController
        parent.CameraView.isHidden  = true
    }
    @IBAction func selectPhotoBtn(_ sender: Any) {
        
        let pickerController = DKImagePickerController()
        pickerController.defaultSelectedAssets = self.assets
        
        pickerController.didCancel = { ()
            print("didCancel")
        }
        
        pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
            self.updateAssets(assets: assets)
        }
        
        self.present(pickerController, animated: true)
    }
   
    
    @IBOutlet var previewView: UICollectionView!
    func collectionView(_ collectionView: UICollectionView, numberOfItemsInSection section: Int) -> Int{
        
        return self.assets?.count ?? 0
    }
    
    func collectionView(_ collectionView: UICollectionView, cellForItemAt indexPath: IndexPath) -> UICollectionViewCell {
        
        let asset = self.assets![indexPath.row]
        var cell: UICollectionViewCell?
        var imageView: UIImageView?
        if asset.isVideo {
            cell = collectionView.dequeueReusableCell(withReuseIdentifier: "CellVideo", for: indexPath)
            imageView = cell?.contentView.viewWithTag(1) as? UIImageView
        } else {
            cell = collectionView.dequeueReusableCell(withReuseIdentifier: "CellImage", for: indexPath)
            imageView = cell?.contentView.viewWithTag(1) as? UIImageView
        }
        
        if let cell = cell, let imageView = imageView {
            let layout = collectionView.collectionViewLayout as! UICollectionViewFlowLayout
            let tag = indexPath.row + 1
            cell.tag = tag
            asset.fetchImageWithSize(layout.itemSize.toPixel(), completeBlock: { image, info in
                if cell.tag == tag {
                    imageView.image = image
                }
            })
        }
        
        return cell!
        
    }
    
    func updateAssets(assets: [DKAsset]) {
        print("didSelectAssets")
        self.assets = assets
        self.previewView?.reloadData()
        
    }
   
}
`

**Comment by paramu** [comment]
Looks like you selected image from picker and showing preview in collection view. Probably ,you have to create upload button and try to upload the images. 

In your code, 
func updateAssets(assets: [DKAsset]) returns array of assets

Here, you already know how to fetch the image and showing preview in collection view 

asset.fetchImageWithSize(layout.itemSize.toPixel(), completeBlock: { image, info in
            if cell.tag == tag {
                imageView.image = image
            }

You have to convert this image to Data by using UIImageJPEGRepresentation/UIImagePNGRepresentation API

Following links may help you...

https://mobikul.com/make-multipart-request-using-alamofire-3-0-swift/
https://medium.com/@hanifsgy/alamofire-multipart-with-parameters-upload-image-from-uiimagepickercontroller-swift-a4abada24ae

**Comment by Nikiraf** [comment]
Hi,
Can you help me to get selected files as Data type. My code is working for images but I'm not sure how to work with video files.

This part is for presenting view for choosing files:

`let pickerController = DKImagePickerController()
        pickerController.sourceType = .photo
        pickerController.didSelectAssets = { (assets: [DKAsset]) in
            if assets.count > 0 {
                self.getImagesFromGalleryAndSend(assets)
            }
        }
        self.present(pickerController, animated: true) {}`

This part of code is to get image from selected files:

`func getImagesFromGalleryAndSend(_ images: [DKAsset]){
    for item in images {
        item.**fetchOriginalImageWithCompleteBlock**({ (image, info) in
        
        })
    }
}`

What method should I use to get files as Data?

**Comment by ferico55** [comment]
Hi @Nikiraf I believe you can get the raw NSData from the asset by utilising `PHImageManager` from `Photos` library which provided by default by Apple
Here's how you can use it
use `requestImageData` as documented [here](https://developer.apple.com/documentation/photos/phimagemanager/1616964-requestimage)
```
PHImageManager.default().requestImageData(for: image, options: nil) { (data, dataString, orientation, infoDictionary) in
            // make use of your data here
        }
```
or use `requestAVAsset` as documented [here](https://developer.apple.com/documentation/photos/phimagemanager/1616935-requestavasset)
```
PHImageManager.default().requestAVAsset(forVideo: originalAsset, options: nil) { (asset, audio, infoDictionary) in
            // do something with video asset and audio here
        }
```

**Comment by zhangao0086** [comment]
In 4.0 version, you can export the selected assets to the app's sandbox via `DKImageAssetExporter`.

Then it's easy to get the original data of the asset:

```swift
pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
    let asset = assets.first!
    if let url = asset.localTemporaryPath {
        if let data = NSData(contentsOf: url) {
            print(data.length)
        }
    }
}
```
For example, see [Export automatically](https://github.com/zhangao0086/DKImagePickerController#exporting-to-file).
