### ISSUE TITLE
Multiple Instances of DKImagePickerController for different asset types

### ISSUE THREAD

**Issue by sivabonigeni** [zhangao0086/DKImagePickerController#404]
Thanks for nice library, i'm facing an issue while creating separate instances for different asset types. found this reference #276 but no luck with that, DKImageManager sharedInstance is getting replaced with the last created object, is there anyway to create separate instances ? 

Thanks

**Comment by zhangao0086** [comment]
Hi @sivabonigeni  I plan to solve this in the next version. Is urgent for you?

**Comment by sivabonigeni** [comment]
Yes @zhangao0086 , it would be great if you through some steps on how to achieve these.

**Comment by snehageorge** [comment]
Hi, even I'm facing the same issue. How can  I fix this ?
Tried 
`DKImageManager.Static.instance = nil`
But gets an error 
> Type 'DKImageManager' has no member 'Static'

**Comment by zhangao0086** [comment]
Feel free to reopen it if this issue persists.
