### ISSUE TITLE
Deselection of an asset does not work

### ISSUE THREAD

**Issue by snehageorge** [zhangao0086/DKImagePickerController#405]
I tried the sample project provided, when I tried to deselect some of the images I selected, it doesn't work as expected. Please have a look on it. In some cases even normal multiple selection seems to have issues.

**Comment by ferico55** [comment]
thank you @snehageorge for reporting the issue, can you be more specific? please provide what device did you use, library version, OS version for us to investigate this issue further

**Comment by zhangao0086** [comment]
I think this issue has been fixed in this commit: https://github.com/zhangao0086/DKImagePickerController/commit/a8f4c627936215b28f48299f2ab4f19dbe879cc3 :)
