### ISSUE TITLE
Not able to implement Pagination with fetchLimit property

### ISSUE THREAD

**Issue by codedreamer46** [zhangao0086/DKImagePickerController#409]
Thanks for the Library, If picker contains large number of Images, it's taking time to load all images, it would be great if we implement pagination to fetch the images, but not able to use the fetchLimit property.

Thanks

**Comment by storix** [comment]
Actually, Photos framework uses a different concept instead of pagination. Check out the [docs](https://developer.apple.com/documentation/photos/phfetchresult):

> PHFetchResult object dynamically loads its contents from the Photos library as needed, providing optimal performance even when handling a large number of results

As a result, `fetchLimit` property cannot be used for pagination. It's just a hard limit which you must know beforehand.

**Comment by zhangao0086** [comment]
Closing this thread...
