### ISSUE TITLE
app getting crash 

### ISSUE THREAD

**Issue by sidshah13** [zhangao0086/DKImagePickerController#410]
app getting crash on this line

    getImageManager().groupDataManager.assetGroupTypes = self.assetGroupTypes
in file DKImagePickerController

**Comment by jyounus** [comment]
I have the same problem. 

I added the pod to my existing project and just try to present the DKImagePickerController, then it crashes. I tried version 3.8.1 and the Feature/4.0.0 branch, both cause this crash. 

Anyone have a solution?

**Comment by jyounus** [comment]
I changed libs and was having a similar crash. I realised that my permissions inside the Info.plist file were incorrect. Make sure you have NSCameraUsageDescription and NSPhotoLibraryUsageDescription and it should work.

**Comment by zhangao0086** [comment]
This issue has been fixed in `4.0` version.

**Comment by sidshah13** [comment]
can you provide me pod?

**Comment by zhangao0086** [comment]
@sidshah13  Try this:
```
pod 'DKImagePickerController', '~> 4.0.0-Beta'
```
