### ISSUE TITLE
Crash in  DKImageManager.fetchImageDataForAsset

### ISSUE THREAD

**Issue by iad24** [zhangao0086/DKImagePickerController#411]
#0. Crashed: com.apple.main-thread
DKImageManager.fetchImageDataForAsset(DKAsset, options : PHImageRequestOptions?, completeBlock : (Data?, [AnyHashable : Any]?) -> ()) -> () (DKImageManager.swift:131)

It only happens once. You might want to know that this part crashed for some reason.
Im using v3.5.7
Please see attached file for the whole logs
[crash.txt](https://github.com/zhangao0086/DKImagePickerController/files/1525707/crash.txt)

**Comment by zhangao0086** [comment]
Thanks!

**Comment by zhangao0086** [comment]
This issue has been fixed in `4.0` version.

**Comment by iad24** [comment]
@zhangao0086 wow. thanks

**Comment by iad24** [comment]
Hmmm. Why so many dependencies now?
CLImageEditor
DKCamera
DKPhotoGallery
FLAnimatedImage
SDWebImage

**Comment by zhangao0086** [comment]
Hi @iad24 In previous versions, this library provided extended functionality by integrating the source code of the dependent libraries. Starting from 4.0, it manages dependent libraries through CocoaPods.
https://github.com/zhangao0086/DKImagePickerController#subspecs
