### ISSUE TITLE
Custom Camera Permissions

### ISSUE THREAD

**Issue by Chefda** [zhangao0086/DKImagePickerController#412]
Hello,

I check camera permission in viewDidLoad method in CustomCamera. I open dialog to go to settings if user denied camera permission.

But when user slide to record video, i need to check microphone permission too. And i can not detect when user slide to record video. UIImagePickerControllerDelegate has no delegate method for this can you have any idea?

**Comment by zhangao0086** [comment]
Feel free to reopen it if the issue persists.
