### ISSUE TITLE
Unresolved identifier 'DKImagePickerController'?

### ISSUE THREAD

**Issue by wtj123** [zhangao0086/DKImagePickerController#413]
After I finished the installation using CocoaPods, I got the  following error.

Use of unresolved identifier 'DKImagePickerController'?

Please help me with that issue. Thanks!

**Comment by acjh** [comment]
Duplicate of #268 

> Add `import DKImagePickerController` to the top of your file and make sure 'Build Active Architecture Only' is set to no for the DKImagePickerController target in Pods

**Comment by wtj123** [comment]
Hi acjh,
Thanks a lot for your help. Now I can use this library.
