### ISSUE TITLE
App Crashing while selecting Image stored in iCloud

### ISSUE THREAD

**Issue by sivabonigeni** [zhangao0086/DKImagePickerController#414]
@zhangao0086 Found Crash while selecting an image stored in iCloud, looping at function fetchImageDataForAsset to download the image from iCloud.

Looping Function: fetchImageDataForAsset(_ asset: DKAsset, options: PHImageRequestOptions?, completeBlock: @escaping (_ data: Data?, _ info: [AnyHashable: Any]?) -> Void)
Error Code: Failed to load image data for asset <PHAsset: 0x104c92590> with format 9999

Steps to Reproduce:
1.Enable Optimise iPhone Storage in Settings>Photos.
2.Now In Photos app images will show exclamation mark at bottom
3.Select the Image that contains exclamation mark then fails to load image and gives above Error Code after few iterations app crashes.

**Comment by Gregga16** [comment]
Did you solve this? @sivabonigeni @zhangao0086

**Comment by zhangao0086** [comment]
Hi @sivabonigeni @Gregga16 This issue has been fixed in 4.0.0 beta branch, it has not yet been officially released, but you can manually switch to 4.0.0 branch:

pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Feature/4.0.0'

**Comment by zhangao0086** [comment]
This issue has been fixed in `4.0` version.

**Comment by Chefda** [comment]
Hi @zhangao0086 what was the problem? Can you explain please, i could not find revision in commits.
