### ISSUE TITLE
How to get most recent changes with cocoapods?

### ISSUE THREAD

**Issue by lesiva** [zhangao0086/DKImagePickerController#415]
I'm experiencing a crash when the user has restricted permission to the camera.

A fix for this was pushed about 3 weeks ago, but I'm having difficulty grabbing the fix by doing a pod update. What is the fix for this? Is it as easy as bumping up the version number in the podspec?

**Comment by acjh** [comment]
Do you mean #407? Try this in your Podfile:

```shell
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'master'
```

**Comment by lesiva** [comment]
@acjh With that setup, as soon as a change is merged to the repo I'll get it in my app, right?

Looking for a more stable experience by specifying a pod version if possible

**Comment by acjh** [comment]
You did ask *How to get most recent changes*. Yes, you can specify a `:commit` if you prefer.
