### ISSUE TITLE
九宫格

### ISSUE THREAD

**Issue by liupeng826** [zhangao0086/DKImagePickerController#418]
您好，项目正在使用您的控件，非常感谢。
您能增加一个九宫格带删除按钮的imageView功能吗？类似
https://github.com/Assuner-Lee/LPDQuoteImagesView

**Comment by zhangao0086** [comment]
您好，感谢您的建议！

这个功能不在该库的规划内。原因在于带删除按钮的 imageView 属于外部预览的一部分，而该库是作为它的数据源而存在的。在 4.0 版本中，您可以关闭该库的自动导出功能（默认），然后把 DKAsset 作为 Model 去创建带删除按钮的 imageView，此时 DKAsset 还没有导出到 App 的沙盒中，只有当用户点提交的时候，手动通过 `DKImageAssetExporter` 将选定的 DKAsset 导出到 App 的沙盒，然后就能将已导出的数据上传到服务器了。
