### ISSUE TITLE
Rotations and Annotations from the camera roll are not preserved in assets

### ISSUE THREAD

**Issue by lesiva** [zhangao0086/DKImagePickerController#429]
In the image picker, the photos correctly show rotations/annotations. In the asset that is returned, the rotations and annotations are not included in the photo. 

This also depends on the phone. An iPhone 6 was preserving the rotation (but still not preserving the drawings) while an iPhone X was not preserving any of it.

**Repro:**
Take a photo using the Camera app. Rotate it or draw on it.
Get the asset in your app using DKImagePickerController.
Notice that the rotation is not respected, annotations are removed.

**Comment by jacobo360** [comment]
+1!!!

**Comment by zhangao0086** [comment]
I cannot reproduce it with iPhone X... 
Could you post your related code or sample project here?

**Comment by zhangao0086** [comment]
Closing this thread...
