### ISSUE TITLE
iPhone X Custom camera Layout issues

### ISSUE THREAD

**Issue by hardikdevios** [zhangao0086/DKImagePickerController#431]
![img_b746dd8ff711-1](https://user-images.githubusercontent.com/6657591/35726264-4aabd8b0-082a-11e8-9440-df8f3e8b6489.jpeg)

**Comment by zhangao0086** [comment]
Please check the 4.0.0 branch. If you're using CocoaPods just try this:
```
pod 'DKImagePickerController', '~> 4.0.0-Beta'
```

**Comment by applepeopletsai** [comment]
Hi, I already use 4.0.0-Beta version, but still have layout issue in iPhoneX after press take picture button
![img_0005](https://user-images.githubusercontent.com/19483534/36882900-796cd49a-1e11-11e8-89b7-40e784cf41a1.png)
Could you solve the problem? 
thanks!

**Comment by zhangao0086** [comment]
Hi @applepeopletsai Does this issue still exist in `develop` branch?

**Comment by applepeopletsai** [comment]
Hi @zhangao0086  Yes, it still exist in develop branch.

**Comment by lawicko** [comment]
A quickfix that I use in my project is to return false from prefersStatusBarHidden method in the DKCamera.swift. The better solution would be something like this:
https://stackoverflow.com/questions/46487808/iphone-x-hidden-status-bar-pushes-navigation-bar-upwards

**Comment by zhangao0086** [comment]
Fixed. Closing this thread...
