### ISSUE TITLE
After capturing a photo in camera and automatically back to photos view, "..." is on the bar instead of "选择(1)"

### ISSUE THREAD

**Issue by erinsnow** [zhangao0086/DKImagePickerController#432]
After capturing a photo in camera and automatically back to photos view, "..." is on the bar on the right top instead of "选择(1)".

Only Chinese situation has been tested.

**Comment by zhangao0086** [comment]
Hi @erinsnow Firstly, sorry for the late response.

This issue only appears on iOS 11. I think the latest version of the picker has been fixed this issue. What's the version of picker for you using?

**Comment by erinsnow** [comment]
Hi, I updated my DK to the newest automatically which is the 3.8.1 version. And my iOS version is 11.
It's not fixed by my new test.
Haven't tested for DK 4.0-beta.

**Comment by kirti0525** [comment]
Hi, I am using the version 3.5.7 and the issue exists in English version also, if I choose photos from gallery then "SELECT(1)" text is showing fine , but when I capture a photo from camera, after that "SE...(2)" , Select is showing like this. It is truncating. Please help me with this

**Comment by zhangao0086** [comment]
@kirti0525  Could you try the 4.0.0 version?

```
pod 'DKImagePickerController', '~> 4.0.0-beta'
```

**Comment by kirti0525** [comment]
Its working absolutely fine with this new version. Thank you so much for your co-operation.
