### ISSUE TITLE
File: DKAssetGroupDetailVC #line: 136 "self.selectedGroupId!" seems not safe.

### ISSUE THREAD

**Issue by erinsnow** [zhangao0086/DKImagePickerController#433]
After reviewing a few lines of code, I didn't find any line to assure the selectedGroupId to be not nill all the time. The groupId upside in #line 125 & #line 130 can be nil as well as selectedGroupId, I suppose.

Crash happens in my Fabric report about this line, though I don't know how can a user doesn't have a group to be fetched.
Hope some code for safety dealing with the Optional selectedGroupId.
Thank you.

**Comment by zhangao0086** [comment]
Please check the 4.0.0 version, if you're using CocoaPods just try this:

```
pod 'DKImagePickerController', '~> 4.0.0-Beta'
```

**Comment by erinsnow** [comment]
I'm using the 3.8.1 version.
Tried to update to DK 4.0.0-Beta. However, there are some changes when I init one and set some variables which were not introduced in the description. 
Sorry for not take some time to look inside and back to the 3.8.1 without having a test about the issue. 😂
Someday as soon as I came across the crash again I'll give a report.
Thank you for your reply and coding.

**Comment by zhangao0086** [comment]
Fixed.
