### ISSUE TITLE
How to set footer in DKImagePickerController like below image

### ISSUE THREAD

**Issue by Bhavesh5291** [zhangao0086/DKImagePickerController#435]

**Comment by Bhavesh5291** [comment]
[
![screenshot6](https://user-images.githubusercontent.com/36148560/35843622-27e010b4-0b2f-11e8-8504-aea4f2125418.png)
](url)

**Comment by Bhavesh5291** [comment]
[
![screenshot6](https://user-images.githubusercontent.com/36148560/35843683-7bdba804-0b2f-11e8-9332-8656d8b63741.png)
](url)

**Comment by katerynasytnykiOS** [comment]
@Bhavesh5291 I think there's a pretty similar footer working in the demo project when you click on "Custom UI" choice, which corresponds to CustomUIDelegate.swift
