### ISSUE TITLE
How to get selected image and video url to post server.

### ISSUE THREAD

**Issue by vivek1608** [zhangao0086/DKImagePickerController#439]
I want this in url formet ---- 
Still i got image and video like this  after assets print ---DKImagePickerController.DKAsset: 0x6000004ad260 

func showImagePicker() {

        
        if let assets = self.assets {
            pickerController.select(assets: assets)
        }
        pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
             self.updateAssets(assets: assets)
            print("didSelectAssets")
            print(assets)
}
please help me

**Comment by zhangao0086** [comment]
Please refer to [exporting-to-file](https://github.com/zhangao0086/DKImagePickerController#exporting-to-file).
