### ISSUE TITLE
Suggestion, Add "Cancel" button on picker

### ISSUE THREAD

**Issue by vinod1988** [zhangao0086/DKImagePickerController#44]
Please add the cancel button on picker, show that user can dismiss the picker for example by mistake user open the picker and  don't want to select the image. or not want to select any image then he/she able to dismiss the picker on cancel button click. I know the done button click dismiss. But as per user experience we need add the "cancel" button.

**Comment by zhangao0086** [comment]
@vinod1988 
Thanks for your useful suggestion! I think I'll add the "cancel" button via an optional property :)

**Comment by zhangao0086** [comment]
Check the 2.4.1 branch:https://github.com/zhangao0086/DKImagePickerController/commit/63df02882b88e851c1ecbf71a6ea98084ee5347d

**Comment by arjanirh** [comment]
Hello. I set showsCancelButton to true, but the button shows not show. I'm using the obj-c API.
Thanks!
