### ISSUE TITLE
open the camera screen directly

### ISSUE THREAD

**Issue by iad24** [zhangao0086/DKImagePickerController#443]
Im using v3.5.7, 

1. Is it possible to just open the camera screen directly and can get access to the photo taken?
So it means it will bypass the image selection screen.

2. Is it possible to add my custom views or overlays to the camera screen?

**Comment by zhangao0086** [comment]
> Is it possible to just open the camera screen directly and can get access to the photo taken?
So it means it will bypass the image selection screen.

Yes. Just set `sourceType` to `camera`.

> Is it possible to add my custom views or overlays to the camera screen?

Make a class that implements `DKImagePickerControllerUIDelegate` then returns a custom camera in 
```swift
func imagePickerControllerCreateCamera(_ imagePickerController: DKImagePickerController) -> UIViewController
```

**Comment by iad24** [comment]
Thanks. I can now open the camera directly. But when i capture a photo, it just snaps and does not show the preview taken photo. It just stays there. Then if I click the flash icon, the app crashes.

**Comment by zhangao0086** [comment]
Could you provide me the crash info?

**Comment by iad24** [comment]
THe crash happens when you set the sourceType to camera and set the UIDelegate to this:

**Comment by iad24** [comment]
But I managed to do a workaround to avoid the crash. But right now, I am subclassing DKImagePickerController to create my own custom camera. After it captures a photo, i want to display the preview of the photo taken on that view controller it self. Problem is after it takes the photo, it dismiss the view controller.

![screen shot 2018-03-01 at 3 09 38 pm](https://user-images.githubusercontent.com/15226261/36831404-994776bc-1d62-11e8-83bf-0466a92258b9.png)

Possible to have boolean field to enable/disable auto dismissal after taking the photo?

**Comment by zhangao0086** [comment]
Closing this thread...
