### ISSUE TITLE
Some Question

### ISSUE THREAD

**Issue by applepeopletsai** [zhangao0086/DKImagePickerController#444]
First, thanks the library, it's useful for me!

My question is : 
1. can we distinguish the MaxSelectableCount by image and video?
The use case is : when user select one video, they can't select more video, but image is not limited.
In other words, user can select three images & one video, but can not select three images & two video
2. Is possible that when capture photo, directly back to the photo list not go to image editor?

**Comment by ahmetalsan** [comment]
Remove PhotoEditor from specs

**Comment by applepeopletsai** [comment]
@ahmetalsan Thanks for your reply, but i have no idea to remove PhotoEditor, could you tell more detail?
I use the 'CustomCameraExtension' class from demo, and there is my code:

let pickerController = DKImagePickerController()
        pickerController.UIDelegate = CustomUIDelegate()
        DKImageExtensionController.registerExtension(extensionClass: CustomCameraExtension.self, for: .camera)
        pickerController.didSelectAssets = { (assets: [DKAsset]) in
            print(assets)
        }
        self.present(pickerController, animated: true, completion:nil)

**Comment by applepeopletsai** [comment]
@zhangao0086 哈囉版主大大
如果您有看到的話麻煩回覆一下唷
非常感謝您

**Comment by zhangao0086** [comment]
很抱歉回复晚了... 最近真的比较忙... 不好意思...

**Comment by applepeopletsai** [comment]
@zhangao0086 非常感謝您的回覆
剛剛測試 第二個問題已經解決
但是第一個問題 canSelect 是public方法 沒有辦法覆寫
是我會錯意了嗎 
抱歉剛寫程式不久 很多地方還需要指教 😂

**Comment by zhangao0086** [comment]
Hi @applepeopletsai 我确实忽略了 `canSelect` 不是 `open` 的问题，下次更新的时候，我会把 `canSelect` 和其他一些影响流程的方法标记为 `open`，

**Comment by zhangao0086** [comment]
`develop` 分支已经更新了

**Comment by applepeopletsai** [comment]
@zhangao0086  太棒了！！ 真的非常感謝您的協助！！

**Comment by applepeopletsai** [comment]
Hi, @zhangao0086 
剛剛在繼承DKImagePickerController有點小問題
應該類似於[https://github.com/zhangao0086/DKImagePickerController/issues/445](url)所提問的問題

我的代碼如下

原先直接使用DKImagePickerController
![image](https://user-images.githubusercontent.com/19483534/37132349-444fc388-22c8-11e8-9d77-65c6192e77a0.png)

繼承DKImagePickerController的class
![image](https://user-images.githubusercontent.com/19483534/37132320-2d6a2780-22c8-11e8-87b0-271461166e7a.png)

由DKImagePickerController改成我自己的class
![image](https://user-images.githubusercontent.com/19483534/37132311-253e960e-22c8-11e8-9e83-4c5e03302e7a.png)

是不是我哪裡有遺漏的呢?

**Comment by zhangao0086** [comment]
已更新 `develop` 分支

**Comment by applepeopletsai** [comment]
@zhangao0086 大神，非常感謝您的協助
您寫的這個工具非常的好用
希望可以繼續維護 👍

**Comment by zhangao0086** [comment]
非常感谢你的支持 @applepeopletsai
