### ISSUE TITLE
DKImagePickerController subclassing

### ISSUE THREAD

**Issue by VGudenko** [zhangao0086/DKImagePickerController#445]
Hello,

I'm trying to subclass DKImagePickerController to override some methods.
Here is a problem
DKImagePickerController has these initializers:

public convenience init()
public convenience init(groupDataManager: DKImageGroupDataManager)

private override init(rootViewController: UIViewController)
private override init(nibName nibNameOrNil: String?, bundle nibBundleOrNil: Bundle?)
required public init?(coder aDecoder: NSCoder){
        fatalError("init(coder:) has not been implemented")
}

How to make a correct init in my subclass if native designated initializers are private and I cant use the convenience in my subclass init methods?

**Comment by zhangao0086** [comment]
Hi @VGudenko I'm sorry for the late response...

This issue was fixed in the latest `develop` branch. Thanks!
