### ISSUE TITLE
Use CustomUIDelegate, DKImagePickerController will nil 

### ISSUE THREAD

**Issue by applepeopletsai** [zhangao0086/DKImagePickerController#447]
@zhangao0086 哈囉, 剛剛測試有發現一個問題
我使用了CustomUIDelegate，並只覆寫了imagePickerControllerCollectionCameraCell這個方法
因為我要可以讓使用者選完照片後，如果再次選擇照片會將上一次選擇的照片預選
所以我在方法裡有呼叫select方法將上一次選擇的照片傳進去
代碼如下
![image](https://user-images.githubusercontent.com/19483534/37193460-fdee4ca6-23a4-11e8-98f0-de9eb1ae21fc.png)

在第二次選擇照片會有以下錯誤
![image](https://user-images.githubusercontent.com/19483534/37193397-a2859c02-23a4-11e8-96b2-e6228e134192.png)

所以我增加了一行代碼
pickerController.UIDelegate.imagePickerController = pickerController
就可以正常執行了

不知道這是不是bug?

**Comment by zhangao0086** [comment]
Hi,  你的 `CustomUIDelegate` 中有以下方法并且它有被执行到吗？

```swift
override open func prepareLayout(_ imagePickerController: DKImagePickerController, vc: UIViewController) {
    self.imagePickerController = imagePickerController
}
```

**Comment by applepeopletsai** [comment]
@zhangao0086 Hi, 加了之後還是一樣，代碼如下
![image](https://user-images.githubusercontent.com/19483534/37270626-70eb44ea-260a-11e8-831e-4c22ebef4b71.png)

我有下斷點在prepareLayout方法裡，第一次點擊有進來此function，選擇照片後dismiss
第二次點擊時，沒有進入prepareLayout而是直接crash

我發現原因可能是因為我在第二次點擊時有把前一次選擇的照片帶入
![image](https://user-images.githubusercontent.com/19483534/37270773-12bca2b4-260b-11e8-984c-e3b408de06bc.png)

因而觸發didSelectAssets方法
![image](https://user-images.githubusercontent.com/19483534/37270797-24ca3bec-260b-11e8-8593-02056e947b0b.png)

所以導致在還沒呼叫到prepareLayout方法時就先執行createDoneButtonIfNeeded方法導致crash

以上，提供您參考

**Comment by zhangao0086** [comment]
非常感谢你的帮助和耐心!!!

这个问题刚刚在这次提交中修复了：
https://github.com/zhangao0086/DKImagePickerController/commit/1dc2513705c4eb82d00406763d88cb8943ed2c63
