### ISSUE TITLE
LongPress issue

### ISSUE THREAD

**Issue by applepeopletsai** [zhangao0086/DKImagePickerController#448]
Hi, @zhangao0086 , 當選擇一張照片後，長壓進入預覽，右上角圓圈的layout會跑版，如下
![image](https://user-images.githubusercontent.com/19483534/37271900-d2cd2eda-260f-11e8-94ed-1d366a572c9c.png)

左右滑動後就會正常顯示，如下
![image](https://user-images.githubusercontent.com/19483534/37272000-36521ace-2610-11e8-8aba-29825eb09c9a.png)

請問這個有辦法解嗎?

**Comment by zhangao0086** [comment]
Fixed.
