### ISSUE TITLE
Uploading duplicate images from camera roll

### ISSUE THREAD

**Issue by ghost** [zhangao0086/DKImagePickerController#449]
Hello, I've been using this pod for a year now and up until recently, multiple images that I attempt to upload to my app from the camera roll are showing up in duplicates of one of the images. ie. I chooses three images from my album, the third image is uploaded three times. I have debugged extensively and used different methods to access the data of the images. I used version 3.8.1 on both swift 3.2 and 4 and your latest beta version.
 I'll be details as I can on what I used 
swift 3.2 and 4, DK version 4.0.0 beta2

`                 
         for asset in assets { 
                          //loop header is the same for the rest 
                asset.fetchOriginalImage(completeBlock: { 
                    (image, info) in
                            let newImg = self.resizeImage(image!, newWidth: self.view.frame.width) //changes size
                            let jpegData = UIImageJPEGRepresentation(newImg, 1)
                            
                            do{
                                try jpegData?.write(to: self.imgPathUrl, options: .atomic)
                            }catch{
                                print("Write image to url failed ")
                            }
                            self.arrSelectedGalleryMedia.add(self.imgPathUrl)
                            if self.arrSelectedGalleryMedia.count >= assets.count{
                                SharedClass.sharedInstance.hideLoader()
                                self.addMedia() //add images
                            }
                   })
                }
`

`              asset.fetchImageData(completeBlock: {
                   (data,info) in
                            do{
                                try data?.write(to: self.imgPathUrl, options: .atomic)
                            }catch{
                                print("Error\(error)")
                            }
                            self.arrSelectedGalleryMedia.add(self.imgPathUrl)
                            if self.arrSelectedGalleryMedia.count >= assets.count{
                                SharedClass.sharedInstance.hideLoader()
                                self.addMedia() //add images
                            }
                   })
`
Swift 3.2 and 4, DK version 3.8.1

`                    
                  asset.fetchOriginalImageWithCompleteBlock({ 
                     (image, info)  in
                            let newImg = self.resizeImage(image!, newWidth: self.view.frame.width)
                            let jpegData = UIImageJPEGRepresentation(newImg, 1)

                           do{
                               try jpegData?.write(to: self.imgPathUrl, options: .atomic)
                            }catch{
                                print("Write image to url failed ")
                            }
                            self.arrSelectedGalleryMedia.add(self.imgPathUrl)
                            if self.arrSelectedGalleryMedia.count >= assets.count{
                                SharedClass.sharedInstance.hideLoader()
                                self.addMedia() //add images
                            }
                        })

`
I used another function in 3.8.1 that write the data to a temporary URL directly and I would store the link in an array. 

The issue seems to be coming from **getImageDataManager().fetchImageData** 
Like in the example I mentioned I can see the assets have been collected but as I loop through each assets, **it skips the first two and loops on the third image three times**. 
Any assistance would be greatly appreciated...

**Comment by knjeri** [comment]
https://stackoverflow.com/q/49575341/8501423 I posted the question on stack over flow too. you can see my code better there

**Comment by zhangao0086** [comment]
See also: `DKImageAssetExporter`
