### ISSUE TITLE
Error to unwrap a nill value in DKCamera.swift

### ISSUE THREAD

**Issue by BrunoCerberus** [zhangao0086/DKImagePickerController#455]
<img width="1599" alt="screen shot 2018-04-11 at 10 19 45" src="https://user-images.githubusercontent.com/10541956/38627786-29cca5ac-3d86-11e8-8aa4-aff2591ff9d8.png">

This happens when I block the permission to access my camera and try to access de camera again, this line of code can be found on line 398 in DKCamera.swift

**Comment by BrunoCerberus** [comment]
I solved the problem just putting an "if let" before frontInput and removing the force unwrap from frontInput

**Comment by lucasromanomr** [comment]
https://github.com/zhangao0086/DKImagePickerController/pull/456

**Comment by zhangao0086** [comment]
Thanks!
