### ISSUE TITLE
Asset Type Bug ?

### ISSUE THREAD

**Issue by emresa37** [zhangao0086/DKImagePickerController#458]
I'm trying to use two separate DKImagePickerController in my project. One of them for video and a
other one for pictures.
Their assets types like

imagePickerController.assetType = .allPhotos 
videoPickerController.assetType = .allVideos 

It looks like work but assetType always stuck on first used one. I mean if I firstly choose video picker the other one's asset type also become a video. Or if I choose picture first, the other one's assetType stuck on photos.

Is it possible or definitely am I doing something wrong?

**Comment by smzranz** [comment]
i too have this issue.

**Comment by zhangao0086** [comment]
Try this:
```
pod 'DKImagePickerController', '~> 4.0.0-Beta'
```
