### ISSUE TITLE
How to  UIImage  convert into DKAsset ,How to video temp url into DKAsset

### ISSUE THREAD

**Issue by testingraahul** [zhangao0086/DKImagePickerController#462]
How to  UIImage  convert into DKAsset
How to video temp url into DKAsset

i mean i want to create DKasset  because i edited image and video and i have only video url and uiimage ,,,,i want to make DKAsset...

   var selectedAssets : [DKAsset]!
    var pickedAssets : DKAsset!

**Comment by zhangao0086** [comment]
Do you have PHObject's localIdentifier?

**Comment by testingraahul** [comment]
I successful done my task. thanku

**Comment by zhangao0086** [comment]
Closing this thread :)

**Comment by testingraahul** [comment]
hi, JonathanCockfield actually I change the own programming structure.
 I change all DKAsset into PHAsset and all the task perform on PHAsset array.

var selectedAssets : [DKAsset]!
//change all DKAsset into PHAsset loo

for asset in self.selectedAssets {
            let value =  asset.originalAsset
            self.arrGallery.append(value!)
        }
//url to phasset
        let asset = AVAsset(url: editURL)

**Comment by sabujdoodle** [comment]
> hi, JonathanCockfield actually I change the own programming structure.
> I change all DKAsset into PHAsset and all the task perform on PHAsset array.
> 
> var selectedAssets : [DKAsset]!
> //change all DKAsset into PHAsset loo
> 
> for asset in self.selectedAssets {
> let value = asset.originalAsset
> self.arrGallery.append(value!)
> }
> //url to phasset
> let asset = AVAsset(url: editURL)

testingraahul, can you please share the code with me? i am facing the same problem, where i need to convert image /video from data to DKAsset. it would be great help . Thanks in Advance

**Comment by testingraahul** [comment]
//uselet dkasset  = self.selectedAssets[0] //array of Dkaasetlet asset =  dkasset.originalAssetself.previewImage.image = self.getAssetImage(asset: asset!)

//function


//get Asset Image    func getAssetImage(asset: PHAsset) -> UIImage {        let manager = PHImageManager.default()        let option = PHImageRequestOptions()        var thumbnail = UIImage()        option.isSynchronous = true        manager.requestImage(for: asset, targetSize: PHImageManagerMaximumSize, contentMode: .aspectFill, options: option, resultHandler: {(result, info)->Void in            guard let result = result else{                return            }            thumbnail = result        })        return thumbnail    }

**Comment by testingraahul** [comment]
> > hi, JonathanCockfield actually I change the own programming structure.
> > I change all DKAsset into PHAsset and all the task perform on PHAsset array.
> > var selectedAssets : [DKAsset]!
> > //change all DKAsset into PHAsset loo
> > for asset in self.selectedAssets {
> > let value = asset.originalAsset
> > self.arrGallery.append(value!)
> > }
> > //url to phasset
> > let asset = AVAsset(url: editURL)
> 
> testingraahul, can you please share the code with me? i am facing the same problem, where i need to convert image /video from data to DKAsset. it would be great help . Thanks in Advance

`//get Asset Image
    func getAssetImage(asset: PHAsset) -> UIImage {
        let manager = PHImageManager.default()
        let option = PHImageRequestOptions()
        var thumbnail = UIImage()
        option.isSynchronous = true
        manager.requestImage(for: asset, targetSize: PHImageManagerMaximumSize, contentMode: .aspectFill, options: option, resultHandler: {(result, info)->Void in
            guard let result = result else{
                return
            }
            thumbnail = result
        })
        return thumbnail
    }`
    
    //use this function
    
    var selectedAssets : [DKAsset]! //array of dkAssests

        let dkasset  = self.selectedAssets[0]
        let asset =  dkasset.originalAsset // get asset
        self.previewImage.image = self.getAssetImage(asset: asset!)
