### ISSUE TITLE
App crashing when setting delegate

### ISSUE THREAD

**Issue by jprossardalia** [zhangao0086/DKImagePickerController#463]
Hi,
I'm using the below code to call the library. When I assign the UIDelgate I get EXC_BAD_ACCESS in DKImagePickerController at line 180

`DKImagePickerController *pickerController = [DKImagePickerController new];
    pickerController.assetType = DKImagePickerControllerAssetTypeAllAssets;
    pickerController.UIDelegate = self;
    pickerController.showsCancelButton = NO;
    pickerController.showsEmptyAlbums = YES;
    pickerController.allowMultipleTypes = YES;
    pickerController.sourceType = DKImagePickerControllerSourceTypeBoth;`

If I don't assign the UIDelegate then the imagepickerview does open but no delegate function are called.
Thanks.

**Comment by zhangao0086** [comment]
Hi @jprossardalia Does your `self` is subclass of `DKImagePickerControllerBaseUIDelegate`?
