### ISSUE TITLE
選擇相簿相關問題

### ISSUE THREAD

**Issue by applepeopletsai** [zhangao0086/DKImagePickerController#468]
哈囉, @zhangao0086 
有兩個問題想請教您
1. 要怎麼樣不顯示預設的"喜好相簿"呢?因為裡面是空的如下圖
![img_2804](https://user-images.githubusercontent.com/19483534/39797387-68074098-538e-11e8-8f0e-0a01cf017e66.png)

2. 在iPhone的照片中，有將照片做很多分類，比如說自拍、螢幕快照等等的相簿，但好像不會出現在選單裡面，只有自己新增的相簿會在選項中，如上圖，只有我自定義的qqq相簿，這樣是正常的嗎?

麻煩您解惑了，感謝~

**Comment by zhangao0086** [comment]
你好，我想先确认下："喜好相簿"在 iOS 原生的相册 app 中，是否也是空的呢？

其次，不管是要隐藏"喜好相簿"还是显示"自拍"，都可以通过 `DKImageGroupDataManagerConfiguration` 的 `assetGroupTypes` 来控制：

```swift
/// The types of PHAssetCollection to display in the picker.
public var assetGroupTypes: [PHAssetCollectionSubtype] = [
    .smartAlbumUserLibrary,
    .smartAlbumFavorites,
    .albumRegular
]
```

**Comment by zhangao0086** [comment]
嗯，any 会显示所有的相册，而 .allPhotos 会过滤掉相册中的影片，这样就会导致有些只包含影片的空相册显示出来，你可以把空相册隐藏掉：

```swift
/// Set the showsEmptyAlbums to specify whether or not the empty albums is shown in the picker.
@objc public var showsEmptyAlbums = true
```

**Comment by applepeopletsai** [comment]
我照您說的，將showsEmptyAlbums設為false，但出現了奇怪現象，如下圖

![img_2806](https://user-images.githubusercontent.com/19483534/39800821-bad5a794-539b-11e8-8a5c-50315709c005.png)

他重複顯示一次了，可能是在改變屬性後並沒有將原先的選項刪除
這問題有辦法解決嗎
麻煩您了 :)

**Comment by zhangao0086** [comment]
啊... 这是一个 Bug 🐛 我刚刚在 develop 上修复它了 😢 
你可以通过这种方式获取到 develop 上的更新：
```
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'develop'
```

不过有一点要注意：用 any 是不保证相册顺序的

**Comment by applepeopletsai** [comment]
太棒了!!!
真的是非常感謝您～～
謝謝 @zhangao0086 大大 😄
