### ISSUE TITLE
Update AssetsLibrary to Photos framework, deprecated

### ISSUE THREAD

**Issue by obstructer** [zhangao0086/DKImagePickerController#47]
Unfortunately I'm getting warnings left and right about how the AssetsLibrary is deprecated and certain methods need to be updated to the Photos framework; they all have to do with the originalAsset variable in the DKAsset class. Please fix this, I would but I'm new to iOS development :/

**Comment by zhangao0086** [comment]
I will release the 3.0.0 with Photos framework.[develop](https://github.com/zhangao0086/DKImagePickerController/tree/develop)
