### ISSUE TITLE
customLocalizationBlock in obj-c

### ISSUE THREAD

**Issue by ahmetalsan** [zhangao0086/DKImagePickerController#474]
Anyone can please convert it to obj-c syntax please?

DKImagePickerControllerResource.customLocalizationBlock = { title in
    if title == "picker.select.title" {
        return "Test(%@)"
    } else {
        return nil
    }
}

**Comment by bochitan** [comment]
Used and build error, No "customLocalizationBlock" property on V4.0.2
How to fix it?

**Comment by zhangao0086** [comment]
Hi @bochitan My mistake :( As a workaround, try this:
```
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'develop'
```

**Comment by bochitan** [comment]
thanks for your reply :)
