### ISSUE TITLE
4.0.0-beta compiler issue

### ISSUE THREAD

**Issue by privkin** [zhangao0086/DKImagePickerController#478]
Hello.
4.0.0-beta doesn't compile. The problem is in DKImageExtensionGallery class at 65 line. There we have wrong closure type for finishedBlock.
Thank you.

**Comment by tylerjames** [comment]
Seeing this same thing as well.

**Comment by lhang** [comment]
I guess it's a dependencies issue. DKPhotoGallery is version 0.0.3

**Comment by zhangao0086** [comment]
Fixed. Thanks to all :)

**Comment by privkin** [comment]
Thanks!
