### ISSUE TITLE
4.0.0-beta dependencies error

### ISSUE THREAD

**Issue by lhang** [zhangao0086/DKImagePickerController#479]
DKPhotoGallery 0.0.3 [has been deleted](https://github.com/CocoaPods/Specs/commits/cb9c86c279d7f8bd0e03186e146b3e9cbd559f9f/Specs/0/d/e/DKPhotoGallery). Maybe you should update dependencies.

use newest pod repo to install dependencies will install DKPhotoGallery 0.0.5 by default. then there will have a compile error:
```
/DKImagePickerController/Extensions/DKImageExtensionGallery.swift:49:33: Cannot assign value of type '(_) -> _' to type '((Int, DKPhotoGalleryItem) -> UIImageView?)?'
```

**Comment by zhangao0086** [comment]
Hi @lhang I'm sorry about the 0.0.3 version was accidentally deleted :(
Recovered. Please try again.

**Comment by tylerjames** [comment]
It still installs 0.0.5 and gives the above error.

**Comment by zhangao0086** [comment]
Ohhh. My fault... I forgot to publish 4.0.0-beta2... 
Updated😅

**Comment by lhang** [comment]
@zhangao0086 it works, thx

**Comment by zhangao0086** [comment]
Closed 😃
