### ISSUE TITLE
Download Image & convert to DKAsset?

### ISSUE THREAD

**Issue by veer-suthar** [zhangao0086/DKImagePickerController#480]
I selected DKAsset from gallery, upload to server - also showing on CollectionView. 

Same Image I want to download back from URL & show on same CollectionView, how can I do. 
Any method you support to make UIImage to DKAsset without saving to gallery?

**Comment by zhangao0086** [comment]
Hi @veer-suthar 
Like this?
```swift
DKAsset(image: image)
```
