### ISSUE TITLE
About get error when build DKImagePickerController

### ISSUE THREAD

**Issue by shrimp101** [zhangao0086/DKImagePickerController#481]
I get these errors when trying to build project after install DKImagePickerController.
Please check my attachment.

Many thanks

![screen shot 2018-06-05 at 14 57 42](https://user-images.githubusercontent.com/4330436/40968458-c927fff0-68df-11e8-8380-be9b39c4f78f.png)
![screen shot 2018-06-05 at 14 57 50](https://user-images.githubusercontent.com/4330436/40968459-c95ce968-68df-11e8-9781-24dcd8c598a6.png)
![screen shot 2018-06-05 at 14 58 06](https://user-images.githubusercontent.com/4330436/40968460-c990ab22-68df-11e8-8384-152af51de1e2.png)
![screen shot 2018-06-05 at 14 58 11](https://user-images.githubusercontent.com/4330436/40968461-c9c7689c-68df-11e8-8322-6bda109b3784.png)
![screen shot 2018-06-05 at 14 58 13](https://user-images.githubusercontent.com/4330436/40968462-c9f80f7e-68df-11e8-9e4e-091d3b678b38.png)
![screen shot 2018-06-05 at 14 58 19](https://user-images.githubusercontent.com/4330436/40968463-ca31df92-68df-11e8-96b0-98263cc91e75.png)

**Comment by zhangao0086** [comment]
Hi Vu Thanh Nam,

It seems that the swift version of the project settings is incorrect.
In addition, you can try to update the DKImagePickerController to version 4.0.0-beta

pod 'DKImagePickerController', '~> 4.0.0-beta'

**Comment by shrimp101** [comment]
Thanks so much. I it work with version 4.0.0
But I get a new problem. How can I disable edit screen after capture a photo??
I take a look your document but can’t see the code.

Please help me figure out.

Thanks in advances

**Comment by zhangao0086** [comment]
Try this:
```
pod 'DKImagePickerController', :subspecs => ['PhotoGallery', 'Camera', 'InlineCamera']
```

**Comment by shrimp101** [comment]
Hi, I tried add pod 'DKImagePickerController', :subspecs => ['PhotoGallery', 'Camera', 'InlineCamera']
in my pod file and get this error.

![screen shot 2018-06-06 at 10 35 57](https://user-images.githubusercontent.com/4330436/41015675-86deb4fe-6975-11e8-8df7-23c5ef84a6ae.png)

**Comment by zhangao0086** [comment]
Ohhhh... My fault.
Try this...
```
pod 'DKImagePickerController', '~> 4.0.0-beta', :subspecs => ['PhotoGallery', 'Camera', 'InlineCamera']
```

**Comment by shrimp101** [comment]
It worked 👍 

Many thanks for your help.
