### ISSUE TITLE
Some memory leaks here

### ISSUE THREAD

**Issue by retsohuang** [zhangao0086/DKImagePickerController#482]
There are some memory leaks due to singleton manager and something else.
This can be reproduce using example project.
<img width="347" alt="screen shot 2018-06-07 at 2 54 44 pm" src="https://user-images.githubusercontent.com/785920/41083243-42bf96b4-6a63-11e8-8ca2-7d2266e83f8c.png">

**Comment by zhangao0086** [comment]
Hi @retsohuang @retsohuang Thanks for your reminder!

I think there is no memory leak here:
![image](https://user-images.githubusercontent.com/7742344/41105968-7d364fde-6aa1-11e8-967a-8cb0bb62cd9b.png)

Although Xcode indicated it out, deinit is actually executed correctly:
![image](https://user-images.githubusercontent.com/7742344/41105924-602ed488-6aa1-11e8-88ec-24bbf0cd38aa.png)

**Comment by retsohuang** [comment]
Yeah, I know that can successfully deallocate, but the strange things are there are warnings when I view with Memory Graph Hierarchy it's normal?
<img width="347" alt="screen shot 2018-06-08 at 11 59 03 am" src="https://user-images.githubusercontent.com/785920/41138426-c412e5e4-6b13-11e8-969e-d87fd08090ca.png">

**Comment by zhangao0086** [comment]
@doanntuann 
Sorry for the late response... 
Yes, you're welcome!
