### ISSUE TITLE
inline Mode DKImageGroupDataManagerConfiguration() unresloved

### ISSUE THREAD

**Issue by rintoandrews90** [zhangao0086/DKImagePickerController#483]
Swift Version 4.1
I have installed using pods. I tried to use inline mode. I am getting error "Use of unresolved identifier 'DKImageGroupDataManagerConfiguration'". I have done import DKImagePickerController.
Please check attached screenshot
![screen shot 2018-06-08 at 12 00 06 am](https://user-images.githubusercontent.com/16162588/41118905-f4aa701a-6aae-11e8-8bd9-d256587a339a.png)
Any help appriciated

**Comment by zhangao0086** [comment]
Hi @rintoandrews90 Looks like there is a problem with the environment. Could you post an example project here that can reproduce this issue?

**Comment by rintoandrews90** [comment]
Thanks for support am attaching project file. Please help 
[MuitiImagePicker.zip](https://github.com/zhangao0086/DKImagePickerController/files/2087862/MuitiImagePicker.zip)

**Comment by zhangao0086** [comment]
Hi @rintoandrews90 

Try installing the latest version:
```swift
pod 'DKImagePickerController', '~> 4.0.0-beta'
```

**Comment by tesshi** [comment]
@zhangao0086 How can I use `CustomInlineLayoutUIDelegate()`?
I wanted to use inline Mode and I was supposed to change `UIDelegate` to `CustomInlineLayoutUIDelegate()`, but it doesn't work...

**Comment by zhangao0086** [comment]
@tesshi What error have you got?

**Comment by tesshi** [comment]
@zhangao0086 
It was like this 'Use of unresolved identifier "CustomInlineLayoutUIDelegate"'

First, I tried 
```
pod 'DKImagePickerController'
```
then I tried the latest version
```
pod 'DKImagePickerController', '~> 4.0.0-beta'
```

Xcode9.3.1, Swift 4.1

![2018-07-03 16 10 45](https://user-images.githubusercontent.com/10583321/42204124-b6c7246e-7edb-11e8-9814-891efc312626.png)

**Comment by zhangao0086** [comment]
`CustomInlineLayoutUIDelegate` not be part of `DKImagePickerController`, it's just a class in the example project. I think you have to create a `CustomInlineLayoutUIDelegate` file of your own.

**Comment by tesshi** [comment]
@zhangao0086 Oh...I got it, I thought it's prepared haha
Okay, I'll create it on my own. Thanks a lot : )
