### ISSUE TITLE
build failed for latest code

### ISSUE THREAD

**Issue by marutiagarwal** [zhangao0086/DKImagePickerController#486]
![screen shot 2018-06-16 at 10 07 03 am](https://user-images.githubusercontent.com/2354751/41499368-11ab1c60-714d-11e8-8850-2f6bbea73a82.png)

I am using Xcode Version 9.3.1. and 
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git'

**Comment by zhangao0086** [comment]
Try this:
```
pod 'DKImagePickerController', '~> 4.0.0-beta'
```
