### ISSUE TITLE
How can I get selected asset on tapping collection view cell?

### ISSUE THREAD

**Issue by Uk44** [zhangao0086/DKImagePickerController#487]
currently i m getting this images into done button tapped. please help me ASAP.

**Comment by zhangao0086** [comment]
Post your code here.

**Comment by Uk44** [comment]
acutally, i want to get all images which will be selected on collectionvie cell tapped i want to display all images in collectionview whenever i select image from dkimagepicker then my collectionview will be reloaded so what can i do?
