### ISSUE TITLE
DKImageCheckView

### ISSUE THREAD

**Issue by alexanderkhitev** [zhangao0086/DKImagePickerController#488]
Hello @zhangao0086  ! I would like to inherit my class from `DKImageCheckView`, but it is inside `DKAssetGroupDetailImageCell`, if I put it in a separate file and I do pull request, will you approve it?

**Comment by zhangao0086** [comment]
I think you can make a cell that inherit `DKAssetGroupDetailBaseCell`, and then you will able to customize the appearance of this cell :)
