### ISSUE TITLE
Iphone X: Camera Cross Button hiding under Status Bar

### ISSUE THREAD

**Issue by Shrutimittal91** [zhangao0086/DKImagePickerController#489]
<img width="375" alt="screen shot 2018-07-03 at 12 55 02 pm" src="https://user-images.githubusercontent.com/8266611/42204853-76441322-7ec0-11e8-95dc-3e86468dfcd7.png">
As see in the screenshot the cancel button for camera in Iphone X is hiding under the status Bar.

**Comment by zhangao0086** [comment]
Hi @Shrutimittal91 Could you try the 4.0.0 version?

```
pod 'DKImagePickerController', '~> 4.0.0-beta'
```

**Comment by tatanehajain** [comment]
Hi @zhangao0086 
We tried the beta version, 4.0.0-beta and faced the build error.

<img width="1167" alt="screen shot 2018-07-11 at 4 00 44 pm" src="https://user-images.githubusercontent.com/40622109/42566315-d12f4d7e-8523-11e8-912d-6a9c57cc6708.png">

**Comment by zhangao0086** [comment]
Closing this thread...
