### ISSUE TITLE
DKImagePickerControllerAssetType not visible in Objective-C

### ISSUE THREAD

**Issue by EmilYo** [zhangao0086/DKImagePickerController#49]
Swift enums are not visible in Objective-C ( see more http://stackoverflow.com/a/24139544/426582 ).
To assetType be available also in Objective-C this enum must be changed to Struct.

**Comment by zhangao0086** [comment]
Thanks!

It seems that I forget to prefix the assetType with `@objc` :)

**Comment by zhangao0086** [comment]
It has been fixed in the [2.4.2](https://github.com/zhangao0086/DKImagePickerController/tree/2.4.2).

**Comment by EmilYo** [comment]
Great. Thank you.
