### ISSUE TITLE
Custom layout 

### ISSUE THREAD

**Issue by Uk44** [zhangao0086/DKImagePickerController#490]
i want to custom layout like this, how can i do? 
![screen shot 2018-07-03 at 8 20 34 pm](https://user-images.githubusercontent.com/20226112/42227364-fc96c724-7efe-11e8-9483-09948885d4f3.png)

**Comment by zhangao0086** [comment]
Have you found a resolution?

**Comment by Uk44** [comment]
no

**Comment by Ruberik** [comment]
There's an "inline" setting that you can see in Readme.MD. Perhaps you can make use of that somehow.

**Comment by zhangao0086** [comment]
Closing this thread.
