### ISSUE TITLE
deselectAll() method does not reload collectionView

### ISSUE THREAD

**Issue by alice05** [zhangao0086/DKImagePickerController#491]
On calling deselectAll() method inside following delegate method of DKImagePickerControllerBaseUIDelegate
`override func imagePickerController(_ imagePickerController: DKImagePickerController, didSelectAssets: [DKAsset])`
 , collectionView does not reload. Hence cell  is still in selected state. When I scroll up-down, the selected cell gets deselected. How should we reload the collectionView?

**Comment by zhangao0086** [comment]
Hi @alice05 

You can make a subclass that inherits from `DKImagePickerController` and then overrides the `canSelect:` function.

Like so:
```swift
class CustomPicker: DKImagePickerController {
    
    override func canSelect(asset: DKAsset, showAlert: Bool = true) -> Bool {
        if super.canSelect(asset: asset, showAlert: showAlert) {
            if self.selectedAssets.count == 2 {
                self.deselectAll()
                return true
            } else {
                return true
            }
        } else {
            return false
        }
    }
}
```
