### ISSUE TITLE
swift header error Cannot find interface declaration 

### ISSUE THREAD

**Issue by ahmedAlmasri** [zhangao0086/DKImagePickerController#492]
this issue provide if using myproject-swift.h

error message
> Cannot find interface declaration for 'DKImageBaseExtension', superclass of 'CustomCameraExtension'
![screen shot 2018-07-22 at 4 12 55 pm](https://user-images.githubusercontent.com/14888785/43045961-7ca6c94e-8dca-11e8-98a4-5c4a01bfaa65.png)

**Comment by Sanadbarjawi** [comment]
+1

**Comment by zhangao0086** [comment]
Unfortunately, you cannot subclass a Swift class in Objective-C. 

> For more details, see Apple's guide:https://developer.apple.com/documentation/swift/migrating_your_objective-c_code_to_swift

Instead, I think you have to make a Swift class that inherit `DKImageBaseExtension`, then import it via `myproject-swift.h`

**Comment by ahmedAlmasri** [comment]
@zhangao0086  yes , I'm use build version 4.0.2 , but the same error

**Comment by zhangao0086** [comment]
@ahmedAlmasri  Can I get a minimum sample project that can confirm this issue?

**Comment by ahmedAlmasri** [comment]
You needed to import the -Swift.h for for both the framework and the app target

```
#import <UIKit/UIKit.h>
#import <AVFoundation/AVFoundation.h>
#import <Foundation/Foundation.h>
#import <Photos/Photos.h>
#import <CLImageEditor/CLImageEditor.h>
#import "FLAnimatedImage.h"
#import "DKPhotoGallery-Swift.h"
#import "FLAnimatedImageView.h"
#import "DKImagePickerController-Swift.h"
```
