### ISSUE TITLE
Facing problem to getting video url from the asset.

### ISSUE THREAD

**Issue by NiteshKhandal** [zhangao0086/DKImagePickerController#494]
Hello sir i am fetching videos using DKImagePickerController and using below code for getting video url and then convert it into NSData.

 if asset.isVideo == true{
                
                asset.fetchAVAsset( .none, completeBlock: { video, info in
                    
                    do{
                        
                        let videourl = video as! AVURLAsset
                        print(videourl)
                        print(videourl.url)
                        let videodata = try Data(contentsOf: videourl.url)
                        
                        self.videoArray.append(videodata)
                    }
                    catch { print("error in video load") }
                    
                })
                
            }
But the problem is that sometimes we are not getting video url to convert into Data.

Please help us and let us know that how to do this task, also how to compress video before uploading.
actually we have to upload multiple videos at a time like face book.

**Comment by zhangao0086** [comment]
Please refer to https://github.com/zhangao0086/DKImagePickerController#exporting-to-file
