### ISSUE TITLE
crash in iphone 6

### ISSUE THREAD

**Issue by ArjunSa786** [zhangao0086/DKImagePickerController#5]
hi
i have selected 20 images and each image size like 1.5 to 3 mb .after select 20 images it will show received memory warning and crash

**Comment by zhangao0086** [comment]
Thanks ~!
Could you post the log of the crash in Xcode?

**Comment by ArjunSa786** [comment]
two times come  Received memory warning. and crash

**Comment by zhangao0086** [comment]
Hi @ArjunSa786 
I just made a test. In the test, I have selected 20+ images and each image size equal to **6 MB**. And it works.

So I think you have any other problems in your project. Could you share your project?

**Comment by zhangao0086** [comment]
Closing the thread...

**Comment by ArjunSa786** [comment]
Hi
in your rev project showing video thumbnail image .i need only image .
and also scroll list of images and click back button crash 
thanls

**Comment by ArjunSa786** [comment]
hi zhangao0086
how to find navigation back button click method in your code 
thanks

**Comment by zhangao0086** [comment]
Hi @ArjunSa786 
Do you mean the "Cancel" button? 
Hope this have helped you :)
![9cbda30c-b4df-45e4-9d81-483608ad4605](https://cloud.githubusercontent.com/assets/7742344/11109664/d844d682-892d-11e5-9d25-6a4f6e213f22.png)

**Comment by ArjunSa786** [comment]
No cancel button..In your prev project when click group Pic and select one group ->list of photos -> in top bar ---   <back button .how i find that method.because when scroll collection view suddenly click back button crash app.i want to nil collection view delegate and collection view.thanks

**Comment by ArjunSa786** [comment]
![screen shot 2015-11-12 at 12 16 41 pm](https://cloud.githubusercontent.com/assets/10627749/11112280/64f5c68c-8937-11e5-8958-34c19f75d15a.png)

**Comment by zhangao0086** [comment]
Can you offer more info about crash info? I think I can fix it.

**Comment by leobouilloux** [comment]
Hi, I'm currently having the same problem initially posted by ArjunSa786.
When I select multiple images (arround 20), it crash on my iPhone 6, but I have no problem on my iPad pro.

Here is the code involved, I know I'm doing  something wrong can you help me please?

        pickerController.didSelectAssets = { (assets: [DKAsset]) in
            for a in assets {
                let date = a.originalAsset!.creationDate!
                let dateFormatter: NSDateFormatter = NSDateFormatter()
                dateFormatter.dateFormat = "YYYY-MM-dd_hh-mm-ss"
                let pictureDate: String = dateFormatter.stringFromDate(date)
                
                a.fetchOriginalImageWithCompleteBlock({ (image, info) in
                    let filename = documentsDirectory.stringByAppendingPathComponent("\(pictureDate).jpg")
                    dispatch_async(dispatch_get_global_queue(DISPATCH_QUEUE_PRIORITY_HIGH, 0)) {
                        UIImageJPEGRepresentation(image!, 0.65)!.writeToFile(filename, atomically: true)
                    }
                })
            }
        }

For each iteration in the loop the memory increase significally (arround 30-50mB by image)

Here is the message received on the output: 

> Message from debugger: Terminated due to memory issue 

Hope you can help,

Kind regards,

**Comment by SnehalDhanani** [comment]
I am having the same issue. When I tried demo project there is no memory increase but when I install the given Pod and tried it with new project I found that memory Usage is gross. How do I reduce memory usage ? I don't know what I am missing here. Please help !!
