### ISSUE TITLE
Change Default Folder

### ISSUE THREAD

**Issue by arthj9** [zhangao0086/DKImagePickerController#50]
Is there a way to change the default album to be displayed. That is, I want the Camera Roll to be the first thing a user sees.

**Comment by zhangao0086** [comment]
No. I'll add the feature in 3.0 with Photos framework.

**Comment by arthj9** [comment]
Any estimate on when 3.0 will be released?

**Comment by zhangao0086** [comment]
I hope I can release it in the coming week :)
