### ISSUE TITLE
Iphone X:use CustomCameraExtension by 4.0.0.beta2 

### ISSUE THREAD

**Issue by BoomDaDa** [zhangao0086/DKImagePickerController#502]
use DKImageExtensionController.registerExtension(extensionClass: CustomCameraExtension.self, for: .camera)
![img_2da00769d85d-1](https://user-images.githubusercontent.com/9928377/44440493-e0fec480-a5fa-11e8-91c6-ee5e2fa7b799.jpeg)

**Comment by zhangao0086** [comment]
CLImageEditor has been replaced with TOCropViewController.
