### ISSUE TITLE
iPhone X - Photo Editor unusable 

### ISSUE THREAD

**Issue by jmilillo** [zhangao0086/DKImagePickerController#507]
Creating a new issue because I was unsure what [https://github.com/zhangao0086/DKImagePickerController/issues/502](issue 502) was trying to report.  The image shown in that bug is the same behavior with the out of the box Photo Editor.

Looks like the photo editor does not deal with the safe area as the user is unable to tap Cancel or Done - leaving the app stuck on that screen.

A work around is to not use the Photo Editor at all until this gets fixed.  Update your podfile as shown in the documentation: 

`pod 'DKImagePickerController', :subspecs => ['PhotoGallery', 'Camera', 'InlineCamera']`

**Comment by Derekhie** [comment]
Having the same problem. Safe area is not being handled correctly. User just gets stuck on the screen.

**Comment by zhangao0086** [comment]
Please update to `4.1.0`. CLImageEditor has been replaced with TOCropViewController.
