### ISSUE TITLE
Need update podspec

### ISSUE THREAD

**Issue by intoxicated** [zhangao0086/DKImagePickerController#509]
s.pod_target_xcconfig = { 'SWIFT_VERSION' => '4.2' } -> s.swift_version = "4.2".

https://github.com/CocoaPods/CocoaPods/issues/7134

**Comment by intoxicated** [comment]
if host project is using swift 4.0, pod do not automatically set this framework to use 4.2.

**Comment by intoxicated** [comment]
not only this pod but every dependencies (e.g DKCamera)

**Comment by zhangao0086** [comment]
Thanks for your feedback! I'll update and publish the related pods later 😃

**Comment by zhangao0086** [comment]
@intoxicated Updated 😃

**Comment by sorianog** [comment]
@zhangao0086 Do you have a PR up fort his yet? I don't mind reviewing it. Updating stuff like this is things I've been exposed to at my day job 😄

**Comment by zhangao0086** [comment]
Hi @sorianog 

I made a "Squash and merge" commit :(
https://github.com/zhangao0086/DKImagePickerController/commit/629b78c36783e4fb04536b85c91a1e10f22371ce#diff-1585c9603b22747e6cf3fb53303c2684
