### ISSUE TITLE
Carthage support is broken

### ISSUE THREAD

**Issue by vvit** [zhangao0086/DKImagePickerController#511]
Hi there, thanks for your work.
I know there's carthage support added. But it seems it doesn't work anymore:

```
*** Checking out DKImagePickerController at "a2909dadc2676c5ac32f6bb52ce23b838fa4adf6"
*** xcodebuild output can be found in /var/folders/rl/2_xfbkzd4sb9_0r_60_0cjxh0000gn/T/carthage-xcodebuild.p3wPml.log
*** Skipped building DKImagePickerController due to the error:
Dependency "DKImagePickerController" has no shared framework schemes for any of the platforms: iOS

Dependency "DKImagePickerController" has no shared framework schemes
```

Can you please check? 
Thanks.

**Comment by zhangao0086** [comment]
Thanks. You can install DKImagePickerController using the following command:

github "zhangao0086/DKImagePickerController" "carthage"
Once I complete the necessary test, I'll release it

**Comment by LeeroyDing** [comment]
Is been broken for almost a month and the `carthage` branch has been removed from this repo and from `DKPhotoGallery` too. All workarounds that worked previously has been unavailable for now. Any plans for fixing this one?

**Comment by touyu** [comment]
I tried it in 4.0.4 but it failed. How can I solve it?

> Build Failed
	Task failed with exit code 65:
	/usr/bin/xcrun xcodebuild -project /xxx/Carthage/Checkouts/DKPhotoGallery/DKPhotoGallery.xcodeproj -scheme DKPhotoGallery -configuration Release -derivedDataPath /Users/yuto/Library/Caches/org.carthage.CarthageKit/DerivedData/10.0_10A255/DKPhotoGallery/0.0.10 -sdk iphoneos ONLY_ACTIVE_ARCH=NO CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY= CARTHAGE=YES archive -archivePath /var/folders/f0/2_8lljw512ngt8wqk8k_zs480000gn/T/DKPhotoGallery SKIP_INSTALL=YES GCC_INSTRUMENT_PROGRAM_FLOW_ARCS=NO CLANG_ENABLE_CODE_COVERAGE=NO STRIP_INSTALLED_PRODUCT=NO (launched in /xxx/Carthage/Checkouts/DKPhotoGallery)

> This usually indicates that project itself failed to compile. Please check the xcodebuild log for more details: /var/folders/f0/2_8lljw512ngt8wqk8k_zs480000gn/T/carthage-xcodebuild.WfzWo3.log

**Comment by zhangao0086** [comment]
Hi @touyu It's working for me. I created an example project:
[TestCarthage.zip](https://github.com/zhangao0086/DKImagePickerController/files/2540926/TestCarthage.zip)

Just `TestCarthage: carthage update --platform ios`
