### ISSUE TITLE
carthage update DKImagePickerController fail

### ISSUE THREAD

**Issue by yuhaiping** [zhangao0086/DKImagePickerController#513]
*** Skipped building DKImagePickerController due to the error:
Dependency "DKImagePickerController" has no shared framework schemes

If you believe this to be an error, please file an issue with the maintainers at https://github.com/zhangao0086/DKImagePickerController/issues/new

**Comment by zhangao0086** [comment]
Hi @yuhaiping Try this:
```
github "zhangao0086/DKPhotoGallery" "carthage"
```

Let me know if that works

**Comment by zhangao0086** [comment]
I didn't notice this. Thanks. You can install `DKImagePickerController` using the following command:

```
github "zhangao0086/DKImagePickerController" "carthage"
```

Once I complete the necessary test, I'll release it

**Comment by leonid-s-usov** [comment]
That I tried yesterday, and it has failed with another issue #527

**Comment by zhangao0086** [comment]
Are you using Xcode 9.4.1 and Swift 4.1?

**Comment by leonid-s-usov** [comment]
Yes, I am

**Comment by zhangao0086** [comment]
@leonid-s-usov Try this:
```
github "zhangao0086/DKImagePickerController" "Swift4"
```
