### ISSUE TITLE
Refreshing DKImagePickerController / DKAssetGroupDetailVC

### ISSUE THREAD

**Issue by mokudekiru** [zhangao0086/DKImagePickerController#523]
I would like to reload the whole image picker in place as the result of a user interaction that changes the imageFetchPredicate.

I already have subclasses for DKImagePickerController & DKAssetGroupDetailVC - what is the best way to accomplish this? We don't have direct access to the collectionView for reload, and I would also like to refresh the titleView, etc.

**Comment by zhangao0086** [comment]
The picker was designed with a configuration is immutable. Could you create a new instance of picker to replace the existing picker?

**Comment by zhangao0086** [comment]
Hi @mokudekiru I added the `reload` functionality. Please check this: https://github.com/zhangao0086/DKImagePickerController/commit/81745d83a3051652cd54f01003125c9028dd58bd

```
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Feature/reload'
```

Also, I have updated the demo project in the `Feature/reload` branch.
![image](https://user-images.githubusercontent.com/7742344/47142154-e32c8900-d2f4-11e8-8161-5341ec3d4bb3.png)

let me know if you have any questions :)
