### ISSUE TITLE
xcode 9.4.1 UIViewController has no member 'AnimationOptions' error

### ISSUE THREAD

**Issue by ismailtosun** [zhangao0086/DKImagePickerController#527]
hi, I'm using xcode 9.4.1 and swift 4 version. 
My pod like this : **pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'master'**

but some error is occurred : **Type 'UIView' has no member 'AnimationOptions'**

**Comment by zhangao0086** [comment]
Try this:
```swift
pod 'DKImagePickerController', '4.0.0'
```
Any versions higher than 4.0.0 are Swift 4.2 :)

**Comment by sorianog** [comment]
@zhangao0086 And at some point, Xcode 10 is needed as well! Forgot what version though.

**Comment by ismailtosun** [comment]
now I update my pod like **pod 'DKImagePickerController', '4.0.0'**
but now I'm getting DKCamera framework error

**Comment by zhangao0086** [comment]
@sorianog You're right! There are no branches/tags available for Xcode9/Swift4 now. 
Maybe I should create a branch for that.

**Comment by zhangao0086** [comment]
@ismailtosun Please try this:
```
pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Swift4'
```

**Comment by ismailtosun** [comment]
@zhangao0086 thanks 👍

**Comment by ismailtosun** [comment]
@zhangao0086 now I'm getting DynamicBlurView and DKCamera error bro.

**Comment by ismailtosun** [comment]
@zhangao0086  now I'm getting DynamicBlurView error.

**Comment by ismailtosun** [comment]
@zhangao0086  help please ?

**Comment by zhangao0086** [comment]
@ismailtosun Please try again :)
