### ISSUE TITLE
swift 4.1 xcode 9.4.1 DKCamera error.

### ISSUE THREAD

**Issue by ismailtosun** [zhangao0086/DKImagePickerController#528]
hi, My pod like :  **pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Swift4'**

but DKCamera gives me an error that uiview has no member animation option

please help !

**Comment by sorianog** [comment]
@zhangao0086 You can close this one too. Its the 2nd duplicate of #527
