### ISSUE TITLE
xcode 9.4.1 swift 4.1 DKCamera framework error

### ISSUE THREAD

**Issue by ismailtosun** [zhangao0086/DKImagePickerController#529]
hi, My pod like :  **pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Swift4'**

but DKCamera gives me an error that uiview has no member animation option

please help !

**Comment by sorianog** [comment]
@ismailtosun Try building your project again using Xcode 10

**Comment by sorianog** [comment]
Please provide your updates in your previous issue. The maintainer is a busy person and it would be helpful if we have clean and easy to read/follow issue threads. 

@zhangao0086 Close this. It's the same person and issue in #527

**Comment by zhangao0086** [comment]
@sorianog Thanks for your help! I appreciate it!
Closing this thread.
