### ISSUE TITLE
I can't get data from assets in new version

### ISSUE THREAD

**Issue by Casporro** [zhangao0086/DKImagePickerController#53]
With the new version (3.0.0) I can't get NSData from assets... If I do this:
```
assets.first!.fetchImageWithSize(sender.view!.bounds.size, completeBlock: {
          (image: UIImage?) -> Void in
                            
           if let imageToSave = image {
                   let data: NSData = UIImageJPEGRepresentation(imageToSave, 0.7) //data always nil
                    self.saveImage(data!)
        }
}
```
data is always nil an image never is nil... What is the problem?

**Comment by zhangao0086** [comment]
Could you try the fixed syntax:
`let data: NSData? = UIImageJPEGRepresentation(imageToSave, 0.7) `

In addition, if the `imageToSave` cannot obtain the jpeg image data, it will return nil. In this case, try to replace `UIImageJPEGRepresentation` with `UIImagePNGRepresentation`.

**Comment by Boli-CS** [comment]
I have another question, how could I get the NSURL of the photo choosed?

**Comment by zhangao0086** [comment]
Hi @Boli-CS 
Why do you want to do this?

**Comment by Casporro** [comment]
Why the fetchImageWithSize method return other size??

**Comment by Casporro** [comment]
and how can I get NSData from AVURLAsset?

**Comment by zhangao0086** [comment]
Hi @Casporro 
You can get NSData from AVURLAsset like this:
```swift
assets.first?.fetchAVAssetWithCompleteBlock({ (avAsset) -> Void in
	let data = NSData(contentsOfURL: avAsset!.URL)
	print(data)
})
```

**Comment by zhangao0086** [comment]
For the ***Why the fetchImageWithSize method return other size??***

It's my fault! Fixed in https://github.com/zhangao0086/DKImagePickerController/commit/78d4e8cbb9183101c61d1a4041e98d529290cfcf :)

**Comment by Casporro** [comment]
Thank you @zhangao0086, nice library and nice work.
I will use exporter to export video to something compatible with iOS and Android.

**Comment by Casporro** [comment]
Can you tell me how can I get a thumbnail from avAsset?

**Comment by zhangao0086** [comment]
@Casporro 
Try using `AVAssetImageGenerator`. 
See also:http://stackoverflow.com/questions/8906004/thumbnail-image-of-video

**Comment by melihkeskin** [comment]
hi zhangao0086,
Nice work..Thanks for sharing.

i want to ask some questions

How can i get images from assets ? 
Can you write a little sample code ?

**Comment by zhangao0086** [comment]
Hi @melihkeskin 
Try this:

```swift
assets.first?.fetchFullScreenImageWithCompleteBlock({ image in
	print(image)
})
```

**Comment by melihkeskin** [comment]
Hello again :),

thank you for your reply
is it only first image isnt it?

what can i do multiple picking ?

**Comment by zhangao0086** [comment]
@melihkeskin 
You can do this:
```swift
var images: [UIImage] = []
for asset in assets {
	asset.fetchFullScreenImageWithCompleteBlock({ image in
		images.append(image!)
		
		if images.count == assets.count {
			print("done")
		}
	})
}
```

Why do you want to get `didFinishPickingMediaWithInfo`? It's a delegate method of  `UIImagePickerController`, so it's never called in this library.

**Comment by melihkeskin** [comment]
Thank for help. I want to get metadata of the images.
I find many sample on the internet but generally they used in the didfinishpickingmediawithinfo. İf you can know other way please tell

**Comment by zhangao0086** [comment]
@melihkeskin 
If you need to get the metadata of a DKAsset, just access the `originalAsset` like so:
```swift
if let originalAsset = asset.originalAsset {
	originalAsset.mediaType
	originalAsset.mediaSubtypes
	originalAsset.creationDate
	originalAsset.modificationDate
	// ...
}
```

See also: [Reading Asset Metadata](https://developer.apple.com/library/ios/documentation/Photos/Reference/PHAsset_Class/#//apple_ref/doc/uid/TP40014383-CH1-SW3)

**Comment by melihkeskin** [comment]
Hello zhangao0086,

i appreciate you. You are really good my friend.
Thanks for everything.
Nice work.

**Comment by zhangao0086** [comment]
@melihkeskin 
I’m glad that helped you :)

**Comment by aldolazuardi** [comment]
hi zhangao0086,
im following ur answer to melihkeskin and it not works (pic below), why i got this error?
<img width="1139" alt="screen shot 2016-01-12 at 3 52 42 pm" src="https://cloud.githubusercontent.com/assets/9720223/12259057/94b42fec-b945-11e5-9fee-615239ec98f1.png">

**Comment by zhangao0086** [comment]
Hi @aldolazuardi 

In 3.0.4, I've updated the `fetchImage...` interface:
the `completeBlock: (image: UIImage?) -> Void` was changed to `completeBlock: (image: UIImage?, info: [NSObject : AnyObject]?) -> Void` so you need to change:

```swift
asset.fetchImageWithSize(size, completeBlock: { image in
    // ...
})
```
to:
```swift
asset.fetchImageWithSize(size, completeBlock: { image, info in
    // ...
})
```
