### ISSUE TITLE
CompleteBlock executes twice

### ISSUE THREAD

**Issue by Casporro** [zhangao0086/DKImagePickerController#54]
Another issue is this method... the code inside block executes twice for each asset...
```
image.fetchFullScreenImageWithCompleteBlock({
        (image: UIImage?) -> Void in
       //code here executes twice for each asset
})
```

**Comment by Casporro** [comment]
If a want something like this:
```
image.fetchImageWithSize(CGSizeMake(640, 240), completeBlock: {
    (image: UIImage?) -> Void in
    imageView.image = image
})

image.fetchImageWithSize(CGSizeMake(750, 1334), completeBlock: { //This block executes twice
    (image: UIImage?) -> Void in
    imageView2.image = image //This line executes twice
})
```
And the second complete block of fetchImage method executes twice...

**Comment by Casporro** [comment]
In conclusion... the call (if is only one) or the last call (if are more than one) of any method fetchImage executes twice...

**Comment by zhangao0086** [comment]
Fixed.

**Comment by zhangao0086** [comment]
@Casporro 
Thanks ~!

https://github.com/zhangao0086/DKImagePickerController/commit/328178ec7d73862bbe32a4ac8b19e6e56bf51d78

**Comment by sandeepbol** [comment]
This issue is happening again on latest release (3.5.7)

**Comment by i0sa** [comment]
yup still happening

**Comment by zhangao0086** [comment]
@i0sa Could you try the `4.0.0-Beta`?

**Comment by i0sa** [comment]
@zhangao0086 yes i did, same thing happening, fetching image with specific sizes excutes twice, once with image with size of (120,80) and once again with original image size

supposedly "fetchImage(with: CGSize()" is supposed to return image with my selected size ? in fact it returns original size,
what's the issue ?
