### ISSUE TITLE
Swift Issues

### ISSUE THREAD

**Issue by thiagodelmotte** [zhangao0086/DKImagePickerController#542]
![captura de tela 2018-11-12 as 14 55 23](https://user-images.githubusercontent.com/2932550/48362596-1c091500-e68b-11e8-9516-65a16422767f.png)

![captura de tela 2018-11-12 as 14 55 14](https://user-images.githubusercontent.com/2932550/48362597-1c091500-e68b-11e8-94ff-b20bf239f991.png)

**Comment by zhangao0086** [comment]
Fixed in `4.0.5` :)

**Comment by thiagodelmotte** [comment]
👏
