### ISSUE TITLE
camera.containsGPSInMetadata = containsGPSInMetadata

### ISSUE THREAD

**Issue by choiks14** [zhangao0086/DKImagePickerController#551]
version:4.1.0

```
camera.containsGPSInMetadata = containsGPSInMetadata
```
Error:(26, 9) value of type 'DKCamera' has no member 'containsGPSInMetadata'

**Comment by zhangao0086** [comment]
Could you check your `Podfile.lock` file about using `DKCamera` version?

It should be `1.6.4`
```
  - DKCamera (1.6.4)
```

**Comment by sorianog** [comment]
@zhangao0086 I'm getting the same error too when building the Example project. The version I get for `DKCamera` is actually `1.6.2` as reported in the `Podfile.lock`
I've already ran `pod install` before running the project.

**Comment by lawicko** [comment]
A workaround would be to force the 1.6.4 version in your Podfile, like this:
`pod 'DKCamera', :git => 'https://github.com/zhangao0086/DKCamera.git', :commit => '1227253b029dc1271d278c321141bf8f92212955'`
This commit id leads to the required version.

**Comment by sorianog** [comment]
This issue is intermittent for me. I'm not seeing it anymore.

**Comment by lawicko** [comment]
Well, I'm not sure what is going on here, but when you take a look at `pod search DKCamera`:
`-> DKCamera (1.6.2)
   A light weight & simple & easy camera for iOS by Swift.
   pod 'DKCamera', '~> 1.6.2'
   - Homepage: https://github.com/zhangao0086/DKCamera
   - Source:   https://github.com/zhangao0086/DKCamera.git
   - Versions: 1.6.2, 1.6.1, 1.6.0, 1.5.3, 1.5.2, 1.5.1, 1.5.0, 1.4.0, 1.3.4, 1.3.3, 1.3.2, 1.3.1, 1.2.11, 1.2.9, 1.2.8, 1.2.7,
   1.2.6, 1.2.5, 1.2.3, 1.2.2, 1.2.1, 1.2.0, 1.1.0, 1.0.4, 1.0.3, 1.0.2, 1.0.0 [master repo]`
I may be wrong, but version 1.6.2 is the newest visible version to the cocoapods, so I don't know how this can work.

**Comment by zhangao0086** [comment]
@lawicko Please run `pod update`

**Comment by applepeopletsai** [comment]
I was facing the same issue because of DKCamera version is '1.6.2'
As @zhangao0086 say, after run 'pod update', 'DKCamera'  version update to '1.6.4', and fix the issue.
Hope this helps.

**Comment by zhangao0086** [comment]
Closing this thread...
