### ISSUE TITLE
showsEmptyAlbums causing duplicate on albums

### ISSUE THREAD

**Issue by OliverDimitrov** [zhangao0086/DKImagePickerController#552]
Basically when showsEmptyAlbums = false, you duplicate the albums. 
Function in DKAssetGroupListVC.swift:212 (filterEmptyGroupIfNeeded). Need to create and return different array of strings, instead of appending to the already existing one.

**Comment by zhangao0086** [comment]
Oh.. My fault!!!

Please check this: https://github.com/zhangao0086/DKImagePickerController/commit/8232489db48a071994771c698a6da01bbff6866e
