### ISSUE TITLE
fetchFullScreenImage on iPhone X is low resolution

### ISSUE THREAD

**Issue by andresarocho** [zhangao0086/DKImagePickerController#556]
Fetching full screen image using **fetchFullScreenImage** on iPhone X returns a very low resolution image. I noticed that this is because the method **toPixel()** checks if the device is an iPhone X and automatically sets the width to 279 or less:

```
	public func toPixel() -> CGSize {
		let scale = UIScreen.main.scale
   
        let screenHeight = max(UIScreen.main.bounds.size.width, UIScreen.main.bounds.size.height)
        if UIDevice.current.userInterfaceIdiom == .phone && screenHeight == 812.0 { // iPhoneX.
            return CGSize(width: min(279, self.width * scale), height: min(279, self.height * scale))
        } else {
            return CGSize(width: self.width * scale, height: self.height * scale)
        }
	}
```

Is there any specific reason on why it is downsized?

Thank you

**Comment by yarodevuci** [comment]
@zhangao0086  hello?

**Comment by mouness2020** [comment]
same problem here

**Comment by dmitrykurochka** [comment]
Yeah it kinda weird. Why??

**Comment by zhangao0086** [comment]
Removed the limit that the width and height cannot exceed 279 on iPhone X. https://github.com/zhangao0086/DKImagePickerController/commit/edb87bbe792835ea8f528c9ad7c142fceb3891e9
