### ISSUE TITLE
Problem with very large number of photos in photoroll

### ISSUE THREAD

**Issue by murthyveda2000** [zhangao0086/DKImagePickerController#564]
I have a user who has over 12k photos in her photoroll. Using the DKImagePickerController version 3.8.1 doesn't have any problem. She is able to switch albums and select photos seamlessly. However, once I upgraded to Swift 4.2 and DKImagePickerController version 4.1.0, it is practically unusable. The picker doesn't respond to tapping on photos and it takes an incredibly long time to switch albums. 

Has anyone else seen these problems arise when upgrading to the latest version of the library?

**Comment by parkboo** [comment]
Me too. Some of my customers are suffering from this issue.

**Comment by SpiciedCrab** [comment]
The issue raised when users have a large number of groups in their albums, since the pickerController' collectionView will call reloadData() frequently before all components loaded. 
So all the operations before loading finished won't work..

**Comment by zhangao0086** [comment]
Check https://github.com/zhangao0086/DKImagePickerController/pull/577
