### ISSUE TITLE
Hide croping opat

### ISSUE THREAD

**Issue by creativeportfolio-ios** [zhangao0086/DKImagePickerController#567]
currently, I'm use DKImageViewController with swift 4.2 using Carthage, which is working awesome.
I need to remove or hide cropping feature when take picture in current version.
so It is possible to remove or hide cropping feature.
![img_0055](https://user-images.githubusercontent.com/34706680/50272013-75b7e880-045c-11e9-94b8-d809f579fe98.PNG)

**Comment by zhangao0086** [comment]
Could you check the `develop` branch?
```
github "zhangao0086/DKImagePickerController" "develop"
```

You can hide cropping feature in the develop branch:
```
DKImageExtensionController.registerExtension(extensionClass: DKImageExtensionNone.self, for: DKImageExtensionType.photoEditor)
```
