### ISSUE TITLE
Fatal error: extension bundle method

### ISSUE THREAD

**Issue by trd-regulos** [zhangao0086/DKImagePickerController#570]
Hello guys.

Every time i clicked the button for selecting images
the app will crashed

![screen shot 2018-12-26 at 2 24 43 pm](https://user-images.githubusercontent.com/40347010/50434901-20774d80-091a-11e9-88db-39a50aaf0361.png)

I am using Swft 4.1
=>  pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git', :branch => 'Swift4'

Please help thanks

**Comment by ajithkumar666** [comment]
I have same issue , any solution?

**Comment by trd-regulos** [comment]
@ajithkumar666 maybe we need to update our Swift version to 4.2 and change pod to pod 'DKImagePickerController'

**Comment by ajithkumar666** [comment]
@trd-regulos  use this this worked for me swift 4
"pod https://github.com/zhangao0086/DKImagePickerController.git', :tag => '4.0.0'"

**Comment by zhangao0086** [comment]
Closing this thread...
