### ISSUE TITLE
Crash when forcing unwrap assets

### ISSUE THREAD

**Issue by hyouuu** [zhangao0086/DKImagePickerController#571]
Got crash report from Fabric - will make a PR to fix it:

Crashed: com.apple.main-thread
0  Pendo                          0x10537f0e0 specialized DKImageGroupDataManagerwith(_:) (DKImageGroupDataManager.swift:122)
1  Pendo                          0x10534e7d0 DKAssetGroupDetailVCfor(_:) (<compiler-generated>)
2  Pendo                          0x1053509f4 DKAssetGroupDetailVCfor(_:) (DKAssetGroupDetailVC.swift:455)
3  Pendo                          0x105355a7c $S23DKImagePickerController20DKAssetGroupDetailVCC14collectionView_13cellForItemAtSo012UICollectionI4CellCSo0nI0C_10Foundation9IndexPathVtFTf4dnn_n (DKAssetGroupDetailVC.swift:520)
4  Pendo                          0x105351838 $S23DKImagePickerController20DKAssetGroupDetailVCC14collectionView_13cellForItemAtSo012UICollectionI4CellCSo0nI0C_10Foundation9IndexPathVtFTo (<compiler-generated>)
5  UIKitCore                      0x1f1cc11ec -[UICollectionView _createPreparedCellForItemAtIndexPath:withLayoutAttributes:applyAttributes:isFocused:notify:] + 356
6  UIKitCore                      0x1f1cc552c -[UICollectionView _updateVisibleCellsNow:] + 4036
7  UIKitCore                      0x1f1cca5cc -[UICollectionView layoutSubviews] + 324
8  UIKitCore                      0x1f2893f44 -[UIView(CALayerDelegate) layoutSublayersOfLayer:] + 1380
9  QuartzCore                     0x1c9a51a34 -[CALayer layoutSublayers] + 184
10 QuartzCore                     0x1c9a569c4 CA::Layer::layout_if_needed(CA::Transaction*) + 324
11 QuartzCore                     0x1c99b59d4 CA::Context::commit_transaction(CA::Transaction*) + 340
12 QuartzCore                     0x1c99e42f4 CA::Transaction::commit() + 608
13 QuartzCore                     0x1c99e515c CA::Transaction::observer_callback(__CFRunLoopObserver*, unsigned long, void*) + 92
14 CoreFoundation                 0x1c53fdb94 __CFRUNLOOP_IS_CALLING_OUT_TO_AN_OBSERVER_CALLBACK_FUNCTION__ + 32
15 CoreFoundation                 0x1c53f8828 __CFRunLoopDoObservers + 412
16 CoreFoundation                 0x1c53f8dc8 __CFRunLoopRun + 1264
17 CoreFoundation                 0x1c53f85b8 CFRunLoopRunSpecific + 436
18 GraphicsServices               0x1c766c584 GSEventRunModal + 100
19 UIKitCore                      0x1f23f0bc8 UIApplicationMain + 212
20 Pendo                          0x104fd80a4 main (ThemePicker.swift:13)
21 libdyld.dylib                  0x1c4eb8b94 start + 4

**Comment by zhangao0086** [comment]
Closing...
