### ISSUE TITLE
Open Custom CameraViewController

### ISSUE THREAD

**Issue by AliTariqQuantum** [zhangao0086/DKImagePickerController#573]
Is there a way, when camera cell is tapped, I can open/present a custom **camera view controller**. I have third party paid camera which I want to use.

**Comment by zhangao0086** [comment]
Hi @AliTariqQuantum There is an example of using a custom camera in the example project:
![image](https://user-images.githubusercontent.com/7742344/50940417-d4044400-14bb-11e9-85d6-2a4304ae6220.png)

**Comment by AliTariqQuantum** [comment]
@zhangao0086 Thanks
