### ISSUE TITLE
Still has crash when accessing groups

### ISSUE THREAD

**Issue by hyouuu** [zhangao0086/DKImagePickerController#574]
We are already using optional access to groups, so my guess is the remaining problems lies in DKAssetGroup's properties - they're all forced unwrapped, but when assigning values to them, some are optional e.g. localizedTitle & ID. Will put up a PR to try to fix that.

#0Crashed: com.apple.main-threadEXC_BAD_ACCESS KERN_INVALID_ADDRESS 0x00a1ad3ac713fec4 Raw Text
--
0 | Pendo | DKImageGroupDataManager.swift line 122$S23DKImagePickerController0A16GroupDataManagerC05fetchD04withAA07DKAssetD0CSgSS_tFTf4xn_n
1 | Pendo | <compiler-generated> line 0$S23DKImagePickerController20DKAssetGroupDetailVCC10fetchAsset3forAA0D0CSgSi_tF
2 | Pendo | DKAssetGroupDetailVC.swift line 502$S23DKImagePickerController20DKAssetGroupDetailVCC19dequeueReusableCell3forAA0def4BaseJ0C10Foundation9IndexPathV_tF
3 | Pendo | DKAssetGroupDetailVC.swift line 585$S23DKImagePickerController20DKAssetGroupDetailVCC14collectionView_13cellForItemAtSo012UICollectionI4CellCSo0nI0C_10Foundation9IndexPathVtFTf4dnn_n
4 | Pendo | <compiler-generated> line 0$S23DKImagePickerController20DKAssetGroupDetailVCC14collectionView_13cellForItemAtSo012UICollectionI4CellCSo0nI0C_10Foundation9IndexPathVtFTo
5 | UIKitCore | <redacted> + 356
19 | UIKitCore | UIApplicationMain + 212
20 | Pendo | ThemePicker.swift line 13main
21 | libdyld.dylib | start + 4

**Comment by zhangao0086** [comment]
Closing...
