### ISSUE TITLE
Bug iOS 12.1

### ISSUE THREAD

**Issue by KunanjuOkta** [zhangao0086/DKImagePickerController#578]
In my project I use swift 4.1 

first i use pod 'DKImagePickerController' have crash in ios 8 and 9 and bug in iOS 12.1 (vesion 4.0.4)

I try to update until version 4.1.2 but still have some problem.

Then I tried to down grade version until 4.0.0 ( #570 )

In ios 8 already not crash but still have a bug in iOS 12.1

My problem is i cant select gallery group after give permission in iOS 12.1 but after closing apps and then open again its fine. Anyone have a solution to this problem?

**Comment by zhangao0086** [comment]
Unfortunately, I can't reproduce it :( Could you make a small project that can reproduce it?
