### ISSUE TITLE
Cannot use DKAsset.fetchImageWithSize with iCloud photos (Perhaps?)

### ISSUE THREAD

**Issue by eightstrax** [zhangao0086/DKImagePickerController#58]
Is there a way to disallow the user from seeing and selecting iCloud photos in the photo picker?  I've discovered a problem when the user selects a photo from their library that hasn't been downloaded to the device yet.  I'm not 100% sure that this means the photo is from iCloud and they are only seeing a small thumbnail preview in the picker.

Below are some scenarios to help you understand how I've determined that the failing photo is from iCloud or some other off-device storage.

Test Case 01:
1. User picks a photo that hasn't been downloaded to device yet.
2. Eventually my code will call "fetchImageWithSize" with a bounds of w:1200.0 and h:1200.0
3. The UIImage that is expected is "nil"

Test Case 02:
1.  First I went to the Photo library outside of my app and found a photo
2. I zoomed into the photo and noticed a circular loading icon in the bottom right hand corner of the image - I am guessing this means the image is downloading from iCloud???
3. User opens my app, initiates the DKPicker and selects the same photo from (1 & 2)
4. My code will call "fetchImageWithSize" with a bounds of w:1200.0 and h:1200.0
5. The UIImage that is expected is set correctly and is not "nil"

Everything else has been great BTW!  Nice work!

**Comment by zhangao0086** [comment]
Hi @eightstrax 
Thanks! I've noticed the problem too! And I've solved it in the `develop` branch :)
Can you help me test that?

```bash
pod 'DKImagePickerController', :branch => 'develop'
```

**Comment by eightstrax** [comment]
I updated my Pod file by removing the old reference and added that line with that 'develop' branch, however I'm getting the following error while running "pod install":

[!] Unknown external source parameters for `DKImagePickerController`: `{:branch=>"develop"}`

**Comment by eightstrax** [comment]
Hey, I fixed the pod issue by using this pod line instead:

pod 'DKImagePickerController', :git => 'https://github.com/zhangao0086/DKImagePickerController.git' , :branch => 'develop'

**Comment by zhangao0086** [comment]
Oh! Sorry, It's my fault!
Thanks for the correction!

**Comment by eightstrax** [comment]
Now I cannot build my Project....

![image](https://cloud.githubusercontent.com/assets/14557593/12017578/9ef2b6c6-adac-11e5-9c0d-e65092d1c0ca.png)

**Comment by zhangao0086** [comment]
Fixed. Please `pod update`.

**Comment by eightstrax** [comment]
Yes, it works now.  Great work!

Important to note to others after doing this:

Had to change the call to DKAsset (Asset) in my code from:

    Asset.fetchImageWithSize(CGSize(width:1200.0, height:1200.0), completeBlock: {
                (image: UIImage?) -> Void in
    ....
    ....
    })


to 
    Asset.fetchImageWithSize(CGSize(width:1200.0, height:1200.0), completeBlock: {
                (image: UIImage?, info: [NSObject: AnyObject]?) -> Void in
    ....
    ....
    })

**Comment by zhangao0086** [comment]
@eightstrax 
Thanks for all your testing!!! I'll update the demo project and release it in v3.0.4 :)
