### ISSUE TITLE
Cannot disable inline camera property

### ISSUE THREAD

**Issue by NilayDag** [zhangao0086/DKImagePickerController#585]
Is there a way to disable inline camera property(camera tile) while on photo or video selection? I tried pickerController.dismissCamera(isInline: true) but it doesn't seem to work.
<img width="580" alt="Camera Thumbnail" src="https://user-images.githubusercontent.com/20637243/54209028-106d1400-44ee-11e9-8a6b-96c8d887b25f.png"> 
I don't want user to see this camera option.

Thanks.

**Comment by zhangao0086** [comment]
Try this:
```swift
pickerController.sourceType = .photo
```

**Comment by NilayDag** [comment]
Oh it works! Thank you so much, you saved my day 💯

**Comment by zhangao0086** [comment]
I'm glad to hear it solved your issue :)
