### ISSUE TITLE
Anyone else not seeing any sort of border when selecting images?

### ISSUE THREAD

**Issue by eskimo** [zhangao0086/DKImagePickerController#587]
Am I doing something wrong? Doesn't seem to show in the demo project either. Also, resources don't seem to be working, I don't see the camera on the image picker, or the checkmark on the custom ui implementation demo.

**Comment by zhangao0086** [comment]
It sounds like the `DKImagePickerController.bundle` is not loaded.
Trying to clean your project and delete derived data.

**Comment by eskimo** [comment]
Worked. Thought I tried cleaning before posting this issue. Sorry :)
