### ISSUE TITLE
How to filter album by name?

### ISSUE THREAD

**Issue by minhhien177** [zhangao0086/DKImagePickerController#588]
Hi guys!

Thank you for the very helpful library. I'm checking whether it's available to filter the albums by name?

For example, I want to see only albums with names in ["Instagram", "Facebook", . . .]. How to make code to achieve this?

Thanks

**Comment by zhangao0086** [comment]
Please checkout the latest version:
```swift
let groupDataManagerConfiguration = DKImageGroupDataManagerConfiguration()

// Only shows the `Camera Roll`
groupDataManagerConfiguration.groupFetchPredicate = NSPredicate(format:"SELF.localizedTitle = %@", "Camera Roll")
            
let groupDataManager = DKImageGroupDataManager(configuration: groupDataManagerConfiguration)
let pickerController = DKImagePickerController(groupDataManager: groupDataManager)

```

**Comment by hien1dreamm** [comment]
Hi @zhangao0086, it works for me, thank you so much. Sorry for my late reply, please close the ticket.

**Comment by minhhien177** [comment]
Hi @zhangao0086, it works for me, thank you so much. Sorry for my late reply.
