### ISSUE TITLE
How to disable the cropping functionality?

### ISSUE THREAD

**Issue by lawicko** [zhangao0086/DKImagePickerController#593]
Release notes for version 4.1.1 promises, that the cropping functionality can be disabled, but I wasn't able to figure out how to do it, any hints? The extensionsController is private, so it doesn't look like it can be manipulated from outside and the default set of extensions is always loaded:

```
private lazy var extensionController: DKImageExtensionController! = {
        return DKImageExtensionController(imagePickerController: self)
    }()
```

I want to disable the cropping functionality because of #553

**Comment by bdobreav** [comment]
Hi, I am also looking for a way to disable the CropViewController. Is it possible? If yes, how?

**Comment by lawicko** [comment]
Sorry but I never got any answer to my question, so I don't know.

**Comment by bdobreav** [comment]
@zhangao0086 can you please tell us if we can disable the cropping functionality?

**Comment by zhangao0086** [comment]
@lawicko @bdobreav In `4.3.1`(iOS9 or above), you can try this:
```swift
let pickerController = DKImagePickerController()
pickerController.extensionController.disable(extensionType: .photoEditor)
```

**Comment by lawicko** [comment]
> @lawicko @bdobreav In `4.3.1`(iOS9 or above), you can try this:
> 
> ```swift
> let pickerController = DKImagePickerController()
> pickerController.extensionController.disable(extensionType: .photoEditor)
> ```

@zhangao0086 `extensionController` is a private property, so I don't think it's possible 😞

**Comment by zhangao0086** [comment]
> > @lawicko @bdobreav In `4.3.1`(iOS9 or above), you can try this:
> > ```swift
> > let pickerController = DKImagePickerController()
> > pickerController.extensionController.disable(extensionType: .photoEditor)
> > ```
> 
> @zhangao0086 `extensionController` is a private property, so I don't think it's possible 😞

@lawicko The extensionController is public: https://github.com/zhangao0086/DKImagePickerController/commit/2bb1b76657a620c520428c969770829bf87e6f1e#diff-32eeb1475dfb238c2518164b2836a271
