### ISSUE TITLE
Video Thumbnails

### ISSUE THREAD

**Issue by Chefda** [zhangao0086/DKImagePickerController#6]
Hello,

This is not issue, just suggestion. 

In system controller, there is a little camera icon and video duration bottom of the video thumbnails. Is it possible to do that with DKImagePickerController?

**Comment by zhangao0086** [comment]
@Chefda 

Thanks.

In fact, I'm making a new version in the `develop` branch :) I think this will make it better :)

**Comment by Chefda** [comment]
@zhangao0086 

Thanks.

I'm looking forward to see new version :)

**Comment by zhangao0086** [comment]
I have bumped version to 2.0.0 :)

**Comment by Chefda** [comment]
@zhangao0086 you rock!
