### ISSUE TITLE
How to covert Asset to UIImage ?

### ISSUE THREAD

**Issue by chikithreddy** [zhangao0086/DKImagePickerController#601]
<img width="705" alt="Screen Shot 2019-06-03 at 7 42 57 PM" src="https://user-images.githubusercontent.com/46279752/58808554-de280a00-8637-11e9-8760-1232c224dfd8.png">

how to convert DKAsset to UIImage here ?

**Comment by zhangao0086** [comment]
Try this:
```swift
for asset in assets {
    asset.fetchFullScreenImage { image, _ in
        // ...
    }
}
```
