### ISSUE TITLE
A Lot of Errors after just install pod

### ISSUE THREAD

**Issue by salmankhalid876** [zhangao0086/DKImagePickerController#602]
I install pod by 
`pod 'DKImagePickerController'`
but I am encountering a lot errors. Why this pod is giving errors on installing just pod?

**Comment by salmankhalid876** [comment]
I installed pod by
pod 'DKImagePickerController'
but I am encountering a lot errors. Why this pod is giving errors on installing just pod?

**Comment by ajaysaini58** [comment]
> I install pod by
> `pod 'DKImagePickerController'`
> but I am encountering a lot errors. Why this pod is giving errors on installing just pod?

try reinstalling the pods. The issue has been resolved. If you are using Swift 5, then xcode will convert the library to swift 5. There might be some warnings, which can be easily fixed by using auto fix option of Xcode. Cheers!

**Comment by zhangao0086** [comment]
Closing this thread
