### ISSUE TITLE
Compatibility with SDWebImage 5

### ISSUE THREAD

**Issue by hstdt** [zhangao0086/DKImagePickerController#603]
`DKImagePickerController` 4.1.4 is not compatibility with `SDWebImage` 5

![image](https://user-images.githubusercontent.com/10215098/59588040-44715a00-9119-11e9-94c6-fcbcff316f75.png)

while `DKImagePickerController`3.8.1 is OK
![image](https://user-images.githubusercontent.com/10215098/59588218-b053c280-9119-11e9-965a-2ea2fee29e9d.png)

**Comment by ajaysaini58** [comment]
I am also getting the same issue. Please resolve.

**Comment by ajaysaini58** [comment]
Everything was working fine 2 days back. Now the code is full of warnings and error. Please resolve this issue. Thanks.

**Comment by ajaysaini58** [comment]
It seems after the update from SdWebImage team, the DKImagePickerController is giving a lot of errors. 
The DkImagePickerController uses SdWebImage.

**Comment by ajaysaini58** [comment]
This issue has been resolved.

**Comment by ajaysaini58** [comment]
> `DKImagePickerController` 4.1.4 is not compatibility with `SDWebImage` 5
> 
> ![image](https://user-images.githubusercontent.com/10215098/59588040-44715a00-9119-11e9-94c6-fcbcff316f75.png)
> 
> while `DKImagePickerController`3.8.1 is OK
> ![image](https://user-images.githubusercontent.com/10215098/59588218-b053c280-9119-11e9-965a-2ea2fee29e9d.png)

Now you can use both of them.

**Comment by hstdt** [comment]
@ajaysaini58  Yes, it fixed😀
