### ISSUE TITLE
Save to custom directory

### ISSUE THREAD

**Issue by yu-t** [zhangao0086/DKImagePickerController#610]
Hi @zhangao0086,

I need to save original images to my own directory in a specific order and then to update the collectionView. But I need to have a callback when all images are fetched. How can I know this?

```
pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
            let numberOfItems = self.collectionView.numberOfItems(inSection: 0)
            for asset in assets {
                let position = numberOfItems + 1
                asset.fetchOriginalImage(completeBlock: { (image, [AnyHashable : Any]?) in
                        self.saveNewPost(image: image, position: position)
                })
            }
```
Or is it possible to save images/videos to a custom directory instead of the tmp and with a custom name? And not to delete them on UIApplicationWillTerminate?

**Comment by zhangao0086** [comment]
You can manually copy or move assets that exported be DKImageAssetExporter to new places.
