### ISSUE TITLE
Failed to load image data for asset

### ISSUE THREAD

**Issue by 350541732** [zhangao0086/DKImagePickerController#611]
when i user this good SDK in my phone which icould is on ,when i selected a photo,it shwos 
error:
Failed to load image data for asset <PHAsset: 0x119b5bd20> mediaType=1/0, sourceType=1, (3024x4032), creationDate=2019-07-26 03:44:54 +0000, location=1, hidden=0, favorite=0  with format 9999

**Comment by zhangao0086** [comment]
I cannot reproduce it :( 
Any stack trace or crash reports will be appreciated 😄

**Comment by pramittewari** [comment]
@zhangao0086 , faced the same issue.
And I've noticed that the failure rate is much higher in iPhones with lower specifications. 

Try using iPhone 6 or so to reproduce.
I saw this in an iPhone6 with 16 GB memory and 1GB RAM.
