### ISSUE TITLE
Get size while selecting the photos

### ISSUE THREAD

**Issue by shindejagdish23** [zhangao0086/DKImagePickerController#612]
Requirement :: **Is it possible to get size or resolution of the image while user select it?**
please do help.
thanks in advance

**Comment by preetamjadakar** [comment]
Hi @shindejagdish23: please do refer https://github.com/zhangao0086/DKImagePickerController/issues/476
Hope this helps!

Cheers!

**Comment by shindejagdish23** [comment]
thanks @preetamjadakar  will refer the solution.

**Comment by zhangao0086** [comment]
Thanks @preetamjadakar Closing this thread.
