### ISSUE TITLE
iOS 13: Force touching an image will result in a crash

### ISSUE THREAD

**Issue by Schlabbi** [zhangao0086/DKImagePickerController#613]
On the iOS 13 developer beta, force touching on an image will result in a crash.

> Assertion failure in -[UIApplication _createStatusBarWithRequestedStyle:orientation:hidden:], /BuildRoot/Library/Caches/com.apple.xbs/Sources/UIKitCore/UIKit-3899.13.13/UIApplication.m:5240
Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'App called -statusBar or -statusBarWindow on UIApplication: this code must be changed as there's no longer a status bar or status bar window. Use the statusBarManager object on the window scene instead.'
libc++abi.dylib: terminating with uncaught exception of type NSException

**Comment by flashspys** [comment]
Will be fixed when https://github.com/zhangao0086/DKPhotoGallery/pull/17 is merged

**Comment by zhangao0086** [comment]
@flashspys Merged! Thanks all!
