### ISSUE TITLE
iOS 13: DKImageAssetExporter doesn't export properly

### ISSUE THREAD

**Issue by jmilillo** [zhangao0086/DKImagePickerController#615]
`DKImageAssetExporter.exportImage` makes a call to `asset.fetchImageData` and looks for `let fileURL = info["PHImageFileURLKey"] as? NSURL`.

This was working for us in iOS 12, with the info dictionary containing 8 keys:
`Dictionary.Keys([AnyHashable(“PHImageFileURLKey”), AnyHashable(“PHImageResultIsPlaceholderKey”), AnyHashable(“PHImageResultIsDegradedKey”), AnyHashable(“PHImageResultDeliveredImageFormatKey”), AnyHashable(“PHImageResultRequestIDKey”), AnyHashable(“PHImageFileSandboxExtensionTokenKey”), AnyHashable(“PHImageResultIsInCloudKey”), AnyHashable(“PHImageResultWantedImageFormatKey”)])`

However, in iOS 13 this gives: `Dictionary.Keys([AnyHashable(“PHImageFileUTIKey”), AnyHashable(“PHImageFileDataKey”), AnyHashable(“PHImageResultIsDegradedKey”), AnyHashable(“PHImageResultRequestIDKey”), AnyHashable(“PHImageFileOrientationKey”)])`

The outcome is all exported assets are given the same default name: `asset.fileName = "Image.jpg"`

**Comment by abhigna-credencys** [comment]
Hello,

I am also facing this same issue, did you find any solution for this?

**Comment by jmilillo** [comment]
I saw this while using `exportsWhenCompleted`.   To get around this I just copied the files manually.

**Comment by zhangao0086** [comment]
Fixed in develop. Thanks!
