### ISSUE TITLE
Change tint color of selected video

### ISSUE THREAD

**Issue by SeungbinBaik** [zhangao0086/DKImagePickerController#619]
I want change bottom tint color when select video. 
even if `self.collectionView.tintColor` not work. (this only change `checked_background` color)
How can I change it?

And all the examples are 404 not found...

**Comment by zhangao0086** [comment]
Hi @SeungbinBaik I have updated the README file to fix the broken links 😅
Let me know if you have any questions 😅

**Comment by SeungbinBaik** [comment]
thanks!!
