### ISSUE TITLE
transfer image from DKasset to custom class

### ISSUE THREAD

**Issue by aldolazuardi** [zhangao0086/DKImagePickerController#62]
Hi @zhangao0086 thank you for great lib. I just wondering how to move image from dkasset to own custom class? thank you

**Comment by zhangao0086** [comment]
Use `fetchFullScreenImageWithCompleteBlock...` like this:
```swift
assets.first?.fetchFullScreenImageWithCompleteBlock({ image, info in
	let object = CustomObject()
	object.image = image
})
```

**Comment by aldolazuardi** [comment]
and how to make all photos in DKAsset to new class?

**Comment by zhangao0086** [comment]
Maybe I should provide a sync method to fetch an image..

**Comment by aldolazuardi** [comment]
yeah that would be great, anyway im using this code

        for asset in photos{
            asset.fetchFullScreenImageWithCompleteBlock({ image, info in
               let images = image
                let data1 = dataImage(userId: "1", value: 1.0, photo: images)
                self.datas += [data1]
                print("*")
            })
        }
        print("datas: \(datas.count)")

i have 6 'image' in photos(DKAsset) and '*' print 6 times, but datas.count is 0, do you have any guess what did i missed?

**Comment by zhangao0086** [comment]
Try this:
```swift
let options = PHImageRequestOptions()
options.deliveryMode = .HighQualityFormat
options.resizeMode = .Exact;
options.synchronous = true

for asset in photos {
	asset.fetchImageWithSize(UIScreen.mainScreen().bounds.size.toPixel(), options: options,
		completeBlock: { image, info in
			let images = image
			let data1 = dataImage(userId: "1", value: 1.0, photo: images)
			self.datas += [data1]
			print("*")
	})
}
print("datas: \(datas.count)")
```

**Comment by aldolazuardi** [comment]
I just found the answer of this problem, turns out it prints 0 because for loop finishes very quickly, while all 6 asset fetches occur in the background. http://stackoverflow.com/questions/34890905/failed-to-input-data-to-class-model-swift/34891231#34891231.

Anyway thank you for the great lib and fast answers bro!

**Comment by zhangao0086** [comment]
Yes, the `fetches` method executed in the background. So you can specific the `synchronous` of the `PHImageRequestOptions ` to `true` like my above answer :)
And I've added two functions to sync fetch images in 3.0.6:
```swift
/**
Fetch an image with the current screen size.

- parameter sync:          If true, the method blocks the calling thread until image is ready or an error occurs.
- parameter completeBlock: The block is executed when the image download is complete.
*/
public func fetchFullScreenImage(sync: Bool, completeBlock: (image: UIImage?, info: [NSObject : AnyObject]?) -> Void)

/**
Fetch an image with the original size.

- parameter sync:          If true, the method blocks the calling thread until image is ready or an error occurs.
- parameter completeBlock: The block is executed when the image download is complete.
*/
public func fetchOriginalImage(sync: Bool, completeBlock: (image: UIImage?, info: [NSObject : AnyObject]?) -> Void)
```

Anyway please let me know if you have any questions :)
