### ISSUE TITLE
Inline camera on some iPhone (6s & 5) picture is tilted

### ISSUE THREAD

**Issue by GaneshKV** [zhangao0086/DKImagePickerController#620]
Hi,

On some of the iphone 6s and iphone 5, using the Inline Camera (even on Demo app) take a selfi landscape mode (home button on right side) is producing a tilted picture. 

How to resolve this? Any help please.

**Comment by mlam-kaydoh** [comment]
adding to Ganesh comment above, when taking the photos in selfi landscape mode (home button on right side), the image is flipped upside down.  When we do the same selfi landscape but with home button on left hand side, no issue with image.

**Comment by zhangao0086** [comment]
Fixed in develop. Thanks!!!
