### ISSUE TITLE
Possible solution for respecting safe area insets of DKImageExtensionPhotoCropper?

### ISSUE THREAD

**Issue by ChopinDavid** [zhangao0086/DKImagePickerController#628]
As I'm sure you are aware, the photo cropper does not respect safe area insets on the bottom of the screen, which is especially noticeable on devices without home buttons, like the iPhone X, iPhone 11, etc.

![dkimagepickercontroller](https://user-images.githubusercontent.com/27712906/67878545-7ce26500-fb09-11e9-9b2d-6cd906c36208.PNG)

Per this solution on TOCropViewController: https://github.com/TimOliver/TOCropViewController/issues/376 I figured that adding `imageCropper.modalPresentationStyle = .fullScreen` to line 48 on DKImageExtensionPhotoCropper.swift would resolve the view controller's lack of respect for safeAreaInsets.bottom, but no change seemed to occur.

In fact, modifying the CropViewController within DKImageExtensionPhotoCropper.swift (via `imageCropper.resetButtonHidden = true`, `imageCropper.aspectRatioPreset = .presetSquare`, etc.) resulted in no change at all in the DKImageExtensionPhotoCropper.

I figured I would at least point out that a more privileged contributor to DKImagePickerController may be able to more easily resolve the issue with safeAreaInsets via possibly adding something like `imageCropper.modalPresentationStyle = .fullScreen` to line 48 on DKImageExtensionPhotoCropper.swift

**Comment by zhangao0086** [comment]
Hi @ChopinDavid Thanks for your detailed explanation 😃
