### ISSUE TITLE
IOS 13 Modal Won't Dismiss, Fix recommended. [BUG]

### ISSUE THREAD

**Issue by orkanylmz** [zhangao0086/DKImagePickerController#629]
presentationControllerShouldDismiss function must not return self.isModalInPresentation, because isModalInPresentation defaults to false, the should dismiss function only called when isModalInPresentation is false, therefore it is never set to true and sheet won't dismiss.

Suggested Solution:

Define a custom variable in DKImagePickerController as shouldPageClose and return this value based on desired behaviour.

**Comment by dailydmello** [comment]
Are you having trouble with the camera not dismissing, after taking a picture?

**Comment by orkanylmz** [comment]
@dailydmello No, I am having trouble with the picker view controller which is presented with the rootVC, I mean the actual picker layout, It won't dismiss with swipe down action as opposed to new IOS 13 sheet presentation.

**Comment by JavierLaguna** [comment]
I have some issue with iOS 13 and use swipe to select/deselect images... the modal close it when I start the swipe

**Comment by zhangao0086** [comment]
Fixed! Thanks!!!
