### ISSUE TITLE
[BUG] allowsLandscape ignored on iPad and camera rotation is broken

### ISSUE THREAD

**Issue by darko55555** [zhangao0086/DKImagePickerController#630]
[pickerController setAllowsLandscape:FALSE] get's ignored on iPad (pro) and rotation is broken.

**Comment by zhangao0086** [comment]
Hi @darko55555 I made some test about allowsLandscape.

### 1. Presented with fullscreen
It works.

### 2. Presented with non-fullscreen(iPhone, iOS 13)
The allowsLandscape of the picker will be _ignored_ both on iPad and iPhone.
In fact the picker returned a correct value:
![image](https://user-images.githubusercontent.com/7742344/68461967-78732600-0246-11ea-9bf3-004b1847a4b9.png)
But it's still rotates. I think this is a system behavior.

#### Solution 1
```swift
pickerController.modalPresentationStyle = .fullScreen
```
#### Solution 2
```swift
// If there are any container view controller, subclass it
// UINavigationController or UITabBarController

    @objc open override var shouldAutorotate : Bool {
        if let topViewController = self.topViewController { // ViewController
            return topViewController.shouldAutorotate
        } else {
            return super.shouldAutorotate
        }
    }

    @objc open override var supportedInterfaceOrientations : UIInterfaceOrientationMask {
        if let topViewController = self.topViewController { // ViewController
            return topViewController.supportedInterfaceOrientations
        } else {
            return super.supportedInterfaceOrientations
        }
    }

// ViewController.swift

    @objc open override var shouldAutorotate : Bool {
        return self.pickerController.shouldAutorotate
    }

    @objc open override var supportedInterfaceOrientations : UIInterfaceOrientationMask {
        return self.pickerController.supportedInterfaceOrientations
    }

    @objc open override var preferredInterfaceOrientationForPresentation: UIInterfaceOrientation {
        return self.pickerController.preferredInterfaceOrientationForPresentation
    }
```

### 3. iPad
It's always not working... `shouldAutorotate`, `supportedInterfaceOrientations` will never be called.
Here is a workaround:
Check the `Requires full screen` in your target:
![image](https://user-images.githubusercontent.com/7742344/68575816-e0747700-04a7-11ea-961d-88cf067f3b6a.png)

---
I finally fixed some bugs about rotate: https://github.com/zhangao0086/DKCamera/compare/006be64a7268bc929092b849eff144454719b679...10cb1e00fadc98517630ad2291d6353b77397fae
Thanks for your issue!
