### ISSUE TITLE
UINavigationBar.appearance().titleTextAttributes is not working on 4.2.0

### ISSUE THREAD

**Issue by JavierLaguna** [zhangao0086/DKImagePickerController#632]
Hi all!!  
Im using the next code on 4.2.0 and its no working.
On the 4.1.7 works

`UINavigationBar.appearance().titleTextAttributes = [
            NSAttributedString.Key.font: Fonts.robotoMedium.withSize(18),
            NSAttributedString.Key.foregroundColor: Color.mainRed
        ]
`

Im getting the title on other font and white color for >iOS 13 and black color for <iOS 13

**Comment by zhangao0086** [comment]
Fixed! Thanks!!!

**Comment by JavierLaguna** [comment]
This will be fixed on the next Cocoa release ?

**Comment by zhangao0086** [comment]
Yes, shipped today(or tomorrow) with 4.2.0

**Comment by JavierLaguna** [comment]
Thank you!
