### ISSUE TITLE
The quality of video capture is bad

### ISSUE THREAD

**Issue by manchan** [zhangao0086/DKImagePickerController#633]
Hello.
I always use this library, very helpful.
but the quality of video capture is bad. 

Can you improve it? Or can it be improved by setting?
`iPhone11 Pro` `iOS13.2`

```
DKImageExtensionController.registerExtension(extensionClass: CustomCameraExtension.self, for: .camera)
```

**Comment by zhangao0086** [comment]
No plan for this. The CustomCameraExtension is just an UIImagePickerController, I think you can implement yourself camera extension :)

**Comment by manchan** [comment]
@zhangao0086 
Thank you for your quick reply.
That was true. need to do is set the video quality in the extension as below.
`picker.videoQuality = .typeHigh`

**Comment by zhangao0086** [comment]
Updated!
