### ISSUE TITLE
Not able to edit image on single selection.

### ISSUE THREAD

**Issue by tejaskdubal** [zhangao0086/DKImagePickerController#634]
Here is my code - 
`              Code - 

                let pickerController = DKImagePickerController()

                pickerController.singleSelect = true

                pickerController.showsCancelButton = true

                pickerController.setEditing(true, animated: true)

                pickerController.didSelectAssets = { (assets: [DKAsset]) in
                    print("didSelectAssets")
                    print(assets)
                }
                self.present(pickerController, animated: true)
`
When I set selction to single not able to edit image it directly naviagte to root controller.
Please help.

**Comment by zhangao0086** [comment]
Hi @tejaskdubal It's an expected behavior. You can implement yourself logic via a custom UIDelegate.
