### ISSUE TITLE
Undefined symbols for architecture i386

### ISSUE THREAD

**Issue by syiasko** [zhangao0086/DKImagePickerController#645]
I have face this compile error out on Xcode 11.3, swift compile version -> swift 5. 
I couldn't compile my apps. I have did remove and reinstall pods. but it still showed the same error below. (for detail, see attachment)
`
Undefined symbols for architecture i386:
  "_OBJC_CLASS_$_FLAnimatedImageView", referenced from:
      type metadata for DKPhotoGallery.DKPhotoImageView in DKPhotoImageView.o
  "_OBJC_METACLASS_$_FLAnimatedImageView", referenced from:
      _OBJC_METACLASS_$__TtC14DKPhotoGallery16DKPhotoImageView in DKPhotoImageView.o
  "_OBJC_CLASS_$_FLAnimatedImage", referenced from:
      objc-class-ref in DKPhotoBaseImagePreviewVC.o
ld: symbol(s) not found for architecture i386
clang: error: linker command failed with exit code 1 (use -v to see invocation)
`

please give me your advice, what should i do?
thank you in advance

<img width="441" alt="Screen Shot 2020-02-24 at 19 46 34" src="https://user-images.githubusercontent.com/33820691/75153964-36131d80-573f-11ea-80f6-a8e75d104df7.png">

**Comment by zhangao0086** [comment]
Hi @syiasko 
Have you tried to Clean & Clean Build Folder?

**Comment by syiasko** [comment]
yes I had, but still got same error.

now, I can run my apps use this workaround. I add manually _DKImageController_ and _DKPhotoGallery_ in **build phases** - **link Binary with libraries** like this.

<img width="830" alt="Screen Shot 2020-02-25 at 17 34 52" src="https://user-images.githubusercontent.com/33820691/75239363-22c28980-57f5-11ea-8c91-a5efcd0fc6e4.png">

**Comment by zhangao0086** [comment]
It's strange...
I'm glad to hear you solved the problem anyway 🙃
