### ISSUE TITLE
IOS Build Failed (Xcode >= 11.3)

### ISSUE THREAD

**Issue by Stanteq** [zhangao0086/DKImagePickerController#648]
Hi, I have a problem with a IOS when I try to build my application after updating the Xcode to the version 11.3 and now 11.4. It's related to DKImagePickerController, bunch of Swift compiler errors.

For example:

```
'pngData()' has been renamed to 'UIImagePNGRepresentation(_:)'
...
'jpegData(compressionQuality:)' has been renamed to 'UIImageJPEGRepresentation(_:_:)'
...
etc
```

**Comment by zhangao0086** [comment]
Hi @Stanteq Please check the **Swift Language Version** of DKImagePickerController and make sure it's **Swift 5**:
![image](https://user-images.githubusercontent.com/7742344/78211557-e2cf8000-74df-11ea-8ea2-bd63d2671fd5.png)
