### ISSUE TITLE
为啥依赖了这么多的库。。。。

### ISSUE THREAD

**Issue by LuckyRoc** [zhangao0086/DKImagePickerController#649]

**Comment by zhangao0086** [comment]
Pod 依赖的多或少对类文件的数量完全没有关系，如果全部采用源码依赖的方式对使用者来说太过粗鲁，因为并不是所有人需要相同的能力：
- DKCamera - 提供相机相关的能力
- DKPhotoGallery - 提供大图预览相关的能力

以目前的插件设计，使用者既可以通过 CocoaPods Subspecs 移除不希望依赖的库，也可以在运行时通过插件依赖自己期望的库，参阅 [Extensions](https://github.com/zhangao0086/DKImagePickerController#extensions)
