### ISSUE TITLE
swift 5 报错

### ISSUE THREAD

**Issue by Goallying** [zhangao0086/DKImagePickerController#650]
![image](https://user-images.githubusercontent.com/12438493/79106635-75f09b80-7da5-11ea-9873-8388d3d00313.png)

**Comment by zhangao0086** [comment]
尝试 Clean 下试试

**Comment by Goallying** [comment]
> 尝试 Clean 下试试

好了，谢谢

**Comment by Goallying** [comment]
![image](https://user-images.githubusercontent.com/12438493/79198970-d8f63700-7e66-11ea-9af2-514986569de0.png)
但是选择多张图片，把DKAsset 转化为UIImage 有点麻烦呀。。

**Comment by zhangao0086** [comment]
> ![image](https://user-images.githubusercontent.com/12438493/79198970-d8f63700-7e66-11ea-9af2-514986569de0.png)
> 但是选择多张图片，把DKAsset 转化为UIImage 有点麻烦呀。。

因为 Photos 这个框架是异步的，图片可能在 iCloud 上，所以需要用异步的方式获取（内部会自动从 iCloud 下载）。
