### ISSUE TITLE
XCODE DOESN'T COMPILE

### ISSUE THREAD

**Issue by juanm4** [zhangao0086/DKImagePickerController#651]
Hi, first of all congratulations for the library, it's great.

When I try to build the project with Xcode it fails. The error is next:

```
Undefined symbols for architecture arm64:
  "_OBJC_CLASS_$_FLAnimatedImageView", referenced from:
      type metadata for DKPhotoGallery.DKPhotoImageView in DKPhotoImageView.o
  "_OBJC_METACLASS_$_FLAnimatedImageView", referenced from:
      _OBJC_METACLASS_$__TtC14DKPhotoGallery16DKPhotoImageView in DKPhotoImageView.o
  "_OBJC_CLASS_$_FLAnimatedImage", referenced from:
      objc-class-ref in DKPhotoBaseImagePreviewVC.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
````
![Captura de pantalla 2020-04-17 a las 13 51 51](https://user-images.githubusercontent.com/4191613/79566346-b0627d00-80b2-11ea-9326-fe1a62626fe8.png)

However, when I execute `tns debug ios` in console it's build perfectly and the app run fine.

What`s happening? Maybe Do I forgot some configuration?

Thanks!

**Comment by zhangao0086** [comment]
Try to clean your project with `Command + Shift + K`.
