### ISSUE TITLE
Crashing after update from 4.3.0 -> 4.3.1

### ISSUE THREAD

**Issue by dneykov** [zhangao0086/DKImagePickerController#658]
4.3.1 is crashing when I try to register custom camera extension.

`DKImageExtensionController.registerExtension(extensionClass: AppCameraExtension.self, for: .camera)`
`Thread 1: EXC_BAD_ACCESS (code=2, address=0x1d01c6e80)`

Any advice? Thanks.

**Comment by zhangao0086** [comment]
Hi @dneykov Could you post your code? I tried the following code, but no `EXC_BAD_ACCESS` happened:
```swift
class AppCameraExtension: DKImageBaseExtension {}
...
DKImageExtensionController.registerExtension(extensionClass: AppCameraExtension.self, for: .camera)
```

**Comment by dneykov** [comment]
Hi @zhangao0086 I'm using it together with library called Eureka for building forms. This is in custom row that I made.

```swift
presentationMode = .presentModally(controllerProvider: ControllerProvider.callback {
            let pickerController = AppAssetPickerController()
            pickerController.singleSelect = true
            pickerController.autoCloseOnSingleSelect = true
            
            DKImageExtensionController.registerExtension(extensionClass: AppCameraExtension.self, for: .camera)
            
            return pickerController
            }, onDismiss: { [weak self] vc in
                self?.select()
                vc.dismiss(animated: true)
        })
```

I just rolled back to 4.3.0 and it is working.

**Comment by dneykov** [comment]
When I have more time I can give it a try again.

**Comment by zhangao0086** [comment]
@dneykov Thanks for your effort! 😃

**Comment by dneykov** [comment]
@zhangao0086 after enabling Address Sanitizer in Xcode issue is gone. Then I disable Address Sanitizer and it keeps working.
