### ISSUE TITLE
[DKImageAssetExporter] [Feature] Add a way to change the compression quality

### ISSUE THREAD

**Issue by erychagov** [zhangao0086/DKImagePickerController#659]
Unfortunately there is no way to change the compression quality and by default it is 0.9 for version below 10.
For versions 10 and above we export with 100% quality.
It would be nice to have a chance to change it.
Also in case version is 10 (or above) we get an enreased image size if we try to export heic image. For example, in my case I get 13Mb instead of original size 2.7Mb

**Comment by erychagov** [comment]
I implemented that feature in this PR:
https://github.com/zhangao0086/DKImagePickerController/pull/660

**Comment by erychagov** [comment]
@zhangao0086 
What do you think about this feature?

**Comment by zhangao0086** [comment]
Merged! Thanks for your PR!!!
