### ISSUE TITLE
Installation Error

### ISSUE THREAD

**Issue by kyhnkrgz** [zhangao0086/DKImagePickerController#67]
First off all thank you for yours working. It is really amazing. 
I did all steps which you write. It looks correctly but when I want to instance DKAsset or DKImagePickerController gives me the error undefined. I researched it and when I change the shcema on my project error fix and build success but in this case application is not run. I use swift in my project. 

May you share something to me about how can ı import the framework and use it correctly in swift.

Thank you so much.

Best Regards.

**Comment by zhangao0086** [comment]
Hello @kyhnkrgz 

Did you use pod?

**Comment by kyhnkrgz** [comment]
Yes I had used. But now I did all steps again and now its work. Thank you again ;)

**Comment by zhangao0086** [comment]
Let me know if you have any questions :)
