### ISSUE TITLE
Xcode 14: Swift Compiler Error: Stored properties cannot be marked potentially unavailable with '@available'

### ISSUE THREAD

**Issue by stx** [zhangao0086/DKImagePickerController#699]
```
Could not build the precompiled application for the device.
Swift Compiler Error (Xcode): Stored properties cannot be marked potentially unavailable with '@available'

Pods/DKImagePickerController/Sources/DKImagePickerController/DKImagePickerController.swift:67:5
```

**Comment by imprecis** [comment]
I have the same issue. Commenting the line '@available(iOS 13.0, *)' solves the issue that I can't run the app, but I can't pick images (I'm using Image Picker for Flutter).

**Comment by zhangao0086** [comment]
Fixed by https://github.com/zhangao0086/DKImagePickerController/pull/700 @pirder

**Comment by pirder** [comment]
@imprecis You can add this Ruby code to your Podfile to filter dependencies you don't need, provided you use the latest tag (in flutter_file_picke)[https://github.com/miguelpruivo/flutter_file_picker/commit/5b9dc6e936d2c4718a79eff3af40c7c0df94e4a7#diff-0a2faa946bbed679bdc47ac3ad86ed462a45ed07653fe2caa377e7999432d52c](url)
<img width="818" alt="image" src="https://user-images.githubusercontent.com/29139348/176113647-3fdf6922-defa-48db-8a92-92c18c2a22f5.png">
`def removeFlutterFilePickerUnwantedPod
  if !Pod.const_defined?(:PICKER_MEDIA) || PICKER_MEDIA
    Pod.const_set(:PICKER_MEDIA, false)
  end
  if !Pod.const_defined?(:PICKER_AUDIO) || PICKER_AUDIO
    Pod.const_set(:PICKER_AUDIO, false)
  end
end
removeFlutterFilePickerUnwantedPod()
`

**Comment by armandojimenez** [comment]
After updating, now It ask me to select a development team, and does not let me compile with Bitcode enabled. Is there any updates with this? I opened issues, I can test my app with ios 16 without a fix for this
