### ISSUE TITLE
Select multi image!

### ISSUE THREAD

**Issue by ban9ban3** [zhangao0086/DKImagePickerController#7]
When i select multi image at many album it got wrong number image selected.
Fix it please.

**Comment by zhangao0086** [comment]
Thanks! @ban9ban3 

But I do not know how to reproduce it... Any hints?

**Comment by ban9ban3** [comment]
Actually your code was correct !!  I'm wrong. Because 1 image can appear in many Album show DKImagePickerController picked them in all album, that is correct logic.

Thanks!!

**Comment by zhangao0086** [comment]
Please tell me if you find other issues. I'm open :)
