### ISSUE TITLE
Add tag 4.3.5 or higher to enable Swift Package Manager versioning support

### ISSUE THREAD

**Issue by richardtop** [zhangao0086/DKImagePickerController#715]
Hi, currently this project has to be used with Swift Package Manager and the only way to use it is to target the "develop" branch directly.
The reason is that it's the only way, as the SPM support has been merged after the 4.3.4 release:
<img width="705" alt="image" src="https://github.com/zhangao0086/DKImagePickerController/assets/8013017/161f7080-3a18-4e30-a909-b7fd5abc4fb0">

Including this project by referencing only the `develop` branch could cause instability into my product, as any breaking change to the `develop` branch will lead to my project not building.

**Proposed solution**

Could you please tag the last commit on the `develop` branch with the 4.3.5 tag or higher? Thanks.

**Comment by zhangao0086** [comment]
Done~
