### ISSUE TITLE
Support App Privacy Manifests

### ISSUE THREAD

**Issue by imk1t** [zhangao0086/DKImagePickerController#718]
## Issue Description
DKImagePickerController was listed on the list of requirements for third-party SDKs announced by Apple.
Is there any push on DKImagePickerController part to include Privacy Manifests files or sign the SDK?
https://developer.apple.com/support/third-party-SDK-requirements/

### What

If this is not addressed, apps containing DKImagePickerController will not be able to be submitted to the AppStore beginning in the spring of 2024.

**Comment by percival888** [comment]
+1  
When will the new version be released

**Comment by Vyazovoy** [comment]
Looks like 4.3.6 has the manifest. But the version was not added to the releases list.

**Comment by jwogan5** [comment]
Do we know when the cocoapods podspec will be updated to 4.3.6 from 4.3.4 for this privacy manifest fix?

**Comment by Vyazovoy** [comment]
@zhangao0086, could you please publish `4.3.6` to Cocoapods? That would help a lot of people.

**Comment by zhangao0086** [comment]
> @zhangao0086, could you please publish `4.3.6` to Cocoapods? That would help a lot of people.

Version 4.3.7 has been published to Cocoapods. I hope this helps everyone~
