### ISSUE TITLE
After selecting image when i again run didSelectAssets function . it Show previous selected photos . How to refresh that?

### ISSUE THREAD

**Issue by davin12x** [zhangao0086/DKImagePickerController#72]

**Comment by zhangao0086** [comment]
You can try this:
```swift
pickerController.defaultSelectedAssets = nil
```

**Comment by davin12x** [comment]
Wow!! Thats easy Fix.. thanks a lot 
Well, i just wanna pick only photo .. i m using .SmartAlbumScreenshots Group type. I want to pick all photo. Which group type is that ??

**Comment by davin12x** [comment]
Wow!! Thats easy Fix.. thanks a lot 
Well, i just wanna pick only photo .. i m using .SmartAlbumScreenshots Group type. I want to pick all photo. Which group type is that ??

**Comment by zhangao0086** [comment]
Just use `pickerController.assetType = .AllPhotos`

**Comment by davin12x** [comment]
Thanks Again ... :)

**Comment by zhangao0086** [comment]
Let me know if you have any questions :)
