### ISSUE TITLE
How can i convert DkAssets to PHAsset

### ISSUE THREAD

**Issue by davin12x** [zhangao0086/DKImagePickerController#74]
in my app i m trying to delete selected photos from camera roll . I tried a lot . But could not figure it out. I also tried to take the value from info which is "PHImageFileURLKey" and delete using  PHAsset.fetchAssetsWithALAssetURLs ..But its not working..so i wanna try fetchAssetsInAssetCollection which is looking for PHAssets  instead of DKAssets....Thanks

**Comment by zhangao0086** [comment]
You can use the DKAsset's `originalAsset` property:
```swift
public class DKAsset: NSObject {
        // ...
	public private(set) var originalAsset: PHAsset?
        // ...
}
```

**Comment by davin12x** [comment]
got u thANKS..
