### ISSUE TITLE
convert data and post image in server

### ISSUE THREAD

**Issue by avinashvaghasiya** [zhangao0086/DKImagePickerController#75]
i am using DKImagePickerController then i select multipal image  in self.assets! 
like.[<DKImagePickerControllerDemo.DKAsset: 0x7fe168e34d70>, <DKImagePickerControllerDemo.DKAsset: 0x7fe168d3c020>, <DKImagePickerControllerDemo.DKAsset: 0x7fe168d71980>]
but how to convert data and post image

**Comment by zhangao0086** [comment]
You can get the data of the selected images like this:
```swift
dispatch_async(dispatch_get_global_queue(0, 0), {
	let options = PHImageRequestOptions()
	options.deliveryMode = .HighQualityFormat
	options.synchronous = true
	
	for (_, asset) in assets.enumerate() {
		asset.fetchImageWithSize(PHImageManagerMaximumSize, options: options) { image, info in
			let imageData = UIImagePNGRepresentation(image?)
		}
	}
})
```

**Comment by avinashvaghasiya** [comment]
hiii
thanks for help!!!!
but i am convert imagedata to base64String then convert it ok
but when i  post to string but in server  add complet
when i get this image when image is only white color show in  image 
plz help me!!

**Comment by zhangao0086** [comment]
Trying to compare the sent base64String and the received base64String.

**Comment by avinashvaghasiya** [comment]
ok i will check it
when base64string add in namutable array then add automatic \n in every line
like this....
this is base64string(only 2-3 line i will show)
mKR+VSgZ+lZsgcoz3pwJP1oGPqRTu49qRDAY5xxSPz74p4Ix1prHA9/89K0SM2Vy
c1ETzUzcfhVdycD3rVIgjc/nVYnPSpmx61WYj/P/ANaqsFiFmqqxzkZ4qWRhmqsh
9eeamxLI3Ix/hVZiM/WnORk81XJHX8azlEljGP5ioWPPB/P9aczH+nNQMeK5Zoka
W5z07UgNISDxmkOPxrkkhMXGTyOTQQcc80vTGe9ICcetZWIZEwP0FRHp71YI68cV
ER6YxW8REJHcc1EcZHNTE4+gqJh29a6ogj//2Q==

then i add in namutablearray

\nkVSj6itBPuy/7tTISKaDK5PYUwADB71JH9w/So+wpi6kqMdxHrxT5QMJ9DUSfe/G
\nppeifQ1PUt7FbJz+IqwyBHXb3qt3H1FXJPvpTYkaGo2saIrDJJ9aboR234x6GrWq
\nf6tKq6H/AMf/AOBrml/CYLcuag2ybylACk8jHqaWKeSK4kjU52jcCeTkdOaj1L/j
\n6X6/1pP+Xyb/AHDXP9hFyKGp3Mt1P50hG5hk44qpM7ucOxPf+lPuvvL9Kif734V2
__________________________________________________________________
why add automatic add \n in array in string
plz ans me how to base64straing add in namutablearray without \n

**Comment by zhangao0086** [comment]
You can test your base64String on http://codebeautify.org/base64-to-image-converter.
Here is the complete code of image to base64String:
```swift
let imageData = UIImagePNGRepresentation(image!)
let base64Data = imageData!.base64EncodedDataWithOptions(.Encoding64CharacterLineLength)
let base64String = NSString(data: base64Data, encoding: NSUTF8StringEncoding)
print(base64String!)
```

**Comment by avinashvaghasiya** [comment]
you are right and i also write same code but when base64string add in to namutable arrye when added complet but i don't know, why add \n in each line like this
\nkVSj6itBPuy/7tTISKaDK5PYUwADB71JH9w/So+wpi6kqMdxHrxT5QMJ9DUSfe/G
\nppeifQ1PUt7FbJz+IqwyBHXb3qt3H1FXJPvpTYkaGo2saIrDJJ9aboR234x6GrWq
\nf6tKq6H/AMf/AOBrml/CYLcuag2ybylACk8jHqaWKeSK4kjU52jcCeTkdOaj1L/j
\n6X6/1pP+Xyb/AHDXP9hFyKGp3Mt1P50hG5hk44qpM7ucOxPf+lPuvvL9Kif734V2

**Comment by zhangao0086** [comment]
I also add the base64String into a mutable array, but no \n?
```swift
let imageData = UIImagePNGRepresentation(image!)
let base64Data = imageData!.base64EncodedDataWithOptions(.Encoding64CharacterLineLength)
let base64String = NSString(data: base64Data, encoding: NSUTF8StringEncoding)
print(base64String!)

var arr = [base64String]
print(arr)
```
```
[Optional(iVBORw0KGgoAAAANSUhEUgAAApAAAAJICAIAAABZukNFAAAMF2lDQ1BJQ0MgUHJv
ZmlsZQAASImVlwdUU0kXx+eVFEJCC0RASuhNkF6l9450sBGSAKHEkBBU7MiigmtB
RQRFRVdEbGsBZK3YyyLY+0YRFWVdLGBB5ZskgK77lfPdc+a9X+7cufOfycw7MwAo
O7IEglxUBYA8foEwNtiPmZySyiRJAAKoQAVYAAsWWyTwjYmJANBG3n+3gZswGto1
a2muf9b/V1PlcEVsAJAYyOkcETsP8kEAcG22QFgAAKED+o1mFAik/A6yuhAKBIBI
lnKmnHWknC5nW1lMfKw/5AAAyFQWS5gJgJI0P7OQnQnzKAkg2/I5PD7kzZC92Fks
xuHyE4a1YXB1+cUOty0V5MYMx2O13NzgWPk8Y/tEhXEjba8WwAUmnwfscTYrLEau
...
wCPgEfAIfOsIBA89NJZzzJinp03/wpF0+8/Ny/eEvTke/ptHwCPgEfAIeAS+KwQC
6Nn50zjW8UZNtOZMaPlwf3gEPAIeAY+AR8AjsK0gIMJuiDfD1o6qWy+2FQW9Hh4B
j4BHwCPgEfAIsJZ4K0/X2x6adfVsyeUPj4BHwCPgEfAIeAS2LQSCxqZEY8KWOyM4
3PxsFPRLkG5bb8lr4xHwCHgEPAI/eATwsMXWLIoCc4NGix3NbM3lD4+AR8Aj4BHw
CHgEthkE8LBtVw/RdnNTkyZge7beZt6OV8Qj4BHwCHgEPAIhAv8Hdix4jaoMxrIA
AAAASUVORK5CYII=)]
```

**Comment by avinashvaghasiya** [comment]
thanks  for help
plz one more que.
how to upload video post in sever same as image to bas64staring
how they convert and send

**Comment by zhangao0086** [comment]
You can get the data of video like this:
```swift
let videoData = NSData(contentsOfURL: videoURL)
```
then converting to base64String:
```swift
let base64Data = videoData!.base64EncodedDataWithOptions(.Encoding64CharacterLineLength)
let base64String = NSString(data: base64Data, encoding: NSUTF8StringEncoding)
```

**Comment by zhangao0086** [comment]
Closing...
