### ISSUE TITLE
Synchronous options for multiple video fetch

### ISSUE THREAD

**Issue by KimCrab** [zhangao0086/DKImagePickerController#76]
Is it possible to give [options] parameter to **fetchAVAssetWithCompleteBlock** method??

I can't fine document about it.

Give me some light.

**Comment by zhangao0086** [comment]
See also:[PHImageRequestOptions](https://developer.apple.com/library/prerelease/ios/documentation/Photos/Reference/PHImageRequestOptions_Class/index.html)

**Comment by zhangao0086** [comment]
I'm sorry for my late reply...
I've added an API to fetch AVAsset that receives a `PHVideoRequestOptions` parameter.

```swift
/**
Fetch an AVAsset with a completeBlock and PHVideoRequestOptions.
*/
public func fetchAVAsset(options: PHVideoRequestOptions?, completeBlock: (AVAsset: AVURLAsset?) -> Void) {
	getImageManager().fetchAVAsset(self, options: options, completeBlock: completeBlock)
}
```

**Comment by KimCrab** [comment]
@zhangao0086 

Wow It seems great! 
But how can I change synchronous value to TRUE?
**PHVideoRequestOptions** does not have synchronous value.

public class PHVideoRequestOptions : NSObject {
    public var networkAccessAllowed: Bool
    public var version: PHVideoRequestOptionsVersion
    public var deliveryMode: PHVideoRequestOptionsDeliveryMode
    public var progressHandler: PHAssetVideoProgressHandler?
}

Plus, Can you give me a small example how to pass Options to function **fetchAVAsset**?

Thanks in advance

**Comment by zhangao0086** [comment]
The PHVideoRequestOptions does not support synchronous...
I'll add some helper function to do it.

**Comment by KimCrab** [comment]
@zhangao0086 

That's awesome.

Please let me know when you finished.

**Comment by zhangao0086** [comment]
I've add a function to sync fetch AVAsset:
```swift
/**
Sync fetch an AVAsset with a completeBlock and PHVideoRequestOptions.
*/
public func fetchAVAsset(sync: Bool, options: PHVideoRequestOptions?, completeBlock: (AVAsset: AVURLAsset?) -> Void) {
	if sync {
		let semaphore = dispatch_semaphore_create(0)
		self.fetchAVAsset(nil, completeBlock: { (AVAsset) -> Void in
			completeBlock(AVAsset: AVAsset)
			dispatch_semaphore_signal(semaphore)
		})
		dispatch_semaphore_wait(semaphore, DISPATCH_TIME_FOREVER)
	} else {
		self.fetchAVAsset(nil, completeBlock: completeBlock)
	}
}
```

**Comment by KimCrab** [comment]
@zhangao0086  Wow.. You are AWESOME!!  What a quick response!
Thanks dude. I'll close the issue.
