### ISSUE TITLE
Cannot get all photos? 

### ISSUE THREAD

**Issue by davin12x** [zhangao0086/DKImagePickerController#78]
Hi . I m facing a problem . When i selected multiple photo e.x 18 photos selected ..It return me less photo instead of all.Here is my code
  let pickerController = DKImagePickerController()
 var images:[UIImage] = []

pickerController.didSelectAssets = { (assets: [DKAsset]) in
            print(assets.count)                                          // This return me exact same value which i select
            for asset in assets {
                asset.fetchOriginalImageWithCompleteBlock({ (image, info) -> Void in
                    print(image)                                            //return less images
                    self.images.append(image!)                      
                    print(self.images.count)                          //Return less images count
                })
            }
        }
        self.presentViewController(pickerController, animated: true) {}

can u help me out . Am i wrong someWhere ?

**Comment by zhangao0086** [comment]
The `fetchOriginalImageWithCompleteBlock` method is executed on a background thread. You should print the `self.images.count` after the all `fetchOriginalImageWithCompleteBlock` are completed.

**Comment by davin12x** [comment]
it still same .. But when i use this code
                 for asset in assets {
                asset.fetchImageWithSize(CGSize(width: 200, height: 200), options: PHImageRequestOptions?.init(), completeBlock: { (image, info) -> Void in
                    self.images.append(image!)
                })
This give me all the value. When i change the CZsize according to original image. Then it again gives me less value

**Comment by zhangao0086** [comment]
Try this:
```swift
pickerController.didSelectAssets = { (assets: [DKAsset]) in
	print(assets.count)

	dispatch_async(dispatch_get_global_queue(0, 0), {
	    let options = PHImageRequestOptions()
	    options.deliveryMode = .HighQualityFormat
	    options.synchronous = true

	    for (_, asset) in assets.enumerate() {
	        asset.fetchImageWithSize(PHImageManagerMaximumSize, options: options) { image, info in
	            self.images.append(image!)
	        }
	    }

	    print(self.images.count)
	})
}
```

**Comment by davin12x** [comment]
![scren](https://cloud.githubusercontent.com/assets/6825007/13374355/36fc00f8-dd50-11e5-8120-4b79fc508c09.png)
thanks for replying . i used this code and most of time it crashed when selecting more than 1 photo..But some time it works ..

**Comment by zhangao0086** [comment]
Could you post the error stacktrace?

**Comment by davin12x** [comment]
![stack trace](https://cloud.githubusercontent.com/assets/6825007/13380876/28881dec-de1b-11e5-8f22-f005261db598.png)
i think i have infinite  loop is going on there...I really appreciate that you are helping me

**Comment by zhangao0086** [comment]
Could you try to replace the condition
```swift
if let isInCloud = info?[PHImageResultIsInCloudKey]?.boolValue
    where isInCloud && self.autoDownloadWhenAssetIsInCloud {
```
to
```swift
if let isInCloud = info?[PHImageResultIsInCloudKey]?.boolValue
	where image == nil && isInCloud && self.autoDownloadWhenAssetIsInCloud {
```

Let me know if that works :)

**Comment by davin12x** [comment]
You are awesome. THANKS A LOT !!!! YOU  saved my life. I was scratching my head ..calling my self totaly dumb..Thanks ..So the problem was downloading images from cloud ..Thanks Again
