### ISSUE TITLE
Quick Question For  A Beginner 

### ISSUE THREAD

**Issue by AdventuresOfMar** [zhangao0086/DKImagePickerController#79]
Hello, Can I just start off by saying thank you for such an incredible project.  I've created something similar but far less complicated. My question is this, Is it possible to call an image picker on view did load. For the demo that you provided in VIewController at view did load I called for your show method providing the needed specifications. 
I end up getting an error <DKImagePickerControllerDemo.DKImagePickerController: 0x12582ee00> on <DKImagePickerControllerDemo.ViewController: 0x124e458f0> whose view is not in the window hierarchy!. Not sure where I am going wrong
  override func viewDidLoad() {
        super.viewDidLoad()
        showImagePickerWithAssetType(
            .AllAssets,
            allowMultipleType: false,
            sourceType: .Photo,
            allowsLandscape: true,
            singleSelect: false
        )

  }

**Comment by zhangao0086** [comment]
Trying to call in `viewDidAppear`.

**Comment by AdventuresOfMar** [comment]
Great, i was actually able to accomplish by adding this to viewDidLoad pickerController.didSelectAssets = { (assets: [DKAsset]) in
            print("didSelectAssets")
            print(assets)
        }
        
        pickerController.assetType =  .AllAssets
        pickerController.allowsLandscape = true
        pickerController.allowMultipleTypes = true
        ///pickerController.sourceType = .Photo
        pickerController.singleSelect = false
        //			pickerController.showsCancelButton = true
        //			pickerController.showsEmptyAlbums = false
        //			pickerController.defaultAssetGroup = PHAssetCollectionSubtype.SmartAlbumFavorites
        
        // Clear all the selected assets if you used the picker controller as a single instance.
        //			pickerController.defaultSelectedAssets = nil
        pickerController.defaultSelectedAssets = self.assets
        
        pickerController.didSelectAssets = { [unowned self] (assets: [DKAsset]) in
            print("didSelectAssets")
            
            self.assets = assets
            //self.previewView?.reloadData()
        }
        
        if UI_USER_INTERFACE_IDIOM() == .Pad {
            pickerController.modalPresentationStyle = .FormSheet;
        }

        
        self.presentViewController(pickerController, animated: true) {}.

One more question, what parameters need to be met in order to call for a separate camera instead of DKCamera

**Comment by zhangao0086** [comment]
Currently don't support that. If you can provide a PR, that would be great :)

**Comment by zhangao0086** [comment]
Let me know if you have any questions
