### ISSUE TITLE
Getting the name of the image.

### ISSUE THREAD

**Issue by GABHISEKBUNTY** [zhangao0086/DKImagePickerController#82]
I am trying out your wonderful ImagePicker in my new project. I am allowing users to select multiple images & hence in turn,when they select the images **I want to display the user the name of the images. How can I achieve that? **

**Comment by zhangao0086** [comment]
Maybe the `info` is what you want:
![e290bcfd-2cfd-4631-91d0-82fd48c71873](https://cloud.githubusercontent.com/assets/7742344/13449602/11367b94-e068-11e5-9212-0133356b1f68.png)

**Comment by GABHISEKBUNTY** [comment]
Ya, I got that by the help of this -

`func fetchImages()
    {
        self.imagecount = 0
        dispatch_async(dispatch_get_global_queue(0, 0), {
            let options = PHImageRequestOptions()
            options.deliveryMode = .HighQualityFormat
            options.synchronous = true
            for (_, asset) in self.assets!.enumerate()
            {
                
                asset.fetchImageWithSize(PHImageManagerMaximumSize, options: options) { image, info in
                    let imageData = UIImagePNGRepresentation(image!)
                   let imageName = ((info!["PHImageFileURLKey"]!.lastPathComponent!) as NSString).stringByDeletingPathExtension
                    print(((info!["PHImageFileURLKey"]!.lastPathComponent!) as NSString).stringByDeletingPathExtension)
                    
                    self.imageArray.insertObject(imageData!, atIndex: self.imagecount)
                    self.imageNameArray.insertObject(imageName, atIndex: self.imagecount)
                    self.imagecount++
                   
                }
                
            }
        })
        
        print(imageNameArray)
    }

`

**Comment by zhangao0086** [comment]
That's right :+1:

**Comment by zhangao0086** [comment]
Closing...
