### ISSUE TITLE
Can we have an intermediate view for Camera

### ISSUE THREAD

**Issue by ZahidKsoft** [zhangao0086/DKImagePickerController#83]
Can we have an intermediate view where the picture taken from camera will be shown along with the Accept and Cancel as the available options so that the user can discard the pic if see any issue with that

**Comment by zhangao0086** [comment]
If you can provide a patch, that would be great!

**Comment by hyouuu** [comment]
I addressed the issue with https://github.com/zhangao0086/DKImagePickerController/pull/84 :)

**Comment by zhaozhongke** [comment]
Use library DZNPhotoPickerController !

**Comment by zhangao0086** [comment]
In `3.1.0`, I've added support for custom camera.
