### ISSUE TITLE
Twitter Like Implementation 

### ISSUE THREAD

**Issue by ThePhantomKid** [zhangao0086/DKImagePickerController#85]
Hello, Can anyone assist me in using this to create a twitter like post view controller where the image picker loads under the post option and once the image picker view is swiped up the image picker loads fully
![img_1181](https://cloud.githubusercontent.com/assets/17694834/13559845/534e6d9e-e3e6-11e5-813c-bebbee1d1d95.PNG)

**Comment by zhangao0086** [comment]
Currently not supported...

**Comment by sash83** [comment]
I want to use the same Twitter like approach. Basically you will leave out the tableview and present the collectionview without any options to choose asset types. Should be possible, isn't it?

**Comment by zhangao0086** [comment]
I like the Twitter approach. I will support later.

**Comment by sash83** [comment]
Have you made any progress with that implementation?

**Comment by zhangao0086** [comment]
Done.
