### ISSUE TITLE
Obj C HighQualityFormat does not return images

### ISSUE THREAD

**Issue by kprigel** [zhangao0086/DKImagePickerController#88]
When using option for HighQualityFormat in Objective C, images never return.  

Code as used (aSelected is array of selected images):

for (int i = 0; i < aSelected.count; i++)
        {
            CGSize imageSize=CGSizeMake(1153, 1153);
            
            PHImageRequestOptions* options = [[PHImageRequestOptions alloc] init] ;
            options.synchronous = YES;
            options.version = PHImageRequestOptionsVersionCurrent;
            options.deliveryMode = PHImageRequestOptionsDeliveryModeHighQualityFormat;
            options.resizeMode=PHImageRequestOptionsResizeModeFast;
            options.networkAccessAllowed = YES;

            DKImageManager *cont = [DKImageManager new];

[cont fetchImageForAsset:aSelected[i] size:imageSize options:options completeBlock:^(UIImage * imageSelected, NSDictionary * info){
[self uploadContentImage:imageSelected];
   }];

**Comment by zhangao0086** [comment]
Trying to use `asset.fetchXXX` instead of `DKImageManager`:
```swift
aSelected[i].fetchImageWithSize(imageSize, options: options, completeBlock: { (image, info) -> Void in
	[self uploadContentImage:imageSelected];
})
```

**Comment by zhangao0086** [comment]
ping...

**Comment by zhangao0086** [comment]
Closing the thread... Feel free to reopen it, though! Just provide some more information! 😄
