### ISSUE TITLE
How to change image of first cell

### ISSUE THREAD

**Issue by tranduytan248** [zhangao0086/DKImagePickerController#90]
Hi!

I need to change image of first cell when select DKImagePickerControllerAssetType
Image selection is one other picture and filming is another image

**Comment by zhangao0086** [comment]
I'll add an `UIDelegate` property that will support custom UI.

**Comment by tranduytan248** [comment]
How to get length video?

**Comment by zhangao0086** [comment]
You can use the `duration` property of the `DKAsset`.

**Comment by tranduytan248** [comment]
No, length is size of video :)

**Comment by zhangao0086** [comment]
Try this:
```swift
asset.fetchAVAssetWithCompleteBlock { (avAsst) -> Void in
	do {
		var fileSize: AnyObject?
		try avAsst?.URL.getResourceValue(&fileSize, forKey: NSURLIsDirectoryKey)
		if let number = fileSize as? NSNumber {
			if number == true {
				// do something
			}
		}
	} catch {
	}
}
```

**Comment by zhangao0086** [comment]
In `3.1.0`, you can use your custom image to instead of default image:
![53f56f68-4538-487f-9ef4-bf0fe0372c1d](https://cloud.githubusercontent.com/assets/7742344/13870198/1881ff66-ed17-11e5-816e-37d23bdf7026.png)

**Comment by tranduytan248** [comment]
![screen-shot-2016-03-18-at-2 11 28-pm](https://cloud.githubusercontent.com/assets/9839231/13871052/ee5a6122-ed13-11e5-93a1-b4d25790b17e.png)
how to replace image to image default?

**Comment by zhangao0086** [comment]
Like this:
```swift
public class CustomUIDelegate: DKImagePickerControllerDefaultUIDelegate {
	
	public override func imagePickerControllerCameraImage() -> UIImage {
		return UIImage()
	}
	
}
```

then 
```swift
pickerController.UIDelegate = CustomUIDelegate()
```

**Comment by tranduytan248** [comment]
Thank,

And your code always return 0
`asset.fetchAVAssetWithCompleteBlock { (avAsst) -> Void in
    do {
        var fileSize: AnyObject?
        try avAsst?.URL.getResourceValue(&fileSize, forKey: NSURLIsDirectoryKey)
        if let number = fileSize as? NSNumber {
            // do something
        }
    } catch {
    }
}`

**Comment by zhangao0086** [comment]
Ohhh...My fault.... You should use `NSURLFileSizeKey` instead of `NSURLIsDirectoryKey`...

**Comment by tranduytan248** [comment]
thank you!
DKImagePickerController is the best

**Comment by zhangao0086** [comment]
Let me know if you have any question :)
