### ISSUE TITLE
keep the ratio when using fetchImageWithSize

### ISSUE THREAD

**Issue by zhiyanshao** [zhangao0086/DKImagePickerController#93]
Is there an option to detect or keep the ratio when using this size one? In that case, the size specified would be the max height and the max width for the compressed image.  

For example, if I specify the size to be CGSize(width: 1200, height: 1200), the image will always be cut into 1200 * 1200 square. If the original ratio is 4:3 and 2000:1500, I'd like to have the UIImage to be 1200 * 900. Thanks!

**Comment by zhiyanshao** [comment]
Actually I used fetchFullScreenImage instead which keeps the original ratio and is much faster than fetchOriginalImage

**Comment by aldolazuardi** [comment]
@zhangao0086 First of all i want to say thank you for such a great library! but i want to ask same question, how to keep the ratio with fetchImageWithSize? when i use fetchOriginalImage app would crash but if im using fetchOriginalImage its too small.

**Comment by aldolazuardi** [comment]
(kinda) found the solution. I changed func in fetchOriginalImage in DKAsset from

`getImageManager().fetchImageForAsset(self, size: PHImageManagerMaximumSize, options: options)` to `getImageManager().fetchImageForAsset(self, size:  CGSize(width: 1500, height: 1500), contentMode: .AspectFit)` it keeps the ratio with 1500px maximum pixel

**Comment by atongmu518** [comment]
I can get it :

asset.fetchOriginalImageWithCompleteBlock({ (image, info) in
                            let width: CGFloat = image!.size.width
                            let height: CGFloat = image!.size.height
                            
                            let realWidth: CGFloat = 740  //the max width
                            var realHeight: CGFloat = 0
                            if width < realWidth {
                                realHeight = height
                            } else {
                                realHeight = realWidth * height / width
                            }
                            
                            asset.fetchImageWithSize(CGSizeMake(realWidth, realHeight), completeBlock: { (image, info) in
                                if let uploadImag  = image { // this is the image to keep the ratio
                                    
                                }
                            })
                            
                        })

**Comment by zhiyanshao** [comment]
@atongmu518 so basically you get the image twice. I think it may still crash if you select too many photos. For me, it crashed after selecting 6 or more on iphone 6 plus.

**Comment by atongmu518** [comment]
@zhiyanshao
another solution is extension the DKAssect, just like @aldolazuardi 
```
extension DKAsset {
    func getImageWithSize(size:CGSize, completeBlock: (image: UIImage?, info: [NSObject : AnyObject]?) -> Void) {
        getImageManager().fetchImageForAsset(self, size:size , contentMode: .AspectFit) { (image, info) in
            completeBlock(image: image, info: info)
        }
    }
}

```

**Comment by zhangao0086** [comment]
Hi all, first of all I'm sorry for the late response...

In the latest version, I've optimized for fetching original image. I think I've solved the crash issue.
(You can try to selecting 100 photos :smiley: )

And I've add an API to fetch image with contentModel:
```swift
public func fetchImageWithSize(size: CGSize, options: PHImageRequestOptions?, contentMode: PHImageContentMode, completeBlock: (image: UIImage?, info: [NSObject : AnyObject]?) -> Void)
```
By default,  the `fetchImageWithSize` method fetching image with `.AspectFit`.

Let me know if you have any questions :)
