### ISSUE TITLE
App crash when click on group button

### ISSUE THREAD

**Issue by sahara108** [zhangao0086/DKImagePickerController#94]
Step to reproduce:
    1. Open DKImagePickerController
    2. Leave the app and open Photos app. Create or delete a album
    3. Back to the application and tap on group button ==> app crash.

**Comment by zhangao0086** [comment]
I have tried these steps but not crash happen... Could you provide some console log? Thanks in advanced :)

**Comment by zhangao0086** [comment]
ping...
