### ISSUE TITLE
Crash when selecting more than 5 photos using fetchOriginalImage

### ISSUE THREAD

**Issue by zhiyanshao** [zhangao0086/DKImagePickerController#95]
I am using iPhone 6 plus with iOS 9.2.

**Comment by zhangao0086** [comment]
Could you post more information about your code?

**Comment by zhangao0086** [comment]
In the latest version, I've optimized for fetching original image.
Please try it :)

**Comment by yanjinww** [comment]
@zhangao0086 the compile fails with the latest version (3.1.3)

**Comment by zhangao0086** [comment]
Hi @yanjinww  
Could you post your error info?

**Comment by zhangao0086** [comment]
See the thread:https://github.com/zhangao0086/DKImagePickerController/issues/116
