### ISSUE TITLE
didSelectAssets block is called twice.

### ISSUE THREAD

**Issue by JettF** [zhangao0086/DKImagePickerController#96]
I am using DKImagePickerController with all of the default settings.

After opening the picker, I select the camera button, then take a photo. This calls the `didSelectAssets` block when the camera is dismissed. Then when I select the 'done' button, `didSelectAssets` is called again. 

In my `didSelectAssets` block, I am appending the new images to my array, and because `didSelectAssets` is called twice, a copy of the photo from the camera is added to my array.

I advocate that `didSelectAssets` only be called once when the picker is dismissed. That way duplicates are not created if appending to an array, or resetting the array.

**Comment by zhangao0086** [comment]
Thanks! 
It's a bug. Fixed :)
