### ISSUE TITLE
Custom Camera with the DKImagePickerController

### ISSUE THREAD

**Issue by Danielthenew** [zhangao0086/DKImagePickerController#98]
I want to make a Custom Camera with the DKImagePickerController so i have seen this code to make that but this Protocol `DKImagePickerControllerUIDelegate ` does not exist when i implement the DKImagePickerController. So give it a another way to make a custom camera or have you an idea what i can make there and my second question can i take videos with this camera or only photos ?? 
Thank you for your Help. 

`public class CustomUIDelegate: DKImagePickerControllerUIDelegate {

    @objc public func imagePickerControllerCreateCamera(imagePickerController: DKImagePickerController, didCancel: (() -> Void), didFinishCapturingImage: ((image: UIImage) -> Void)) -> UIViewController {
        let vc = UIViewController()
        vc.view.backgroundColor = UIColor.redColor()

        let delayTime = dispatch_time(DISPATCH_TIME_NOW, Int64(2 * Double(NSEC_PER_SEC)))
        dispatch_after(delayTime, dispatch_get_main_queue()) {
            didCancel()
        }

        return vc
    }
}`

Thanks for your Help.

**Comment by zhangao0086** [comment]
Hi @Danielthenew 
In https://github.com/zhangao0086/DKImagePickerController/pull/102, I've added an example using `UIImagePickerController` and that support video capture.

Let me know if you have any questions :)

**Comment by Danielthenew** [comment]
Thanks for your Help :) 
So i have one more question i would like to get the date from a Picture when i take it from the DKImagePicker Photo and Video Library.
I have tried with `asset.originalAsset?.creationDate` but he make the topical date. 

`            pickerController.didSelectAssets = { (assets: [DKAsset]) in
        
                 for asset in assets {
                    asset.fetchOriginalImageWithCompleteBlock({ (image, info) -> Void in
                        
                        let date = asset.originalAsset?.creationDate
`

**Comment by zhangao0086** [comment]
Feel free to re-open if your issue is not solved.
